! (C) Copyright 2000- ECMWF.
! (C) Copyright 2013- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE BUTTERFLY_ALG_DP_MOD
USE PARKIND_ECTRANS, ONLY : JPRD, JPRM, JPIM, JPRB, JPRBT, JPIB
USE INTERPOL_DECOMP_MOD, ONLY : COMPUTE_ID
USE SHAREDMEM_MOD, ONLY : SHAREDMEM, SHAREDMEM_ASSOCIATE
USE ECTRANS_BLAS_MOD, ONLY : GEMM, GEMV

IMPLICIT NONE

PRIVATE
PUBLIC NODE_TYPE,LEV_STRUCT,BUTTERFLY_STRUCT,CONSTRUCT_BUTTERFLY,MULT_BUTV,MULT_BUTM,CLONE,&
 & PACK_BUTTERFLY_STRUCT,UNPACK_BUTTERFLY_STRUCT,FREE_BUTTERFLY,&
 & BUTTERFLY_GPU_GROUPS,BUTTERFLY_GPU_LEVEL,BUTTERFLY_GPU_PLAN,&
 & HYBRID_BLOCK,HYBRID_MATRIX,CONSTRUCT_HYBRID,FREE_HYBRID,&
 & HYBRID_DENSE,HYBRID_LOW_RANK,HYBRID_BUTTERFLY,&
 & ANALYZE_LEGENDRE_TRUNCATION,LEGENDRE_TRUNCATION_DIAGNOSTICS_REQUESTED,&
 & BUTTERFLY_COST,ANALYZE_TRANSPOSED_HYBRID,CONSTRUCT_TRANSPOSED_HYBRID

INTEGER(KIND=JPIM),PARAMETER :: HYBRID_DENSE=1
INTEGER(KIND=JPIM),PARAMETER :: HYBRID_LOW_RANK=2
INTEGER(KIND=JPIM),PARAMETER :: HYBRID_BUTTERFLY=3

TYPE BUTTERFLY_GPU_GROUPS
INTEGER(KIND=JPIM) :: COUNT=0
INTEGER(KIND=JPIM) :: TILE_COUNT=0
INTEGER(KIND=JPIM),ALLOCATABLE :: N(:),K(:),LDB(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: TILE_GROUP(:),TILE_START(:)
INTEGER(KIND=JPIB),ALLOCATABLE :: SRC_COL(:),DST_COL(:),FACTOR_OFFSET(:),&
  & PIVOT_OFFSET(:)
END TYPE BUTTERFLY_GPU_GROUPS

TYPE BUTTERFLY_GPU_LEVEL
TYPE(BUTTERFLY_GPU_GROUPS) :: FWD,REV_ODD,REV_EVEN
END TYPE BUTTERFLY_GPU_LEVEL

TYPE BUTTERFLY_GPU_PLAN
LOGICAL :: ENABLED=.FALSE.
LOGICAL :: COMPACT_ID=.FALSE.
LOGICAL :: FUSE_FINAL=.FALSE.
LOGICAL :: RECOMPRESS_FINAL=.FALSE.
INTEGER(KIND=JPIM) :: MAX_LEVELS=0
INTEGER(KIND=JPIM) :: CANDIDATE_COUNT=0
INTEGER(KIND=JPIM) :: SELECTED_COUNT=0
INTEGER(KIND=JPIM) :: DENSE_BLOCKS=0,LOW_RANK_BLOCKS=0,BUTTERFLY_BLOCKS=0
INTEGER(KIND=JPIB) :: BETA_COLS=0,EVEN_BETA_COLS=0,WORK_COLS=0
INTEGER(KIND=JPIB) :: DENSE_COST=0,HYBRID_COST=0
INTEGER(KIND=JPIB) :: FINAL_FACTOR_VALUES=0,FINAL_GATHER_COUNT=0
INTEGER(KIND=JPIB) :: FINAL_ORIGINAL_COST=0,FINAL_EXEC_COST=0
INTEGER(KIND=JPIM) :: FINAL_RECOMPRESSED_GROUPS=0,FINAL_DIRECT_GROUPS=0
LOGICAL,ALLOCATABLE :: USE_HYBRID(:)
REAL(KIND=JPRBT),POINTER :: FACTORS(:) => NULL()
INTEGER(KIND=JPIM),ALLOCATABLE :: PIVOTS(:)
INTEGER(KIND=JPIB),ALLOCATABLE :: FINAL_GATHER_SRC(:),FINAL_GATHER_DST(:)
TYPE(BUTTERFLY_GPU_GROUPS) :: LEVEL0,FINAL
TYPE(BUTTERFLY_GPU_GROUPS) :: FINAL_FUSED
TYPE(BUTTERFLY_GPU_GROUPS) :: FINAL_PROJECT,FINAL_BASIS
TYPE(BUTTERFLY_GPU_GROUPS) :: DENSE
TYPE(BUTTERFLY_GPU_LEVEL),ALLOCATABLE :: LEVEL(:)
END TYPE BUTTERFLY_GPU_PLAN

! Butterfly package.

! Butterfly algorithm for matrix multiplication
! Coded from: "An algorithm for the rapid evaluation of special function transform" by
! Michael O'Neill, Franco Woolfe and Vladimir Rohklin, Appl.Comput.Harmon.Anal. 2009?
! referred to in the following as ONWR

TYPE NODE_TYPE
INTEGER(KIND=JPIM) :: ILEV    =0   ! Level of this node
INTEGER(KIND=JPIM) :: IFCOL   =0   ! First column
INTEGER(KIND=JPIM) :: ILCOL   =0   ! Last column
INTEGER(KIND=JPIM) :: IFROW   =0   ! first row
INTEGER(KIND=JPIM) :: ILROW   =0   ! Last row
INTEGER(KIND=JPIM) :: ICOLS   =0   ! Number of columns
INTEGER(KIND=JPIM) :: IROWS   =0   ! Number of rows
INTEGER(KIND=JPIM) :: IRANK   =0   ! Rank of interpolative decomposition
INTEGER(KIND=JPIM) :: IOFFBETA=0   ! Offset in "beta" work space
INTEGER(KIND=JPIM),POINTER :: ICLIST(:) => NULL() ! List of columns in B (column skeleton matrix)
REAL(KIND=JPRB),POINTER :: PNONIM(:)  => NULL() ! Non-identety part of interpolation matrix
REAL(KIND=JPRB),POINTER :: B(:,:)  => NULL()  ! Column skeleton matrix
REAL(KIND=JPRD),POINTER :: DB(:,:)  => NULL()  ! Column skeleton matrix, as part of pre-computations only
END TYPE NODE_TYPE

TYPE LEV_STRUCT
INTEGER(KIND=JPIM) :: IJ      =0  ! Number of row boxes at this level
INTEGER(KIND=JPIM) :: IK      =0  ! Number of column boxes at this level
INTEGER(KIND=JPIM) :: IBETALEN=0  ! Workspace needed at this level of interim results "beta"
TYPE(NODE_TYPE),POINTER :: NODE(:,:) => NULL() ! Box info
END TYPE LEV_STRUCT

TYPE BUTTERFLY_STRUCT
INTEGER(KIND=JPIM)  :: M_ORDER     =0 ! M of original matrix
INTEGER(KIND=JPIM)  :: N_ORDER     =0 ! N of original matrix
INTEGER(KIND=JPIM)  :: N_CMAX      =0 ! Max number of columns in each submatrix at level 0
INTEGER(KIND=JPIM)  :: N_LEVELS    =0 ! Max level in dyadic hierarchy
INTEGER(KIND=JPIM)  :: IBETALEN_MAX=0 ! Max workspace for one level of interim results "beta"
TYPE(LEV_STRUCT),POINTER :: SLEV(:) => NULL() ! Level structure (dimensioned 0:n_levels)
END TYPE BUTTERFLY_STRUCT

TYPE HYBRID_BLOCK
INTEGER(KIND=JPIM) :: KIND=HYBRID_DENSE
INTEGER(KIND=JPIM) :: FIRST_ROW=0,FIRST_COL=0,NROWS=0,NCOLS=0
INTEGER(KIND=JPIB) :: DENSE_COST=0,FACTOR_COST=0
INTEGER(KIND=JPIB) :: WORK_BASE=0
TYPE(BUTTERFLY_STRUCT) :: BUT
REAL(KIND=JPRBT),ALLOCATABLE :: DENSE(:,:)
END TYPE HYBRID_BLOCK

TYPE HYBRID_MATRIX
LOGICAL :: SELECTED=.FALSE.
LOGICAL :: CONSTRUCTED=.FALSE.
INTEGER(KIND=JPIM) :: BLOCK_COUNT=0
INTEGER(KIND=JPIM) :: DENSE_BLOCKS=0,LOW_RANK_BLOCKS=0,BUTTERFLY_BLOCKS=0
INTEGER(KIND=JPIB) :: DENSE_COST=0,HYBRID_COST=0
TYPE(HYBRID_BLOCK),ALLOCATABLE :: BLOCKS(:)
END TYPE HYBRID_MATRIX

TYPE CLONE
REAL(KIND=JPRB) , ALLOCATABLE :: COMMSBUF(:) ! for communicating packed bufferfly_structs
END TYPE CLONE                          ! between MPI tasks

CONTAINS
!================================================================================
SUBROUTINE CONSTRUCT_BUTTERFLY(PEPS,KCMAX,KM,KN,PMAT,YD_STRUCT)

! Constuct butterfly

REAL(KIND=JPRD),INTENT(IN)    :: PEPS  ! Precision
INTEGER(KIND=JPIM),INTENT(IN) :: KCMAX ! Max number of columns in each submatrix at level 0
INTEGER(KIND=JPIM),INTENT(IN) :: KM    ! Number of rows in matrix pmat
INTEGER(KIND=JPIM),INTENT(IN) :: KN    ! Number of columns in matrix pmat
REAL(KIND=JPRD),INTENT(IN)    :: PMAT(:,:)  ! original matrix
TYPE(BUTTERFLY_STRUCT),INTENT(INOUT) :: YD_STRUCT ! Structure needed to apply butterfly

REAL(KIND=JPRD),ALLOCATABLE :: ZSUB(:,:),ZBCOMB(:,:)
INTEGER(KIND=JPIM) :: ILEVELS,JL,JJ,JK,IJ,IK
INTEGER(KIND=JPIM) :: IROWS,ICOLS
INTEGER(KIND=JPIM) :: ILM1,IJL,IKL,IJR,IKR,IRANKL,IRANKR,IOFFROW,IBLEV,IBLEVM1
INTEGER(KIND=JPIM) :: IRSTRIDE,IOFFBETA
TYPE(NODE_TYPE),POINTER :: YNODEL,YNODER,YNODE 
TYPE(NODE_TYPE),POINTER :: YBNODEL,YBNODER,YBNODE 
TYPE(LEV_STRUCT) :: YTEMPB(0:1)

!--------------------------------------------------------------------------------


! ONWR 5.4.1
YD_STRUCT%M_ORDER = KM
YD_STRUCT%N_ORDER = KN
YD_STRUCT%N_CMAX  = KCMAX

!Find number of levels
ILEVELS = 0
DO
  IF(2**ILEVELS >= (YD_STRUCT%N_ORDER+YD_STRUCT%N_CMAX-1) /YD_STRUCT%N_CMAX ) EXIT
  ILEVELS = ILEVELS+1
ENDDO
YD_STRUCT%N_LEVELS = ILEVELS
ALLOCATE(YD_STRUCT%SLEV(0:YD_STRUCT%N_LEVELS))

! Number of boxes at each level
IJ = 1
IK = (KN-1)/KCMAX+1
DO JL=0,YD_STRUCT%N_LEVELS
  YD_STRUCT%SLEV(JL)%IJ = IJ
  YD_STRUCT%SLEV(JL)%IK = IK
  IJ = IJ*2
  IK = MAX((IK+1)/2,1)
ENDDO

DO JL=0,YD_STRUCT%N_LEVELS
  ALLOCATE(YD_STRUCT%SLEV(JL)%NODE(YD_STRUCT%SLEV(JL)%IJ,YD_STRUCT%SLEV(JL)%IK))
  CALL GSTATS(1253,0)
  !$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(JJ,JK,YNODE,ILM1,IJL,IKL,IJR,IKR,IRSTRIDE)
  DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
    DO JK=1,YD_STRUCT%SLEV(JL)%IK
      YNODE => YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
      YNODE%ILEV = JL
      IF(JL == 0) THEN
        YNODE%IFCOL = 1+(JK-1)*KCMAX
        YNODE%ILCOL = MIN(JK*KCMAX,KN)
        YNODE%ICOLS = YNODE%ILCOL - YNODE%IFCOL+1
        YNODE%IFROW = 1
        YNODE%ILROW = KM
      ELSE
        YNODE%IFCOL = -99
        YNODE%ILCOL = -99
        YNODE%ICOLS = -99
        ILM1 = JL-1
        IJL  = (JJ+1)/2
        IKL  = 2*JK-1
        IJR  = (JJ+1)/2
        IKR  = 2*JK
        IRSTRIDE = (YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IROWS+1)/2
        IF(MOD(JJ,2) == 1) THEN
          YNODE%IFROW = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IFROW
          YNODE%ILROW = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IFROW+IRSTRIDE -1
        ELSE
          YNODE%IFROW = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IFROW+IRSTRIDE
          YNODE%ILROW = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%ILROW
        ENDIF
      ENDIF
      YNODE%IROWS = YNODE%ILROW - YNODE%IFROW+1
      YNODE%IROWS = MAX(YNODE%IROWS,0)
    ENDDO
  ENDDO
  !$OMP END PARALLEL DO
  CALL GSTATS(1253,1)
ENDDO


! ONWR 5.4.2

DO JL=0,YD_STRUCT%N_LEVELS
  IBLEV = MOD(JL,2)
  IF(JL > 0) THEN
    IBLEVM1 = MOD(JL-1,2)
  ELSE
    IBLEVM1 = -1
  ENDIF
  ALLOCATE(YTEMPB(IBLEV)%NODE(YD_STRUCT%SLEV(JL)%IJ,YD_STRUCT%SLEV(JL)%IK))
  CALL GSTATS(1253,0)
  !$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(JJ,JK,YNODE,YBNODE,IROWS,ICOLS,&
  !$OMP& ZSUB,ILM1,IJL,IKL,IJR,IKR,YNODEL,YBNODEL,IRANKL,YNODER,YBNODER,IRANKR,IOFFROW,ZBCOMB)
  DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
    DO JK=1,YD_STRUCT%SLEV(JL)%IK
      YNODE => YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
      YBNODE => YTEMPB(IBLEV)%NODE(JJ,JK)
      IF(JL == 0) THEN
        IROWS=YNODE%IROWS
        ICOLS=YNODE%ICOLS
        ALLOCATE(ZSUB(IROWS,ICOLS))
        CALL EXTRACT_SUB(YNODE,PMAT,ZSUB)
        CALL COMPRESS_MAT(YNODE,YBNODE,PEPS,IROWS,ICOLS,ZSUB)
        DEALLOCATE(ZSUB)
      ELSE
        ILM1 = JL-1
        IJL  = (JJ+1)/2
        IKL  = 2*JK-1
        IJR  = (JJ+1)/2
        IKR  = 2*JK
        YNODEL => YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)
        YBNODEL =>  YTEMPB(IBLEVM1)%NODE(IJL,IKL)
        IRANKL = YNODEL%IRANK
        IF(IKR <= YD_STRUCT%SLEV(ILM1)%IK) THEN
          YNODER => YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)
          YBNODER =>  YTEMPB(IBLEVM1)%NODE(IJR,IKR)
          IRANKR = YNODER%IRANK
        ELSE
          YNODER => YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)
          IRANKR = 0
        ENDIF
        IROWS  = YNODE%IROWS
        ICOLS  = IRANKL+IRANKR
        YNODE%ICOLS=ICOLS
        IOFFROW = YNODE%IFROW-&
         & YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IFROW
        ALLOCATE(ZBCOMB(IROWS,ICOLS))
        CALL COMBINE_B(YBNODEL%DB,IRANKL,&
         &             YBNODER%DB,IRANKR,&
         &             IROWS,IOFFROW,ZBCOMB)
        CALL COMPRESS_MAT(YNODE,YBNODE,PEPS,IROWS,ICOLS,ZBCOMB)
        DEALLOCATE(ZBCOMB)
      ENDIF
    ENDDO
  ENDDO
  !$OMP END PARALLEL DO
  CALL GSTATS(1253,1)
  IF(IBLEVM1 >= 0) THEN
!Deallocate Bs no longer needed
    DO JJ=1,YD_STRUCT%SLEV(JL-1)%IJ
      DO JK=1,YD_STRUCT%SLEV(JL-1)%IK
        DEALLOCATE(YTEMPB(IBLEVM1)%NODE(JJ,JK)%DB)
      ENDDO
    ENDDO
    DEALLOCATE(YTEMPB(IBLEVM1)%NODE)
  ENDIF
! Permanently store B for last level
  IF(JL == YD_STRUCT%N_LEVELS) THEN
    DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
      DO JK=1,YD_STRUCT%SLEV(JL)%IK
        YNODE => YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
        ALLOCATE(YNODE%DB(YNODE%IROWS,YNODE%IRANK))
        YNODE%DB(:,:) = YTEMPB(IBLEV)%NODE(JJ,JK)%DB(:,:)
        DEALLOCATE(YTEMPB(IBLEV)%NODE(JJ,JK)%DB)
      ENDDO
    ENDDO
    DEALLOCATE(YTEMPB(IBLEV)%NODE)
  ENDIF
ENDDO

CALL GSTATS(1901,0)
! Compute work space 
YD_STRUCT%IBETALEN_MAX = 0
DO JL=0,YD_STRUCT%N_LEVELS
  IOFFBETA = 0
  DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
    DO JK=1,YD_STRUCT%SLEV(JL)%IK
      YNODE => YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
      IF( ASSOCIATED(YNODE%DB) ) THEN
        ALLOCATE(YNODE%B(SIZE(YNODE%DB(:,1)),SIZE(YNODE%DB(1,:))))
        YNODE%B(:,:) = YNODE%DB(:,:)
        DEALLOCATE(YNODE%DB)
      ENDIF
      YNODE%IOFFBETA = IOFFBETA
      IOFFBETA = IOFFBETA+YNODE%IRANK
    ENDDO
  ENDDO
  YD_STRUCT%SLEV(JL)%IBETALEN = IOFFBETA
  YD_STRUCT%IBETALEN_MAX = MAX(YD_STRUCT%IBETALEN_MAX,YD_STRUCT%SLEV(JL)%IBETALEN)
ENDDO

CALL GSTATS(1901,1)

RETURN

END SUBROUTINE CONSTRUCT_BUTTERFLY
!=============================================================================
SUBROUTINE PACK_BUTTERFLY_STRUCT(YD_STRUCT,YD_CLONE)

! Pack butterfly struct into array
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: YD_STRUCT ! Structure needed to apply butterfly
TYPE(CLONE), TARGET, INTENT(OUT) :: YD_CLONE            ! for communicating packed bufferfly_structs

INTEGER(KIND=JPIM) :: ILEN,I,JL,JIK,JIJ,J,J1,J2
!--------------------------------------------------------------------------------

ILEN=0
ILEN=ILEN+5
DO JL=0,YD_STRUCT%N_LEVELS
  ILEN=ILEN+3
  IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE) )THEN
    DO JIK=1,YD_STRUCT%SLEV(JL)%IK
      DO JIJ=1,YD_STRUCT%SLEV(JL)%IJ
        ILEN=ILEN+9
        ILEN=ILEN+1
        IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST) )THEN
          ILEN=ILEN+SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST)
        ENDIF
        ILEN=ILEN+1
        IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM) )THEN
          ILEN=ILEN+SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM)
        ENDIF
        ILEN=ILEN+2
        IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B) )THEN
          ILEN=ILEN+SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
ENDDO
ALLOCATE(YD_CLONE%COMMSBUF(ILEN))
I=0
YD_CLONE%COMMSBUF(I+1)=YD_STRUCT%M_ORDER
YD_CLONE%COMMSBUF(I+2)=YD_STRUCT%N_ORDER
YD_CLONE%COMMSBUF(I+3)=YD_STRUCT%N_CMAX
YD_CLONE%COMMSBUF(I+4)=YD_STRUCT%N_LEVELS
YD_CLONE%COMMSBUF(I+5)=YD_STRUCT%IBETALEN_MAX
I=I+5
DO JL=0,YD_STRUCT%N_LEVELS
  YD_CLONE%COMMSBUF(I+1)=YD_STRUCT%SLEV(JL)%IJ
  YD_CLONE%COMMSBUF(I+2)=YD_STRUCT%SLEV(JL)%IK
  YD_CLONE%COMMSBUF(I+3)=YD_STRUCT%SLEV(JL)%IBETALEN
  I=I+3
  IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE) )THEN
    DO JIK=1,YD_STRUCT%SLEV(JL)%IK
      DO JIJ=1,YD_STRUCT%SLEV(JL)%IJ
        YD_CLONE%COMMSBUF(I+1)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ILEV
        YD_CLONE%COMMSBUF(I+2)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IFCOL
        YD_CLONE%COMMSBUF(I+3)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ILCOL
        YD_CLONE%COMMSBUF(I+4)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IFROW
        YD_CLONE%COMMSBUF(I+5)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ILROW
        YD_CLONE%COMMSBUF(I+6)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICOLS
        YD_CLONE%COMMSBUF(I+7)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IROWS
        YD_CLONE%COMMSBUF(I+8)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IRANK
        YD_CLONE%COMMSBUF(I+9)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IOFFBETA
        I=I+9
        YD_CLONE%COMMSBUF(I+1)=0
        I=I+1
        IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST) )THEN
          J=SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST)
          YD_CLONE%COMMSBUF(I)=J
          YD_CLONE%COMMSBUF(I+1:I+J)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST(:)
          I=I+J
        ENDIF
        YD_CLONE%COMMSBUF(I+1)=0
        I=I+1
        IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM) )THEN
          J=SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM)
          YD_CLONE%COMMSBUF(I)=J
          YD_CLONE%COMMSBUF(I+1:I+J)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM(:)
          I=I+J
        ENDIF
        YD_CLONE%COMMSBUF(I+1)=0
        YD_CLONE%COMMSBUF(I+2)=0
        I=I+2
        IF( ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B) )THEN
          J1=SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B,DIM=1)
          J2=SIZE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B,DIM=2)
          YD_CLONE%COMMSBUF(I-1)=J1
          YD_CLONE%COMMSBUF(I  )=J2
          DO J=1,J2
            YD_CLONE%COMMSBUF(I+1:I+J1)=YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B(:,J)
            I=I+J1
          ENDDO
        ENDIF
      ENDDO
    ENDDO
  ENDIF
ENDDO
IF( I /= ILEN )THEN
  CALL ABOR1('PACK_BUTTERFLY_STRUCT: PACKED LENGTH /= PRECOMPUTED LENGTH')
ENDIF

END SUBROUTINE PACK_BUTTERFLY_STRUCT
!=====================================================================================
SUBROUTINE UNPACK_BUTTERFLY_STRUCT(YD_STRUCT,YD_CLONE,YDMEMBUF)

! Construct butterfly struct from packed array
TYPE(BUTTERFLY_STRUCT),INTENT(OUT) :: YD_STRUCT      ! Structure needed to apply butterfly
TYPE(CLONE), TARGET, OPTIONAL,INTENT(IN) :: YD_CLONE          ! for communicating packed bufferfly_structs
TYPE(SHAREDMEM),OPTIONAL,INTENT(INOUT) :: YDMEMBUF   ! Memory buffer
INTEGER(KIND=JPIM) :: I,JL,JIK,JIJ,J,J1,J2,II
REAL(KIND=JPRB),POINTER :: ZBUF(:)
LOGICAL :: LLMEMBUF
!--------------------------------------------------------------------------------
IF(PRESENT(YDMEMBUF)) THEN
  LLMEMBUF = .TRUE.
ELSE
  IF(.NOT.PRESENT(YD_CLONE))  CALL ABOR1('UNPACK_BUTTERFLY_STRUCT: YD_CLONE ARGUMENT MISSING')
  LLMEMBUF = .FALSE.
ENDIF
I=0
IF(LLMEMBUF) THEN
  CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,5,ZBUF,ADVANCE=.TRUE.)
ELSE
  ZBUF => YD_CLONE%COMMSBUF(I+1:I+5)
ENDIF
YD_STRUCT%M_ORDER      = NINT(ZBUF(1),JPIM)
YD_STRUCT%N_ORDER      = NINT(ZBUF(2),JPIM)
YD_STRUCT%N_CMAX       = NINT(ZBUF(3),JPIM)
YD_STRUCT%N_LEVELS     = NINT(ZBUF(4),JPIM)
YD_STRUCT%IBETALEN_MAX = NINT(ZBUF(5),JPIM)
I=I+5

ALLOCATE(YD_STRUCT%SLEV(0:YD_STRUCT%N_LEVELS))
DO JL=0,YD_STRUCT%N_LEVELS
  IF(LLMEMBUF) THEN
    CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,3,ZBUF,ADVANCE=.TRUE.)
  ELSE
    ZBUF => YD_CLONE%COMMSBUF(I+1:I+3)
  ENDIF
  YD_STRUCT%SLEV(JL)%IJ      =NINT(ZBUF(1),JPIM)
  YD_STRUCT%SLEV(JL)%IK      =NINT(ZBUF(2),JPIM)
  YD_STRUCT%SLEV(JL)%IBETALEN=NINT(ZBUF(3),JPIM)
  I=I+3
  ALLOCATE(YD_STRUCT%SLEV(JL)%NODE(YD_STRUCT%SLEV(JL)%IJ,YD_STRUCT%SLEV(JL)%IK))
  DO JIK=1,YD_STRUCT%SLEV(JL)%IK
    DO JIJ=1,YD_STRUCT%SLEV(JL)%IJ
      IF(LLMEMBUF) THEN
        CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,10,ZBUF,ADVANCE=.TRUE.)
      ELSE
        ZBUF => YD_CLONE%COMMSBUF(I+1:I+10)
      ENDIF
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ILEV    = NINT(ZBUF(1),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IFCOL   = NINT(ZBUF(2),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ILCOL   = NINT(ZBUF(3),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IFROW   = NINT(ZBUF(4),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ILROW   = NINT(ZBUF(5),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICOLS   = NINT(ZBUF(6),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IROWS   = NINT(ZBUF(7),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IRANK   = NINT(ZBUF(8),JPIM)
      YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%IOFFBETA= NINT(ZBUF(9),JPIM)
      J = NINT(ZBUF(10))
      I=I+10
      ALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST(J))
      IF( J > 0 )THEN
        IF(LLMEMBUF) THEN
          CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,J,ZBUF,ADVANCE=.TRUE.)
        ELSE
          ZBUF => YD_CLONE%COMMSBUF(I+1:I+J)
        ENDIF
        DO II=1,J
           YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%ICLIST(II)=NINT(ZBUF(II),JPIM)
        END DO
        I=I+J
      ENDIF
      IF(LLMEMBUF) THEN
        CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,1,ZBUF,ADVANCE=.TRUE.)
      ELSE
        ZBUF => YD_CLONE%COMMSBUF(I+1:I+1)
      ENDIF
      J=NINT(ZBUF(1),JPIM)
      I=I+1
      IF( J > 0 )THEN
        IF(LLMEMBUF) THEN
          CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,J,YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM,ADVANCE=.TRUE.)
        ELSE
          ALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM(J))
          YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%PNONIM(:)=YD_CLONE%COMMSBUF(I+1:I+J)
        ENDIF
        I=I+J
      ENDIF
      IF(LLMEMBUF) THEN
        CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,2,ZBUF,ADVANCE=.TRUE.)
      ELSE
        ZBUF => YD_CLONE%COMMSBUF(I+1:I+2)
      ENDIF
      J1=NINT(ZBUF(1),JPIM)
      J2=NINT(ZBUF(2),JPIM)
      I=I+2
      IF( J1 > 0 .AND. J2 > 0 )THEN
        IF(LLMEMBUF) THEN
          CALL SHAREDMEM_ASSOCIATE(YDMEMBUF,J1,J2,YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B,ADVANCE=.TRUE.)
          I=I+J1*J2
        ELSE
          ALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B(J1,J2))
          DO J=1,J2
            YD_STRUCT%SLEV(JL)%NODE(JIJ,JIK)%B(:,J)=YD_CLONE%COMMSBUF(I+1:I+J1)
            I=I+J1
          ENDDO
        ENDIF
      ENDIF
    ENDDO
  ENDDO
ENDDO
IF(.NOT.LLMEMBUF) THEN
  IF( I /= SIZE(YD_CLONE%COMMSBUF) )THEN
    CALL ABOR1('UNPACK_BUTTERFLY_STRUCT: UNPACKED LENGTH /= ALLOCATED LENGTH')
  ENDIF
ENDIF
END SUBROUTINE UNPACK_BUTTERFLY_STRUCT
!===========================================================================
SUBROUTINE EXTRACT_SUB(YDNODE,PMAT,PSUB)

TYPE(NODE_TYPE),INTENT(IN) :: YDNODE
REAL(KIND=JPRD),INTENT(IN) :: PMAT(:,:)
REAL(KIND=JPRD),INTENT(OUT) :: PSUB(:,:)

INTEGER(KIND=JPIM) :: ICOL,IROW,JCOL,JROW
!--------------------------------------------------------------------

ICOL = 0
DO JCOL=YDNODE%IFCOL,YDNODE%ILCOL
  ICOL = ICOL+1
  IROW = 0
  DO JROW=YDNODE%IFROW,YDNODE%ILROW
    IROW = IROW+1
    PSUB(IROW,ICOL) = PMAT(JROW,JCOL)
  ENDDO
ENDDO

END SUBROUTINE EXTRACT_SUB
!===================================================================
SUBROUTINE COMBINE_B(PBL,KRANKL,PBR,KRANKR,KROWS,KOFFROW,PBCOMB)

REAL(KIND=JPRD),INTENT(IN) :: PBL(:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KRANKL
REAL(KIND=JPRD),INTENT(IN) :: PBR(:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KRANKR
INTEGER(KIND=JPIM),INTENT(IN) :: KROWS
INTEGER(KIND=JPIM),INTENT(IN) :: KOFFROW
REAL(KIND=JPRD),INTENT(OUT) :: PBCOMB(:,:)

INTEGER(KIND=JPIM) :: JCOL,JM
!--------------------------------------------------------------------
DO JCOL=1,KRANKL
  DO JM=1,KROWS
   PBCOMB(JM,JCOL) = PBL(KOFFROW+JM,JCOL)
 ENDDO
ENDDO
DO JCOL=1,KRANKR
  DO JM=1,KROWS
    PBCOMB(JM,KRANKL+JCOL) = PBR(KOFFROW+JM,JCOL) 
  ENDDO
ENDDO

END SUBROUTINE COMBINE_B
!===================================================================
SUBROUTINE COMPRESS_MAT(YDNODE,YDBNODE,PEPS,KROWS,KCOLS,PSUB)

TYPE(NODE_TYPE),INTENT(INOUT) :: YDNODE
TYPE(NODE_TYPE),INTENT(INOUT) :: YDBNODE
REAL(KIND=JPRD),INTENT(IN)    :: PEPS
INTEGER(KIND=JPIM),INTENT(IN) :: KROWS,KCOLS
REAL(KIND=JPRD),INTENT(IN)    :: PSUB(:,:)

INTEGER(KIND=JPIM) :: JR,IRANK,ICLIST(KCOLS),JN,JM,II
REAL(KIND=JPRD) :: ZSUB(KROWS,KCOLS),ZPNONIM(KROWS,KCOLS)
!--------------------------------------------------------------------

II = 0
DO JN=1,KCOLS
  DO JM=1,KROWS
    II = II+1
    ZSUB(JM,JN) = PSUB(JM,JN)
  ENDDO
ENDDO

CALL COMPUTE_ID(PEPS,KROWS,KCOLS,ZSUB,IRANK,ICLIST,ZPNONIM)
YDNODE%IRANK = IRANK
ALLOCATE(YDNODE%PNONIM(IRANK*(KCOLS-IRANK)))
ALLOCATE(YDNODE%ICLIST(KCOLS))
ALLOCATE(YDBNODE%DB(KROWS,IRANK))
YDNODE%ICLIST(:) = ICLIST(1:KCOLS)
II = 0
DO JN=1,KCOLS-IRANK
  DO JM=1,IRANK
    II = II+1
    YDNODE%PNONIM(II) = REAL(ZPNONIM(JM,JN), JPRB)
  ENDDO
ENDDO
DO JR=1,IRANK
  YDBNODE%DB(:,JR) = PSUB(:,ICLIST(JR))
ENDDO

END SUBROUTINE COMPRESS_MAT
!====================================================================
SUBROUTINE MULT_BUTV(CDTRANS,YD_STRUCT,PVECIN,PVECOUT)

! Multiply vector by matrix represented by buttervfly

TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: YD_STRUCT ! Structure from constucT-butterfly
CHARACTER(LEN=1),INTENT(IN)   :: CDTRANS       ! 'N' normal matmul, 'T' with transpose of matrix
REAL(KIND=JPRB),INTENT(IN)    :: PVECIN(:)     ! Input vector
REAL(KIND=JPRB),INTENT(OUT)   :: PVECOUT(:)    ! Output vector

REAL(KIND=JPRB),ALLOCATABLE   :: ZBETA(:,:)
INTEGER(KIND=JPIM) :: JL,JJ,JK,ILEVS,IFR,ILR,IROWS
INTEGER(KIND=JPIM) :: ILM1,IJL,IKL,IJR,IKR,IRANKL,IRANKR
INTEGER(KIND=JPIM) :: IBETALV,IBTST,IBTEN,IBETALVM1,IBTSTL,IBTENL,IBTSTR,IBTENR
REAL(KIND=JPRB) :: ZVECOUT(SIZE(PVECOUT))
LOGICAL :: LLTRANSPOSE
TYPE(NODE_TYPE),POINTER :: YNODE 
!----------------------------------------------------------------------------------
LLTRANSPOSE = (CDTRANS == 'T' .OR. CDTRANS == 't') 

ILEVS = YD_STRUCT%N_LEVELS
ALLOCATE(ZBETA(YD_STRUCT%IBETALEN_MAX,0:1)) ! Work space for "beta"

! ONWR 5.4.3
IF(LLTRANSPOSE) THEN
  DO JL=ILEVS,0,-1
    IBETALV = MOD(JL,2)
    DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
      DO JK=1,YD_STRUCT%SLEV(JL)%IK
        YNODE =>  YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
        IBTST = YNODE%IOFFBETA+1
        IBTEN = YNODE%IOFFBETA+YNODE%IRANK
        IF(JL == 0) THEN
          IFR = YNODE%IFCOL
          ILR = YNODE%ILCOL
          CALL MULT_P_TR(YNODE,ZBETA(IBTST:IBTEN,IBETALV),PVECOUT(IFR:ILR))
        ELSE
          IF(JL == ILEVS) THEN
            IFR = YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%IFROW
            ILR = YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%ILROW
            IROWS=YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%IROWS
            CALL GEMV('T',IROWS,YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%IRANK,&
               & 1.0_JPRB,YNODE%B,IROWS,PVECIN(IFR:ILR),1,&
               & 0.0_JPRB,ZBETA(IBTST:IBTEN,IBETALV),1)
          ENDIF
          ILM1 = JL-1
          IBETALVM1=MOD(ILM1,2)
          IJL  = (JJ+1)/2
          IKL  = 2*JK-1
          IJR  = (JJ+1)/2
          IKR  = 2*JK
          IRANKL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IRANK
          IF(IKR <= YD_STRUCT%SLEV(ILM1)%IK) THEN
            IRANKR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IRANK
          ELSE
            IRANKR = 0
          ENDIF
          IBTSTL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+1
          IBTENL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+IRANKL
          IBTSTR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+1
          IBTENR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+IRANKR
          CALL MULT_P_TR(YNODE,ZBETA(IBTST:IBTEN,IBETALV),ZVECOUT(1:IRANKL+IRANKR))  
          IF(MOD(JJ,2) == 1) THEN
            ZBETA(IBTSTL:IBTENL,IBETALVM1)= ZVECOUT(1:IRANKL)
            IF(IRANKR > 0) THEN
              ZBETA(IBTSTR:IBTENR,IBETALVM1)=ZVECOUT(IRANKL+1:IRANKL+IRANKR)
            ENDIF
          ELSE
            ZBETA(IBTSTL:IBTENL,IBETALVM1)=ZBETA(IBTSTL:IBTENL,IBETALVM1)+ &
             & ZVECOUT(1:IRANKL)
            IF(IRANKR > 0) THEN
              ZBETA(IBTSTR:IBTENR,IBETALVM1)=ZBETA(IBTSTR:IBTENR,IBETALVM1) + &
               &  ZVECOUT(IRANKL+1:IRANKL+IRANKR)
            ENDIF
          ENDIF
        ENDIF
      ENDDO
    ENDDO
  ENDDO
ELSE
  DO JL=0,ILEVS
    IBETALV = MOD(JL,2)
    DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
      DO JK=1,YD_STRUCT%SLEV(JL)%IK
        YNODE =>  YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
        IBTST = YNODE%IOFFBETA+1
        IBTEN = YNODE%IOFFBETA+YNODE%IRANK
        IF(JL == 0) THEN    ! ONWR (115)
          IFR = YNODE%IFCOL
          ILR = YNODE%ILCOL
          CALL MULT_P(YNODE,PVECIN(IFR:ILR),ZBETA(IBTST:IBTEN,IBETALV) )     
        ELSE                ! ONWR (116)
          ILM1 = JL-1
          IBETALVM1=MOD(ILM1,2)
          IJL  = (JJ+1)/2
          IKL  = 2*JK-1
          IJR  = (JJ+1)/2
          IKR  = 2*JK
          IRANKL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IRANK
          IF(IKR <= YD_STRUCT%SLEV(ILM1)%IK) THEN
            IRANKR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IRANK
          ELSE
            IRANKR = 0
          ENDIF
          IBTSTL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+1
          IBTENL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+IRANKL
          IBTSTR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+1
          IBTENR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+IRANKR
          CALL MULT_P(YNODE,ZBETA(IBTSTL:IBTENR,IBETALVM1),ZBETA(IBTST:IBTEN,IBETALV))     
        ENDIF
        IF(JL == ILEVS) THEN ! ONWR (117)
          IFR = YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%IFROW
          ILR = YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%ILROW
          IROWS = YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%IROWS
          CALL GEMV('N',IROWS,YD_STRUCT%SLEV(ILEVS)%NODE(JJ,JK)%IRANK,&
             & 1.0_JPRB,YNODE%B,IROWS,ZBETA(IBTST:IBTEN,IBETALV),1,&
             & 0.0_JPRB,PVECOUT(IFR:ILR),1)
        ENDIF
      ENDDO
    ENDDO
  ENDDO
ENDIF
END SUBROUTINE MULT_BUTV
!====================================================================
SUBROUTINE MULT_BUTM(CDTRANS,YD_STRUCT,KF,PVECIN,PVECOUT,KWV)

! Multiply matrix by matrix represented by butterfly

CHARACTER(LEN=1),INTENT(IN)   :: CDTRANS       ! 'N' normal matmul, 'T' with transpose of matrix
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: YD_STRUCT ! Structure from constucT-butterfly
INTEGER(KIND=JPIM),INTENT(IN) :: KF            ! Number of fields
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KWV           ! zonal wave number m (special_case)
REAL(KIND=JPRB),INTENT(IN)    :: PVECIN(:,:)     ! Input vector
REAL(KIND=JPRB),INTENT(OUT)   :: PVECOUT(:,:)    ! Output vector

INTEGER(KIND=JPIM) :: JL,JJ,JK,ILEVS,IFR,ILR,IROWS,JF
INTEGER(KIND=JPIM) :: ILM1,IJL,IKL,IJR,IKR,IRANKL,IRANKR,IROUT,IRIN
INTEGER(KIND=JPIM) :: IRANK,IM,IN,JN,JM,IDX,IKWV,II
INTEGER(KIND=JPIM) :: IBETALV,IBTST,IBTEN,IBETALVM1,IBTSTL,IBTENL,IBTSTR,IBTENR,ILBETA
REAL(KIND=JPRB) :: ZVECIN(YD_STRUCT%N_ORDER,KF),ZVECOUT(YD_STRUCT%N_ORDER,KF)
REAL(KIND=JPRB),ALLOCATABLE   :: ZBETA(:,:,:)
LOGICAL :: LLTRANSPOSE

! IKWV==0 only, LLTRANSPOSE = true only
REAL(KIND=JPRD),ALLOCATABLE   :: ZPNONIM_D(:,:)
REAL(KIND=JPRD),ALLOCATABLE   :: ZBETA_D(:,:), ZB_D(:,:)
REAL(KIND=JPRD),ALLOCATABLE   :: ZOUT_D(:,:), ZIN_D(:,:)

TYPE(NODE_TYPE),POINTER :: YNODE 

IKWV=10
IF( PRESENT(KWV) ) THEN
  IKWV=KWV
ENDIF

!----------------------------------------------------------------------------------
LLTRANSPOSE = (CDTRANS == 'T' .OR. CDTRANS == 't') 
IROUT=SIZE(PVECOUT(:,1))
IRIN=SIZE(PVECIN(:,1))

ILEVS = YD_STRUCT%N_LEVELS
ILBETA = YD_STRUCT%IBETALEN_MAX
ALLOCATE(ZBETA(ILBETA,KF,0:1)) ! Work space for "beta"

! ONWR 5.4.3
IF (LLTRANSPOSE) THEN
  IF (IKWV == 0  .AND. JPRB /= JPRD) THEN
    ALLOCATE(ZBETA_D(ILBETA,KF))
    ALLOCATE(ZOUT_D(YD_STRUCT%N_ORDER,KF))
    ALLOCATE(ZIN_D(IRIN,KF))
  ENDIF

  DO JL=ILEVS,0,-1
    IBETALV = MOD(JL,2)
    DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
      DO JK=1,YD_STRUCT%SLEV(JL)%IK
        YNODE =>  YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
        IBTST = YNODE%IOFFBETA+1
        IBTEN = YNODE%IOFFBETA+YNODE%IRANK
        IF(JL == 0) THEN
          IFR = YNODE%IFCOL
          ILR = YNODE%ILCOL
          IN = YNODE%ICOLS-YNODE%IRANK
          IM = YNODE%IRANK
          IF( IM <=0 )  CALL ABOR1('mult_butm: IM<=0 not allowed')
          IF(IN>0) THEN
            ! Force GEMMs for the zeroth wavenumber to be double precision
            IF (IKWV == 0 .AND. JPRB /= JPRD) THEN
              ALLOCATE(ZPNONIM_D(IM,IN))
              II = 0
              DO JN = 1, IN
                  DO JM = 1, IM
                    II = II + 1
                    ZPNONIM_D(JM,JN) = REAL(YNODE%PNONIM(II),JPRD)
                  ENDDO
              ENDDO
              ZBETA_D(1:IM,1:KF) = REAL(ZBETA(IBTST:IBTST+IM-1,1:KF,IBETALV),JPRD)
              CALL GEMM('T', 'N', &
                &       IN, KF, IM, &
                &       1.0_JPRD, &
                &       ZPNONIM_D(1,1), IM, &
                &       ZBETA_D(1,1), ILBETA, &
                &       0.0_JPRD, &
                &       ZOUT_D(1,1), YD_STRUCT%N_ORDER)
              ZVECOUT(YNODE%IRANK+1:YNODE%IRANK+IN,1:KF) = REAL(ZOUT_D(1:IN,1:KF),JPRB)
              DEALLOCATE(ZPNONIM_D)
            ELSE
              CALL GEMM('T', 'N', &
                &       IN, KF, IM, &
                &       1.0_JPRB, &
                &       YNODE%PNONIM(1), IM, &
                &       ZBETA(IBTST,1,IBETALV), ILBETA, &
                &       0.0_JPRB, &
                &       ZVECOUT(YNODE%IRANK+1,1), YD_STRUCT%N_ORDER)
            ENDIF
          ENDIF
          DO JF=1,KF
            DO JN=1,YNODE%IRANK
              IDX = YNODE%ICLIST(JN)
              PVECOUT(IFR+IDX-1,JF) = ZBETA(IBTST+JN-1,JF,IBETALV)
            ENDDO
            DO JN=YNODE%IRANK+1,YNODE%ICOLS
              IDX = YNODE%ICLIST(JN)
              PVECOUT(IFR+IDX-1,JF) = ZVECOUT(JN,JF)
            ENDDO
          ENDDO
        ELSE
          IF(JL == ILEVS) THEN
            IFR = YNODE%IFROW
            ILR = YNODE%ILROW
            IROWS =YNODE%IROWS
            IRANK = YNODE%IRANK
            ! Force GEMMs for the zeroth wavenumber to be double precision
            IF (IKWV == 0 .AND. JPRB /= JPRD) THEN
              ALLOCATE(ZB_D(IROWS,IRANK))
              ZB_D(1:IROWS,1:IRANK) = REAL(YNODE%B(1:IROWS,1:IRANK),JPRD)
              ZIN_D(1:ILR-IFR+1,1:KF) = REAL(PVECIN(IFR:ILR,1:KF),JPRD)
              CALL GEMM('T', 'N', &
                &       IRANK, KF, IROWS, &
                &       1.0_JPRD, &
                &       ZB_D, IROWS, &
                &       ZIN_D, IRIN, &
                &       0.0_JPRD, &
                &       ZBETA_D, ILBETA)
              ZBETA(IBTST:IBTST+IRANK-1,1:KF,IBETALV) = REAL(ZBETA_D(1:IRANK,1:KF),JPRM)
              DEALLOCATE(ZB_D)
            ELSE
              CALL GEMM('T', 'N', &
                &       IRANK, KF, IROWS, &
                &       1.0_JPRB, &
                &       YNODE%B(1,1), IROWS, &
                &       PVECIN(IFR,1), IRIN, &
                &       0.0_JPRB, &
                &       ZBETA(IBTST,1,IBETALV), ILBETA)
            END IF
          ENDIF
          ILM1 = JL-1
          IBETALVM1=MOD(ILM1,2)
          IJL  = (JJ+1)/2
          IKL  = 2*JK-1
          IJR  = (JJ+1)/2
          IKR  = 2*JK
          IRANKL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IRANK
          IBTSTL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+1
          IBTENL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+IRANKL
          IF(IKR <= YD_STRUCT%SLEV(ILM1)%IK) THEN
            IRANKR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IRANK
            IBTSTR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+1
            IBTENR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+IRANKR
          ELSE
            IRANKR = 0
          ENDIF
          IN = YNODE%ICOLS-YNODE%IRANK
          IM = YNODE%IRANK
          IF( IM <=0 )  CALL ABOR1('mult_butm: IM<=0 not allowed')
          IF(IN>0) THEN
            ! Force GEMMs for the zeroth wavenumber to be double precision
            IF (IKWV == 0 .AND. JPRB /= JPRD) THEN
              ALLOCATE(ZPNONIM_D(IM,IN))
              II = 0
              DO JN = 1, IN
                DO JM = 1, IM
                    II = II + 1
                    ZPNONIM_D(JM,JN) = REAL(YNODE%PNONIM(II),JPRD)
                ENDDO
              ENDDO
              ZBETA_D(1:IM,1:KF) = REAL(ZBETA(IBTST:IBTST+IM-1,1:KF,IBETALV),JPRD)
              CALL GEMM('T', 'N', &
                &       IN, KF, IM, &
                &       1.0_JPRD, &
                &       ZPNONIM_D, IM, &
                &       ZBETA_D, ILBETA, &
                &       0.0_JPRD,&
                &       ZOUT_D, YD_STRUCT%N_ORDER)
              ZVECOUT(YNODE%IRANK+1:YNODE%IRANK+IN,1:KF) = REAL(ZOUT_D(1:IN,1:KF),JPRM)
              DEALLOCATE(ZPNONIM_D)
            ELSE
              CALL GEMM('T', 'N', &
                &       IN, KF, IM, &
                &       1.0_JPRB, &
                &       YNODE%PNONIM(1), IM, &
                &       ZBETA(IBTST,1,IBETALV), ILBETA, &
                &       0.0_JPRB, &
                &       ZVECOUT(YNODE%IRANK+1,1), YD_STRUCT%N_ORDER)
            ENDIF
          ENDIF
          DO JF=1,KF
            DO JN=1,YNODE%IRANK
              IDX = YNODE%ICLIST(JN)
              ZVECIN(IDX,JF) = ZBETA(IBTST+JN-1,JF,IBETALV)
            ENDDO
            DO JN=YNODE%IRANK+1,YNODE%ICOLS
              IDX = YNODE%ICLIST(JN)
              ZVECIN(IDX,JF) = ZVECOUT(JN,JF)
            ENDDO
          ENDDO
          
          DO JF=1,KF
            IF(MOD(JJ,2) == 1) THEN
              ZBETA(IBTSTL:IBTENL,JF,IBETALVM1)= ZVECIN(1:IRANKL,JF)
              IF(IRANKR > 0) THEN
                ZBETA(IBTSTR:IBTENR,JF,IBETALVM1)=ZVECIN(IRANKL+1:IRANKL+IRANKR,JF)
              ENDIF
            ELSE
              ZBETA(IBTSTL:IBTENL,JF,IBETALVM1)=ZBETA(IBTSTL:IBTENL,JF,IBETALVM1)+ &
               & ZVECIN(1:IRANKL,JF)
              IF(IRANKR > 0) THEN
                ZBETA(IBTSTR:IBTENR,JF,IBETALVM1)=ZBETA(IBTSTR:IBTENR,JF,IBETALVM1) + &
                 &  ZVECIN(IRANKL+1:IRANKL+IRANKR,JF)
              ENDIF
            ENDIF
          ENDDO
        ENDIF
      ENDDO
    ENDDO
  ENDDO

  IF (IKWV == 0 .AND. JPRB /= JPRD) THEN
    DEALLOCATE(ZBETA_D)
    DEALLOCATE(ZOUT_D)
    DEALLOCATE(ZIN_D)
  ENDIF

ELSE
  DO JL=0,ILEVS
    IBETALV = MOD(JL,2)
    DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
      DO JK=1,YD_STRUCT%SLEV(JL)%IK
        YNODE =>  YD_STRUCT%SLEV(JL)%NODE(JJ,JK)
        IBTST = YNODE%IOFFBETA+1
        IBTEN = YNODE%IOFFBETA+YNODE%IRANK
        IF(JL == 0) THEN
          IFR = YNODE%IFCOL
          ILR = YNODE%ILCOL
          IRANK = YNODE%IRANK
          IM = IRANK
          IN = YNODE%ICOLS-IRANK
          DO JF=1,KF
            DO JN=1,YNODE%ICOLS
              IDX = YNODE%ICLIST(JN)
              IF(JN <= IRANK) THEN
                ZBETA(IBTST+JN-1,JF,IBETALV) = PVECIN(IFR+IDX-1,JF)
              ELSE
                ZVECIN(JN,JF) = PVECIN(IFR+IDX-1,JF)
              ENDIF
            ENDDO
          ENDDO
          IF( IRANK <=0 )  CALL ABOR1('mult_butm: IRANK<=0 not allowed')
          IF(YNODE%ICOLS > IRANK) THEN
            CALL GEMM('N','N',IRANK,KF,IN,1.0_JPRB,&
               & YNODE%PNONIM(1),IRANK,ZVECIN(IRANK+1,1),YD_STRUCT%N_ORDER,1.0_JPRB,&
               & ZBETA(IBTST,1,IBETALV),ILBETA)
          ENDIF
        ELSE
          ILM1 = JL-1
          IBETALVM1=MOD(ILM1,2)
          IJL  = (JJ+1)/2
          IKL  = 2*JK-1
          IJR  = (JJ+1)/2
          IKR  = 2*JK
          IRANKL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IRANK
          IBTSTL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+1
          IBTENL = YD_STRUCT%SLEV(ILM1)%NODE(IJL,IKL)%IOFFBETA+IRANKL
          IF(IKR <= YD_STRUCT%SLEV(ILM1)%IK) THEN
            IRANKR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IRANK
            IBTSTR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+1
            IBTENR = YD_STRUCT%SLEV(ILM1)%NODE(IJR,IKR)%IOFFBETA+IRANKR
          ELSE
            IRANKR = 0
            IBTENR = IBTENL 
          ENDIF
          IRANK = YNODE%IRANK
          IM = IRANK
          IN = YNODE%ICOLS-IRANK
          DO JF=1,KF
            DO JN=1,YNODE%ICOLS
              IDX = YNODE%ICLIST(JN)
              IF(JN <= IRANK) THEN
                ZBETA(IBTST+JN-1,JF,IBETALV) = ZBETA(IBTSTL+IDX-1,JF,IBETALVM1)
              ELSE
                ZVECIN(JN,JF) = ZBETA(IBTSTL+IDX-1,JF,IBETALVM1)
              ENDIF
            ENDDO
          ENDDO
          IF( IRANK <=0 )  CALL ABOR1('mult_butm: IRANK<=0 not allowed')
          IF(YNODE%ICOLS > IRANK) THEN
            CALL GEMM('N','N',IRANK,KF,IN,1.0_JPRB,&
               & YNODE%PNONIM(1),IRANK,ZVECIN(IRANK+1,1),YD_STRUCT%N_ORDER,1.0_JPRB,&
               & ZBETA(IBTST,1,IBETALV),ILBETA)
          ENDIF
        ENDIF
        IF( IRANK <=0 )  CALL ABOR1('mult_butm: IRANK<=0 not allowed')
        IF(JL == ILEVS) THEN
          IFR = YNODE%IFROW
          ILR = YNODE%ILROW
          IROWS = YNODE%IROWS
          CALL GEMM('N','N',IROWS,KF,YNODE%IRANK,1.0_JPRB,&
             & YNODE%B(1,1),IROWS,ZBETA(IBTST,1,IBETALV),YD_STRUCT%IBETALEN_MAX,0.0_JPRB,&
             & PVECOUT(IFR,1),IROUT)
        ENDIF
      ENDDO
    ENDDO
  ENDDO
ENDIF
DEALLOCATE(ZBETA)
END SUBROUTINE MULT_BUTM
!=====================================================================
SUBROUTINE MULT_P(YDNODE,PVECIN,PVECOUT)
! Multiply vector by projection matrix
TYPE(NODE_TYPE),INTENT(INOUT) :: YDNODE
REAL(KIND=JPRB),INTENT(IN)    :: PVECIN(:)
REAL(KIND=JPRB),INTENT(OUT)   :: PVECOUT(:)

REAL(KIND=JPRB) :: ZVECIN(YDNODE%ICOLS)
INTEGER(KIND=JPIM) :: JN, IDX, IRANK, IM, IN
!---------------------------------------------------------

IRANK = YDNODE%IRANK
DO JN = 1, YDNODE%ICOLS
  IDX = YDNODE%ICLIST(JN)
  IF (JN <= IRANK) THEN
    PVECOUT(JN) = PVECIN(IDX)
  ELSE
    ZVECIN(JN) = PVECIN(IDX)
  ENDIF
ENDDO

IF (YDNODE%ICOLS > IRANK) THEN
  IM = IRANK
  IN = YDNODE%ICOLS-IRANK
  CALL GEMV('N', &
    &       IM, IN, &
    &       1.0_JPRB, &
    &       YDNODE%PNONIM(1), IRANK, &
    &       ZVECIN(IRANK+1), 1, &
    &       1.0_JPRB, &
    &       PVECOUT(1), 1)
ENDIF

END SUBROUTINE MULT_P
!=====================================================================
SUBROUTINE MULT_PM(YDNODE,KF,KLBETA,PVECIN,PVECOUT)
! Multiply matrix by projection matrix
TYPE(NODE_TYPE),INTENT(INOUT) :: YDNODE
INTEGER(KIND=JPIM),INTENT(IN) :: KF 
INTEGER(KIND=JPIM),INTENT(IN) :: KLBETA
REAL(KIND=JPRB),INTENT(IN)    :: PVECIN(:,:)
REAL(KIND=JPRB),INTENT(OUT)   :: PVECOUT(:,:)

REAL(KIND=JPRB) :: ZVECIN(YDNODE%ICOLS,KF), ZVECOUT(SIZE(PVECOUT(:,1)),KF)
INTEGER(KIND=JPIM) :: JN,IDX,IRANK,IM,IN,JF

!---------------------------------------------------------

IRANK = YDNODE%IRANK
IM = IRANK
IN = YDNODE%ICOLS-IRANK
DO JF=1,KF
  DO JN=1,YDNODE%ICOLS
    IDX = YDNODE%ICLIST(JN)
    IF(JN <= IRANK) THEN
      ZVECOUT(JN,JF) = PVECIN(IDX,JF)
    ELSE
      ZVECIN(JN,JF) = PVECIN(IDX,JF)
    ENDIF
  ENDDO
ENDDO
IF (YDNODE%ICOLS > IRANK) THEN
  CALL GEMM('N','N',IRANK,KF,IN,1.0_JPRB,&
     & YDNODE%PNONIM(1),IRANK,ZVECIN(IRANK+1,1),YDNODE%ICOLS,1.0_JPRB,&
     & PVECOUT(1,1),IRANK)
ENDIF
END SUBROUTINE MULT_PM
!==================================================================
SUBROUTINE MULT_P_TR(YDNODE, PVECIN, PVECOUT)
! Multiply vector by transposed procetion matrix
TYPE(NODE_TYPE),INTENT(INOUT) :: YDNODE
REAL(KIND=JPRB),INTENT(IN)    :: PVECIN(:)
REAL(KIND=JPRB),INTENT(OUT)   :: PVECOUT(:)

REAL(KIND=JPRB) :: ZVECOUT(YDNODE%ICOLS)
INTEGER(KIND=JPIM) :: JK, JN, IDX, IRANK, IM, IN
!---------------------------------------------------------

IRANK = YDNODE%IRANK
IN = YDNODE%ICOLS-IRANK
IF (IN > 0) THEN
  IM = IRANK
  CALL GEMV('T', &
    &       IM, IN,&
    &       1.0_JPRB, &
    &       YDNODE%PNONIM(1), IRANK, &
    &       PVECIN(1), 1, &
    &       0.0_JPRB, &
    &       ZVECOUT(IRANK+1), 1)
ENDIF
DO JK = 1, IRANK
   IDX = YDNODE%ICLIST(JK)
   PVECOUT(IDX) = PVECIN(JK)
ENDDO
DO JN = IRANK + 1,YDNODE%ICOLS
  IDX = YDNODE%ICLIST(JN)
  PVECOUT(IDX) = ZVECOUT(JN)
ENDDO

END SUBROUTINE MULT_P_TR
!==================================================================
SUBROUTINE MULT_P_TRM(YDNODE, KF, PVECIN, PVECOUT)
! Multiply matrix by transposed procetion matrix
TYPE(NODE_TYPE),INTENT(INOUT) :: YDNODE
INTEGER(KIND=JPIM),INTENT(IN) :: KF 
REAL(KIND=JPRB),INTENT(IN)    :: PVECIN(:,:)
REAL(KIND=JPRB),INTENT(OUT)   :: PVECOUT(:,:)

REAL(KIND=JPRB) :: ZVECOUT(YDNODE%ICOLS,KF)
INTEGER(KIND=JPIM) :: JK, JN, IDX, IM, IN, JF

!------------------------------------------------------------------

IN = YDNODE%ICOLS-YDNODE%IRANK
IM = YDNODE%IRANK
IF (IN > 0) THEN
  CALL GEMM('T', 'N', &
    &       IN, KF, IM, &
    &       1.0_JPRB, &
    &       YDNODE%PNONIM(1), IM, &
    &       PVECIN(1,1), IM, &
    &       0.0_JPRB, &
    &       ZVECOUT(YDNODE%IRANK+1,1),YDNODE%ICOLS)
ENDIF
DO JF = 1, KF
  DO JK = 1, YDNODE%IRANK
    IDX = YDNODE%ICLIST(JK)
    PVECOUT(IDX,JF) = PVECIN(JK,JF)
  ENDDO
  DO JN = YDNODE%IRANK + 1, YDNODE%ICOLS
    IDX = YDNODE%ICLIST(JN)
    PVECOUT(IDX,JF) = ZVECOUT(JN,JF)
  ENDDO
ENDDO
END SUBROUTINE MULT_P_TRM
!====================================================================
SUBROUTINE CONSTRUCT_HYBRID(PEPS,KCMAX,KLEAF,KMORDER,KFIRST_DEGREE,&
 & KPATH,KUNIT,PTHETA,PMAT,YHYBRID)
REAL(KIND=JPRD),INTENT(IN) :: PEPS
INTEGER(KIND=JPIM),INTENT(IN) :: KCMAX,KLEAF,KMORDER,KFIRST_DEGREE
CHARACTER(LEN=*),INTENT(IN) :: KPATH
INTEGER,INTENT(IN) :: KUNIT
REAL(KIND=JPRD),INTENT(IN) :: PTHETA(:),PMAT(:,:)
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: YHYBRID

INTEGER(KIND=JPIM) :: IBLOCK,ICOUNT,IORIGINAL_KIND,IORIGINAL_LEVELS,ITRIAL_COUNT
INTEGER(KIND=JPIM) :: IRANK_COUNT,IRANK_MIN,IRANK_MAX
INTEGER(KIND=JPIM) :: ICAND_RANK_COUNT,ICAND_RANK_MIN,ICAND_RANK_MAX
INTEGER(KIND=JPIB) :: ICOST,IRANK_SUM,ICAND_RANK_SUM
INTEGER(KIND=JPIB) :: ICROP_BLOCKS(3),ICROP_EMPTY(3),ICROP_VALUES(3),&
  & ICROP_ACTIVE(3),ICROP_BBOX(3),ICROP_ROW_SPAN(3),ICROP_COL_SPAN(3)
INTEGER :: ILENGTH,ISTATUS
REAL(KIND=JPRD) :: ZCOST_RATIO,ZCROP_EPS,ZEPS,ZRANK_MEAN,ZSELECT_RATIO
REAL(KIND=JPRD),PARAMETER :: ZSELECT_RATIO_DEFAULT=0.75_JPRD
CHARACTER(LEN=32) :: ZVALUE
LOGICAL :: LCROP_DIAGNOSTICS,LDETAILS,LDIAGNOSTICS,LREFINE,LLOWRANKONLY

CALL FREE_HYBRID(YHYBRID)
IF (SIZE(PMAT,1) == 0 .OR. SIZE(PMAT,2) == 0) RETURN
LDIAGNOSTICS=HYBRID_DIAGNOSTICS_REQUESTED()
LDETAILS=HYBRID_DETAIL_DIAGNOSTICS_REQUESTED()
LREFINE=HYBRID_REFINE_REQUESTED()
LLOWRANKONLY=HYBRID_LOW_RANK_ONLY_REQUESTED()
LCROP_DIAGNOSTICS=HYBRID_CROP_DIAGNOSTICS_REQUESTED()
ZCROP_EPS=EPSILON(1.0_JPRD)
IF (LCROP_DIAGNOSTICS) THEN
  CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_CROP_EPS',ZVALUE,&
    & LENGTH=ILENGTH,STATUS=ISTATUS)
  IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
    READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) ZCROP_EPS
    IF (ISTATUS /= 0 .OR. ZCROP_EPS <= 0.0_JPRD) ZCROP_EPS=EPSILON(1.0_JPRD)
  ENDIF
ENDIF
ZEPS=PEPS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_EPS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
  READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) ZEPS
  IF (ISTATUS /= 0 .OR. ZEPS <= 0.0_JPRD) ZEPS=PEPS
ENDIF
ZSELECT_RATIO=ZSELECT_RATIO_DEFAULT
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_SELECT_RATIO',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
  READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) ZSELECT_RATIO
  IF (ISTATUS /= 0 .OR. ZSELECT_RATIO <= 0.0_JPRD .OR. &
    & ZSELECT_RATIO >= 1.0_JPRD) ZSELECT_RATIO=ZSELECT_RATIO_DEFAULT
ENDIF

YHYBRID%CONSTRUCTED=.TRUE.
YHYBRID%DENSE_COST=INT(SIZE(PMAT,1),JPIB)*INT(SIZE(PMAT,2),JPIB)
ICAND_RANK_COUNT=0
ICAND_RANK_SUM=0
ICAND_RANK_MIN=HUGE(ICAND_RANK_MIN)
ICAND_RANK_MAX=0
ICROP_BLOCKS=0
ICROP_EMPTY=0
ICROP_VALUES=0
ICROP_ACTIVE=0
ICROP_BBOX=0
ICROP_ROW_SPAN=0
ICROP_COL_SPAN=0

IF (LREFINE) THEN
  ALLOCATE(YHYBRID%BLOCKS(64))
  ICOUNT=0
  ITRIAL_COUNT=0
  CALL BUILD_REFINED_BLOCK(1,SIZE(PMAT,1),1,SIZE(PMAT,2),ICOUNT)
  CALL RESIZE_BLOCK_STORAGE(ICOUNT,ICOUNT)
  YHYBRID%BLOCK_COUNT=ICOUNT
ELSE
  ICOUNT=0
  CALL VISIT_BLOCK(1,SIZE(PMAT,1),1,SIZE(PMAT,2),.FALSE.,ICOUNT)
  ALLOCATE(YHYBRID%BLOCKS(ICOUNT))
  ICOUNT=0
  CALL VISIT_BLOCK(1,SIZE(PMAT,1),1,SIZE(PMAT,2),.TRUE.,ICOUNT)
  YHYBRID%BLOCK_COUNT=ICOUNT

  DO IBLOCK=1,YHYBRID%BLOCK_COUNT
  ASSOCIATE(B=>YHYBRID%BLOCKS(IBLOCK))
  B%DENSE_COST=INT(B%NROWS,JPIB)*INT(B%NCOLS,JPIB)
  IORIGINAL_KIND=B%KIND
  IF (LCROP_DIAGNOSTICS) CALL ACCUMULATE_CROP_STATS(B%FIRST_ROW,&
    & B%FIRST_ROW+B%NROWS-1,B%FIRST_COL,B%FIRST_COL+B%NCOLS-1,&
    & IORIGINAL_KIND)
  IF (B%KIND == HYBRID_BUTTERFLY .AND. LLOWRANKONLY) B%KIND=HYBRID_DENSE
  IORIGINAL_LEVELS=0
  ICOST=B%DENSE_COST
  IRANK_COUNT=0
  IRANK_SUM=0
  IRANK_MIN=0
  IRANK_MAX=0
  SELECT CASE(B%KIND)
  CASE(HYBRID_LOW_RANK)
    CALL CONSTRUCT_BUTTERFLY(ZEPS,B%NCOLS,B%NROWS,B%NCOLS,&
      & PMAT(B%FIRST_ROW:B%FIRST_ROW+B%NROWS-1,&
      & B%FIRST_COL:B%FIRST_COL+B%NCOLS-1),B%BUT)
    ICOST=BUTTERFLY_COST(B%BUT)
    IORIGINAL_LEVELS=B%BUT%N_LEVELS
    CALL COLLECT_RANKS(B%BUT,IBLOCK,IORIGINAL_KIND,&
      & IRANK_COUNT,IRANK_SUM,IRANK_MIN,IRANK_MAX)
    IF (ICOST >= B%DENSE_COST) THEN
      CALL FREE_BUTTERFLY(B%BUT)
      B%KIND=HYBRID_DENSE
    ELSE
      B%FACTOR_COST=ICOST
    ENDIF
  CASE(HYBRID_BUTTERFLY)
    CALL CONSTRUCT_BUTTERFLY(ZEPS,MIN(KCMAX,B%NCOLS),B%NROWS,B%NCOLS,&
      & PMAT(B%FIRST_ROW:B%FIRST_ROW+B%NROWS-1,&
      & B%FIRST_COL:B%FIRST_COL+B%NCOLS-1),B%BUT)
    ICOST=BUTTERFLY_COST(B%BUT)
    IORIGINAL_LEVELS=B%BUT%N_LEVELS
    CALL COLLECT_RANKS(B%BUT,IBLOCK,IORIGINAL_KIND,&
      & IRANK_COUNT,IRANK_SUM,IRANK_MIN,IRANK_MAX)
    IF (ICOST >= B%DENSE_COST) THEN
      CALL FREE_BUTTERFLY(B%BUT)
      B%KIND=HYBRID_DENSE
    ELSE
      B%FACTOR_COST=ICOST
    ENDIF
  END SELECT

  IF (B%KIND == HYBRID_DENSE) THEN
    ALLOCATE(B%DENSE(B%NROWS,B%NCOLS))
    B%DENSE=REAL(PMAT(B%FIRST_ROW:B%FIRST_ROW+B%NROWS-1,&
      & B%FIRST_COL:B%FIRST_COL+B%NCOLS-1),JPRBT)
    B%FACTOR_COST=B%DENSE_COST
    YHYBRID%DENSE_BLOCKS=YHYBRID%DENSE_BLOCKS+1
  ELSEIF (B%KIND == HYBRID_LOW_RANK) THEN
    YHYBRID%LOW_RANK_BLOCKS=YHYBRID%LOW_RANK_BLOCKS+1
  ELSE
    YHYBRID%BUTTERFLY_BLOCKS=YHYBRID%BUTTERFLY_BLOCKS+1
  ENDIF
  YHYBRID%HYBRID_COST=YHYBRID%HYBRID_COST+B%FACTOR_COST
  IF (IRANK_COUNT > 0) THEN
    ICAND_RANK_COUNT=ICAND_RANK_COUNT+IRANK_COUNT
    ICAND_RANK_SUM=ICAND_RANK_SUM+IRANK_SUM
    ICAND_RANK_MIN=MIN(ICAND_RANK_MIN,IRANK_MIN)
    ICAND_RANK_MAX=MAX(ICAND_RANK_MAX,IRANK_MAX)
  ENDIF
  IF (LDETAILS) THEN
    ZCOST_RATIO=REAL(ICOST,JPRD)/REAL(B%DENSE_COST,JPRD)
    ZRANK_MEAN=0.0_JPRD
    IF (IRANK_COUNT > 0) ZRANK_MEAN=REAL(IRANK_SUM,JPRD)/REAL(IRANK_COUNT,JPRD)
    WRITE(KUNIT,*) 'GPU_HYBRID_BLOCK path=',TRIM(KPATH),' m=',KMORDER,&
      & ' block=',IBLOCK,' original=',TRIM(HYBRID_KIND_NAME(IORIGINAL_KIND)),&
      & ' final=',TRIM(HYBRID_KIND_NAME(B%KIND)),&
      & ' first_row=',B%FIRST_ROW,' rows=',B%NROWS,&
      & ' first_col=',B%FIRST_COL,' cols=',B%NCOLS,&
      & ' levels=',IORIGINAL_LEVELS,' dense_cost=',B%DENSE_COST,&
      & ' trial_cost=',ICOST,' factor_cost=',B%FACTOR_COST,&
      & ' cost_ratio=',ZCOST_RATIO,' rank_nodes=',IRANK_COUNT,&
      & ' rank_min=',IRANK_MIN,' rank_max=',IRANK_MAX,' rank_mean=',ZRANK_MEAN
  ENDIF
    END ASSOCIATE
  ENDDO
ENDIF

IF (LCROP_DIAGNOSTICS) THEN
  DO IORIGINAL_KIND=HYBRID_DENSE,HYBRID_BUTTERFLY
    WRITE(KUNIT,*) 'GPU_HYBRID_CROP path=',TRIM(KPATH),' m=',KMORDER,&
      & ' kind=',TRIM(HYBRID_KIND_NAME(IORIGINAL_KIND)),&
      & ' eps=',ZCROP_EPS,' blocks=',ICROP_BLOCKS(IORIGINAL_KIND),&
      & ' empty_blocks=',ICROP_EMPTY(IORIGINAL_KIND),&
      & ' values=',ICROP_VALUES(IORIGINAL_KIND),&
      & ' active=',ICROP_ACTIVE(IORIGINAL_KIND),&
      & ' bbox=',ICROP_BBOX(IORIGINAL_KIND),&
      & ' row_span=',ICROP_ROW_SPAN(IORIGINAL_KIND),&
      & ' col_span=',ICROP_COL_SPAN(IORIGINAL_KIND)
  ENDDO
ENDIF

YHYBRID%SELECTED=YHYBRID%LOW_RANK_BLOCKS+YHYBRID%BUTTERFLY_BLOCKS > 0 .AND. &
  & REAL(YHYBRID%HYBRID_COST,JPRD) < ZSELECT_RATIO*REAL(YHYBRID%DENSE_COST,JPRD)
IF (LDIAGNOSTICS) THEN
  ZCOST_RATIO=REAL(YHYBRID%HYBRID_COST,JPRD)/REAL(YHYBRID%DENSE_COST,JPRD)
  ZRANK_MEAN=0.0_JPRD
  IF (ICAND_RANK_COUNT > 0) THEN
    ZRANK_MEAN=REAL(ICAND_RANK_SUM,JPRD)/REAL(ICAND_RANK_COUNT,JPRD)
  ELSE
    ICAND_RANK_MIN=0
  ENDIF
  WRITE(KUNIT,*) 'GPU_HYBRID_CANDIDATE path=',TRIM(KPATH),' m=',KMORDER,&
    & ' rows=',SIZE(PMAT,1),' cols=',SIZE(PMAT,2),&
    & ' blocks=',YHYBRID%BLOCK_COUNT,' dense_blocks=',YHYBRID%DENSE_BLOCKS,&
    & ' low_rank_blocks=',YHYBRID%LOW_RANK_BLOCKS,&
    & ' butterfly_blocks=',YHYBRID%BUTTERFLY_BLOCKS,&
    & ' dense_cost=',YHYBRID%DENSE_COST,' hybrid_cost=',YHYBRID%HYBRID_COST,&
    & ' cost_ratio=',ZCOST_RATIO,' select_ratio=',ZSELECT_RATIO,' eps=',ZEPS,&
    & ' rank_nodes=',ICAND_RANK_COUNT,' rank_min=',ICAND_RANK_MIN,&
    & ' rank_max=',ICAND_RANK_MAX,' rank_mean=',ZRANK_MEAN,&
    & ' refined=',LREFINE,' low_rank_only=',LLOWRANKONLY,&
    & ' selected=',YHYBRID%SELECTED
ENDIF
IF (.NOT.YHYBRID%SELECTED) CALL RELEASE_HYBRID_BLOCKS(YHYBRID)

CONTAINS

LOGICAL FUNCTION HYBRID_DIAGNOSTICS_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_DIAGNOSTICS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
HYBRID_DIAGNOSTICS_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & INDEX('12',ZVALUE(1:1)) > 0
END FUNCTION HYBRID_DIAGNOSTICS_REQUESTED

LOGICAL FUNCTION HYBRID_DETAIL_DIAGNOSTICS_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_DIAGNOSTICS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
HYBRID_DETAIL_DIAGNOSTICS_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION HYBRID_DETAIL_DIAGNOSTICS_REQUESTED

LOGICAL FUNCTION HYBRID_REFINE_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_REFINE',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
HYBRID_REFINE_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION HYBRID_REFINE_REQUESTED

LOGICAL FUNCTION HYBRID_LOW_RANK_ONLY_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_LOW_RANK_ONLY',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
HYBRID_LOW_RANK_ONLY_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION HYBRID_LOW_RANK_ONLY_REQUESTED

LOGICAL FUNCTION HYBRID_CROP_DIAGNOSTICS_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_HYBRID_CROP_DIAGNOSTICS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
HYBRID_CROP_DIAGNOSTICS_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION HYBRID_CROP_DIAGNOSTICS_REQUESTED

SUBROUTINE ACCUMULATE_CROP_STATS(KR1,KR2,KC1,KC2,KKIND)
INTEGER(KIND=JPIM),INTENT(IN) :: KR1,KR2,KC1,KC2,KKIND
INTEGER(KIND=JPIM) :: IC,ICMAX,ICMIN,IR,IRMAX,IRMIN
INTEGER(KIND=JPIM),ALLOCATABLE :: ICMAX_BY_ROW(:),ICMIN_BY_ROW(:),&
  & IRMAX_BY_COL(:),IRMIN_BY_COL(:)
INTEGER(KIND=JPIB) :: IACTIVE,IBBOX,ICOL_SPAN,IROW_SPAN

ALLOCATE(ICMIN_BY_ROW(KR1:KR2),ICMAX_BY_ROW(KR1:KR2),&
  & IRMIN_BY_COL(KC1:KC2),IRMAX_BY_COL(KC1:KC2))
ICMIN_BY_ROW=KC2+1
ICMAX_BY_ROW=KC1-1
IRMIN_BY_COL=KR2+1
IRMAX_BY_COL=KR1-1
IACTIVE=0
IRMIN=KR2+1
IRMAX=KR1-1
ICMIN=KC2+1
ICMAX=KC1-1
DO IC=KC1,KC2
  DO IR=KR1,KR2
    IF (ABS(PMAT(IR,IC)) > ZCROP_EPS) THEN
      IACTIVE=IACTIVE+1
      IRMIN=MIN(IRMIN,IR)
      IRMAX=MAX(IRMAX,IR)
      ICMIN=MIN(ICMIN,IC)
      ICMAX=MAX(ICMAX,IC)
      ICMIN_BY_ROW(IR)=MIN(ICMIN_BY_ROW(IR),IC)
      ICMAX_BY_ROW(IR)=MAX(ICMAX_BY_ROW(IR),IC)
      IRMIN_BY_COL(IC)=MIN(IRMIN_BY_COL(IC),IR)
      IRMAX_BY_COL(IC)=MAX(IRMAX_BY_COL(IC),IR)
    ENDIF
  ENDDO
ENDDO
IBBOX=0
IROW_SPAN=0
ICOL_SPAN=0
IF (IACTIVE > 0) THEN
  IBBOX=INT(IRMAX-IRMIN+1,JPIB)*INT(ICMAX-ICMIN+1,JPIB)
  DO IR=KR1,KR2
    IF (ICMAX_BY_ROW(IR) >= ICMIN_BY_ROW(IR)) &
      & IROW_SPAN=IROW_SPAN+ICMAX_BY_ROW(IR)-ICMIN_BY_ROW(IR)+1
  ENDDO
  DO IC=KC1,KC2
    IF (IRMAX_BY_COL(IC) >= IRMIN_BY_COL(IC)) &
      & ICOL_SPAN=ICOL_SPAN+IRMAX_BY_COL(IC)-IRMIN_BY_COL(IC)+1
  ENDDO
ELSE
  ICROP_EMPTY(KKIND)=ICROP_EMPTY(KKIND)+1
ENDIF
ICROP_BLOCKS(KKIND)=ICROP_BLOCKS(KKIND)+1
ICROP_VALUES(KKIND)=ICROP_VALUES(KKIND)+&
  & INT(KR2-KR1+1,JPIB)*INT(KC2-KC1+1,JPIB)
ICROP_ACTIVE(KKIND)=ICROP_ACTIVE(KKIND)+IACTIVE
ICROP_BBOX(KKIND)=ICROP_BBOX(KKIND)+IBBOX
ICROP_ROW_SPAN(KKIND)=ICROP_ROW_SPAN(KKIND)+IROW_SPAN
ICROP_COL_SPAN(KKIND)=ICROP_COL_SPAN(KKIND)+ICOL_SPAN
DEALLOCATE(ICMIN_BY_ROW,ICMAX_BY_ROW,IRMIN_BY_COL,IRMAX_BY_COL)
END SUBROUTINE ACCUMULATE_CROP_STATS

CHARACTER(LEN=9) FUNCTION HYBRID_KIND_NAME(KKIND)
INTEGER(KIND=JPIM),INTENT(IN) :: KKIND

SELECT CASE(KKIND)
CASE(HYBRID_LOW_RANK)
  HYBRID_KIND_NAME='low_rank'
CASE(HYBRID_BUTTERFLY)
  HYBRID_KIND_NAME='butterfly'
CASE DEFAULT
  HYBRID_KIND_NAME='dense'
END SELECT
END FUNCTION HYBRID_KIND_NAME

SUBROUTINE COLLECT_RANKS(BUT,KBLOCK,KKIND,KCOUNT,KSUM,KMIN,KMAX)
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
INTEGER(KIND=JPIM),INTENT(IN) :: KBLOCK,KKIND
INTEGER(KIND=JPIM),INTENT(OUT) :: KCOUNT,KMIN,KMAX
INTEGER(KIND=JPIB),INTENT(OUT) :: KSUM
INTEGER(KIND=JPIM) :: JL,JJ,JK,ILEVEL_COUNT,ILEVEL_MIN,ILEVEL_MAX
INTEGER(KIND=JPIB) :: ILEVEL_SUM
REAL(KIND=JPRD) :: ZLEVEL_MEAN

KCOUNT=0
KSUM=0
KMIN=HUGE(KMIN)
KMAX=0
IF (.NOT.ASSOCIATED(BUT%SLEV)) THEN
  KMIN=0
  RETURN
ENDIF

DO JL=0,BUT%N_LEVELS
  ILEVEL_COUNT=0
  ILEVEL_SUM=0
  ILEVEL_MIN=HUGE(ILEVEL_MIN)
  ILEVEL_MAX=0
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      ILEVEL_COUNT=ILEVEL_COUNT+1
      ILEVEL_SUM=ILEVEL_SUM+INT(BUT%SLEV(JL)%NODE(JJ,JK)%IRANK,JPIB)
      ILEVEL_MIN=MIN(ILEVEL_MIN,BUT%SLEV(JL)%NODE(JJ,JK)%IRANK)
      ILEVEL_MAX=MAX(ILEVEL_MAX,BUT%SLEV(JL)%NODE(JJ,JK)%IRANK)
    ENDDO
  ENDDO
  KCOUNT=KCOUNT+ILEVEL_COUNT
  KSUM=KSUM+ILEVEL_SUM
  KMIN=MIN(KMIN,ILEVEL_MIN)
  KMAX=MAX(KMAX,ILEVEL_MAX)
  IF (LDETAILS) THEN
    ZLEVEL_MEAN=REAL(ILEVEL_SUM,JPRD)/REAL(ILEVEL_COUNT,JPRD)
    WRITE(KUNIT,*) 'GPU_HYBRID_LEVEL path=',TRIM(KPATH),' m=',KMORDER,&
      & ' block=',KBLOCK,' original=',TRIM(HYBRID_KIND_NAME(KKIND)),&
      & ' level=',JL,' nodes=',ILEVEL_COUNT,' rank_min=',ILEVEL_MIN,&
      & ' rank_max=',ILEVEL_MAX,' rank_mean=',ZLEVEL_MEAN
  ENDIF
ENDDO
END SUBROUTINE COLLECT_RANKS

RECURSIVE SUBROUTINE BUILD_REFINED_BLOCK(KR1,KR2,KC1,KC2,KCOUNT)
INTEGER(KIND=JPIM),INTENT(IN) :: KR1,KR2,KC1,KC2
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCOUNT
INTEGER(KIND=JPIM) :: IRMID,ICMID,INR,INC,IORIGINAL_KIND,IORIGINAL_LEVELS
INTEGER(KIND=JPIM) :: IRANK_COUNT,IRANK_MIN,IRANK_MAX
INTEGER(KIND=JPIB) :: ICOST,IRANK_SUM
REAL(KIND=JPRD) :: ZBLOCK_COST_RATIO,ZBLOCK_RANK_MEAN
TYPE(HYBRID_BLOCK) :: YBLOCK

INR=KR2-KR1+1
INC=KC2-KC1+1
IF (INR > 2*INC .AND. INR > 1) THEN
  IRMID=(KR1+KR2)/2
  CALL BUILD_REFINED_BLOCK(KR1,IRMID,KC1,KC2,KCOUNT)
  CALL BUILD_REFINED_BLOCK(IRMID+1,KR2,KC1,KC2,KCOUNT)
  RETURN
ELSEIF (INC > 2*INR .AND. INC > 1) THEN
  ICMID=(KC1+KC2)/2
  CALL BUILD_REFINED_BLOCK(KR1,KR2,KC1,ICMID,KCOUNT)
  CALL BUILD_REFINED_BLOCK(KR1,KR2,ICMID+1,KC2,KCOUNT)
  RETURN
ENDIF

IORIGINAL_KIND=CLASSIFY_BLOCK(KR1,KR2,KC1,KC2)
IF (IORIGINAL_KIND == HYBRID_DENSE .AND. INR > KLEAF .AND. INC > KLEAF) THEN
  CALL SPLIT_REFINED_BLOCK(KR1,KR2,KC1,KC2,KCOUNT)
  RETURN
ENDIF
IF (LCROP_DIAGNOSTICS) CALL ACCUMULATE_CROP_STATS(KR1,KR2,KC1,KC2,&
  & IORIGINAL_KIND)

ITRIAL_COUNT=ITRIAL_COUNT+1
YBLOCK%KIND=IORIGINAL_KIND
IF (YBLOCK%KIND == HYBRID_BUTTERFLY .AND. LLOWRANKONLY) &
  & YBLOCK%KIND=HYBRID_DENSE
YBLOCK%FIRST_ROW=KR1
YBLOCK%FIRST_COL=KC1
YBLOCK%NROWS=INR
YBLOCK%NCOLS=INC
YBLOCK%DENSE_COST=INT(INR,JPIB)*INT(INC,JPIB)
IORIGINAL_LEVELS=0
ICOST=YBLOCK%DENSE_COST
IRANK_COUNT=0
IRANK_SUM=0
IRANK_MIN=0
IRANK_MAX=0

SELECT CASE(YBLOCK%KIND)
CASE(HYBRID_LOW_RANK)
  CALL CONSTRUCT_BUTTERFLY(ZEPS,INC,INR,INC,&
    & PMAT(KR1:KR2,KC1:KC2),YBLOCK%BUT)
  ICOST=BUTTERFLY_COST(YBLOCK%BUT)
  IORIGINAL_LEVELS=YBLOCK%BUT%N_LEVELS
  CALL COLLECT_RANKS(YBLOCK%BUT,ITRIAL_COUNT,IORIGINAL_KIND,&
    & IRANK_COUNT,IRANK_SUM,IRANK_MIN,IRANK_MAX)
CASE(HYBRID_BUTTERFLY)
  CALL CONSTRUCT_BUTTERFLY(ZEPS,MIN(KCMAX,INC),INR,INC,&
    & PMAT(KR1:KR2,KC1:KC2),YBLOCK%BUT)
  ICOST=BUTTERFLY_COST(YBLOCK%BUT)
  IORIGINAL_LEVELS=YBLOCK%BUT%N_LEVELS
  CALL COLLECT_RANKS(YBLOCK%BUT,ITRIAL_COUNT,IORIGINAL_KIND,&
    & IRANK_COUNT,IRANK_SUM,IRANK_MIN,IRANK_MAX)
END SELECT

IF (YBLOCK%KIND /= HYBRID_DENSE .AND. ICOST >= YBLOCK%DENSE_COST .AND. &
  & MIN(INR,INC) > KLEAF) THEN
  IF (LDETAILS) THEN
    WRITE(KUNIT,*) 'GPU_HYBRID_REFINE path=',TRIM(KPATH),' m=',KMORDER,&
      & ' trial=',ITRIAL_COUNT,' original=',TRIM(HYBRID_KIND_NAME(IORIGINAL_KIND)),&
      & ' first_row=',KR1,' rows=',INR,' first_col=',KC1,' cols=',INC,&
      & ' dense_cost=',YBLOCK%DENSE_COST,' trial_cost=',ICOST
  ENDIF
  CALL FREE_BUTTERFLY(YBLOCK%BUT)
  CALL SPLIT_REFINED_BLOCK(KR1,KR2,KC1,KC2,KCOUNT)
  RETURN
ENDIF

IF (YBLOCK%KIND /= HYBRID_DENSE .AND. ICOST >= YBLOCK%DENSE_COST) THEN
  CALL FREE_BUTTERFLY(YBLOCK%BUT)
  YBLOCK%KIND=HYBRID_DENSE
ELSEIF (YBLOCK%KIND /= HYBRID_DENSE) THEN
  YBLOCK%FACTOR_COST=ICOST
ENDIF

IF (YBLOCK%KIND == HYBRID_DENSE) THEN
  ALLOCATE(YBLOCK%DENSE(INR,INC))
  YBLOCK%DENSE=REAL(PMAT(KR1:KR2,KC1:KC2),JPRBT)
  YBLOCK%FACTOR_COST=YBLOCK%DENSE_COST
  YHYBRID%DENSE_BLOCKS=YHYBRID%DENSE_BLOCKS+1
ELSEIF (YBLOCK%KIND == HYBRID_LOW_RANK) THEN
  YHYBRID%LOW_RANK_BLOCKS=YHYBRID%LOW_RANK_BLOCKS+1
ELSE
  YHYBRID%BUTTERFLY_BLOCKS=YHYBRID%BUTTERFLY_BLOCKS+1
ENDIF
YHYBRID%HYBRID_COST=YHYBRID%HYBRID_COST+YBLOCK%FACTOR_COST
IF (IRANK_COUNT > 0) THEN
  ICAND_RANK_COUNT=ICAND_RANK_COUNT+IRANK_COUNT
  ICAND_RANK_SUM=ICAND_RANK_SUM+IRANK_SUM
  ICAND_RANK_MIN=MIN(ICAND_RANK_MIN,IRANK_MIN)
  ICAND_RANK_MAX=MAX(ICAND_RANK_MAX,IRANK_MAX)
ENDIF

KCOUNT=KCOUNT+1
CALL ENSURE_BLOCK_CAPACITY(KCOUNT,KCOUNT-1)
IF (LDETAILS) THEN
  ZBLOCK_COST_RATIO=REAL(ICOST,JPRD)/REAL(YBLOCK%DENSE_COST,JPRD)
  ZBLOCK_RANK_MEAN=0.0_JPRD
  IF (IRANK_COUNT > 0) &
    ZBLOCK_RANK_MEAN=REAL(IRANK_SUM,JPRD)/REAL(IRANK_COUNT,JPRD)
  WRITE(KUNIT,*) 'GPU_HYBRID_BLOCK path=',TRIM(KPATH),' m=',KMORDER,&
    & ' block=',KCOUNT,' trial=',ITRIAL_COUNT,&
    & ' original=',TRIM(HYBRID_KIND_NAME(IORIGINAL_KIND)),&
    & ' final=',TRIM(HYBRID_KIND_NAME(YBLOCK%KIND)),&
    & ' first_row=',KR1,' rows=',INR,' first_col=',KC1,' cols=',INC,&
    & ' levels=',IORIGINAL_LEVELS,' dense_cost=',YBLOCK%DENSE_COST,&
    & ' trial_cost=',ICOST,' factor_cost=',YBLOCK%FACTOR_COST,&
    & ' cost_ratio=',ZBLOCK_COST_RATIO,' rank_nodes=',IRANK_COUNT,&
    & ' rank_min=',IRANK_MIN,' rank_max=',IRANK_MAX,&
    & ' rank_mean=',ZBLOCK_RANK_MEAN
ENDIF
CALL MOVE_HYBRID_BLOCK(YBLOCK,YHYBRID%BLOCKS(KCOUNT))
END SUBROUTINE BUILD_REFINED_BLOCK

RECURSIVE SUBROUTINE SPLIT_REFINED_BLOCK(KR1,KR2,KC1,KC2,KCOUNT)
INTEGER(KIND=JPIM),INTENT(IN) :: KR1,KR2,KC1,KC2
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCOUNT
INTEGER(KIND=JPIM) :: IRMID,ICMID

IRMID=(KR1+KR2)/2
ICMID=(KC1+KC2)/2
CALL BUILD_REFINED_BLOCK(KR1,IRMID,KC1,ICMID,KCOUNT)
CALL BUILD_REFINED_BLOCK(KR1,IRMID,ICMID+1,KC2,KCOUNT)
CALL BUILD_REFINED_BLOCK(IRMID+1,KR2,KC1,ICMID,KCOUNT)
CALL BUILD_REFINED_BLOCK(IRMID+1,KR2,ICMID+1,KC2,KCOUNT)
END SUBROUTINE SPLIT_REFINED_BLOCK

SUBROUTINE ENSURE_BLOCK_CAPACITY(KNEEDED,KCOUNT)
INTEGER(KIND=JPIM),INTENT(IN) :: KNEEDED,KCOUNT
INTEGER(KIND=JPIM) :: INEW

IF (KNEEDED <= SIZE(YHYBRID%BLOCKS)) RETURN
INEW=MAX(KNEEDED,2*SIZE(YHYBRID%BLOCKS))
CALL RESIZE_BLOCK_STORAGE(INEW,KCOUNT)
END SUBROUTINE ENSURE_BLOCK_CAPACITY

SUBROUTINE RESIZE_BLOCK_STORAGE(KSIZE,KCOUNT)
INTEGER(KIND=JPIM),INTENT(IN) :: KSIZE,KCOUNT
INTEGER(KIND=JPIM) :: JB
TYPE(HYBRID_BLOCK),ALLOCATABLE :: YBLOCKS(:)

IF (KSIZE == SIZE(YHYBRID%BLOCKS)) RETURN
ALLOCATE(YBLOCKS(KSIZE))
DO JB=1,KCOUNT
  CALL MOVE_HYBRID_BLOCK(YHYBRID%BLOCKS(JB),YBLOCKS(JB))
ENDDO
DEALLOCATE(YHYBRID%BLOCKS)
CALL MOVE_ALLOC(YBLOCKS,YHYBRID%BLOCKS)
END SUBROUTINE RESIZE_BLOCK_STORAGE

SUBROUTINE MOVE_HYBRID_BLOCK(YFROM,YTO)
TYPE(HYBRID_BLOCK),INTENT(INOUT) :: YFROM,YTO

YTO%KIND=YFROM%KIND
YTO%FIRST_ROW=YFROM%FIRST_ROW
YTO%FIRST_COL=YFROM%FIRST_COL
YTO%NROWS=YFROM%NROWS
YTO%NCOLS=YFROM%NCOLS
YTO%DENSE_COST=YFROM%DENSE_COST
YTO%FACTOR_COST=YFROM%FACTOR_COST
YTO%WORK_BASE=YFROM%WORK_BASE
YTO%BUT=YFROM%BUT
NULLIFY(YFROM%BUT%SLEV)
IF (ALLOCATED(YFROM%DENSE)) CALL MOVE_ALLOC(YFROM%DENSE,YTO%DENSE)
END SUBROUTINE MOVE_HYBRID_BLOCK

RECURSIVE SUBROUTINE VISIT_BLOCK(KR1,KR2,KC1,KC2,LFILL,KCOUNT)
INTEGER(KIND=JPIM),INTENT(IN) :: KR1,KR2,KC1,KC2
LOGICAL,INTENT(IN) :: LFILL
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCOUNT
INTEGER(KIND=JPIM) :: IRMID,ICMID,INR,INC,IKIND

INR=KR2-KR1+1
INC=KC2-KC1+1
IF (INR > 2*INC .AND. INR > 1) THEN
  IRMID=(KR1+KR2)/2
  CALL VISIT_BLOCK(KR1,IRMID,KC1,KC2,LFILL,KCOUNT)
  CALL VISIT_BLOCK(IRMID+1,KR2,KC1,KC2,LFILL,KCOUNT)
  RETURN
ELSEIF (INC > 2*INR .AND. INC > 1) THEN
  ICMID=(KC1+KC2)/2
  CALL VISIT_BLOCK(KR1,KR2,KC1,ICMID,LFILL,KCOUNT)
  CALL VISIT_BLOCK(KR1,KR2,ICMID+1,KC2,LFILL,KCOUNT)
  RETURN
ENDIF

IKIND=CLASSIFY_BLOCK(KR1,KR2,KC1,KC2)
IF (IKIND == HYBRID_DENSE .AND. INR > KLEAF .AND. INC > KLEAF) THEN
  IRMID=(KR1+KR2)/2
  ICMID=(KC1+KC2)/2
  CALL VISIT_BLOCK(KR1,IRMID,KC1,ICMID,LFILL,KCOUNT)
  CALL VISIT_BLOCK(KR1,IRMID,ICMID+1,KC2,LFILL,KCOUNT)
  CALL VISIT_BLOCK(IRMID+1,KR2,KC1,ICMID,LFILL,KCOUNT)
  CALL VISIT_BLOCK(IRMID+1,KR2,ICMID+1,KC2,LFILL,KCOUNT)
  RETURN
ENDIF

KCOUNT=KCOUNT+1
IF (LFILL) THEN
  YHYBRID%BLOCKS(KCOUNT)%KIND=IKIND
  YHYBRID%BLOCKS(KCOUNT)%FIRST_ROW=KR1
  YHYBRID%BLOCKS(KCOUNT)%FIRST_COL=KC1
  YHYBRID%BLOCKS(KCOUNT)%NROWS=INR
  YHYBRID%BLOCKS(KCOUNT)%NCOLS=INC
ENDIF
END SUBROUTINE VISIT_BLOCK

INTEGER(KIND=JPIM) FUNCTION CLASSIFY_BLOCK(KR1,KR2,KC1,KC2)
INTEGER(KIND=JPIM),INTENT(IN) :: KR1,KR2,KC1,KC2
REAL(KIND=JPRD) :: ZMIN,ZMAX

ZMIN=PTHETA(KR1)-TURNING_ANGLE(KC2)
ZMAX=PTHETA(KR2)-TURNING_ANGLE(KC1)
IF (ZMIN > 0.0_JPRD) THEN
  CLASSIFY_BLOCK=HYBRID_BUTTERFLY
ELSEIF (ZMAX < 0.0_JPRD) THEN
  CLASSIFY_BLOCK=HYBRID_LOW_RANK
ELSE
  CLASSIFY_BLOCK=HYBRID_DENSE
ENDIF
END FUNCTION CLASSIFY_BLOCK

REAL(KIND=JPRD) FUNCTION TURNING_ANGLE(KCOL)
INTEGER(KIND=JPIM),INTENT(IN) :: KCOL
INTEGER(KIND=JPIM) :: IN
REAL(KIND=JPRD) :: ZRATIO

IN=KFIRST_DEGREE-2*(KCOL-1)
ZRATIO=SQRT(MAX(REAL(KMORDER*KMORDER,JPRD)-0.25_JPRD,0.0_JPRD))/&
  & (REAL(IN,JPRD)+0.5_JPRD)
TURNING_ANGLE=ASIN(MIN(MAX(ZRATIO,0.0_JPRD),1.0_JPRD))
END FUNCTION TURNING_ANGLE

END SUBROUTINE CONSTRUCT_HYBRID
!====================================================================
SUBROUTINE CONSTRUCT_TRANSPOSED_HYBRID(PEPS,KCMAX,PMAT,YHYBRID,YTRANSPOSED)
REAL(KIND=JPRD),INTENT(IN) :: PEPS,PMAT(:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KCMAX
TYPE(HYBRID_MATRIX),INTENT(IN) :: YHYBRID
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: YTRANSPOSED

REAL(KIND=JPRD),ALLOCATABLE :: ZTRANSPOSE(:,:)
INTEGER(KIND=JPIM) :: IB,ICMAX
INTEGER(KIND=JPIB) :: ICOST

CALL FREE_HYBRID(YTRANSPOSED)
IF (.NOT.ALLOCATED(YHYBRID%BLOCKS)) RETURN
YTRANSPOSED%CONSTRUCTED=.TRUE.
YTRANSPOSED%BLOCK_COUNT=YHYBRID%BLOCK_COUNT
ALLOCATE(YTRANSPOSED%BLOCKS(YTRANSPOSED%BLOCK_COUNT))

DO IB=1,YHYBRID%BLOCK_COUNT
  ASSOCIATE(B=>YHYBRID%BLOCKS(IB),T=>YTRANSPOSED%BLOCKS(IB))
  T%FIRST_ROW=B%FIRST_COL
  T%FIRST_COL=B%FIRST_ROW
  T%NROWS=B%NCOLS
  T%NCOLS=B%NROWS
  T%DENSE_COST=B%DENSE_COST
  YTRANSPOSED%DENSE_COST=YTRANSPOSED%DENSE_COST+T%DENSE_COST
  ALLOCATE(ZTRANSPOSE(T%NROWS,T%NCOLS))
  ZTRANSPOSE=TRANSPOSE(PMAT(B%FIRST_ROW:B%FIRST_ROW+B%NROWS-1,&
    & B%FIRST_COL:B%FIRST_COL+B%NCOLS-1))
  ICMAX=MIN(KCMAX,T%NCOLS)
  IF (B%KIND == HYBRID_LOW_RANK) ICMAX=T%NCOLS
  CALL CONSTRUCT_BUTTERFLY(PEPS,ICMAX,T%NROWS,T%NCOLS,&
    & ZTRANSPOSE,T%BUT)
  ICOST=BUTTERFLY_COST(T%BUT)
  IF (ICOST < T%DENSE_COST) THEN
    T%FACTOR_COST=ICOST
    IF (T%BUT%N_LEVELS == 0) THEN
      T%KIND=HYBRID_LOW_RANK
      YTRANSPOSED%LOW_RANK_BLOCKS=YTRANSPOSED%LOW_RANK_BLOCKS+1
    ELSE
      T%KIND=HYBRID_BUTTERFLY
      YTRANSPOSED%BUTTERFLY_BLOCKS=YTRANSPOSED%BUTTERFLY_BLOCKS+1
    ENDIF
  ELSE
    CALL FREE_BUTTERFLY(T%BUT)
    T%KIND=HYBRID_DENSE
    T%FACTOR_COST=T%DENSE_COST
    ALLOCATE(T%DENSE(T%NROWS,T%NCOLS))
    T%DENSE=REAL(ZTRANSPOSE,JPRBT)
    YTRANSPOSED%DENSE_BLOCKS=YTRANSPOSED%DENSE_BLOCKS+1
  ENDIF
  YTRANSPOSED%HYBRID_COST=YTRANSPOSED%HYBRID_COST+T%FACTOR_COST
  DEALLOCATE(ZTRANSPOSE)
  END ASSOCIATE
ENDDO

YTRANSPOSED%SELECTED=YTRANSPOSED%LOW_RANK_BLOCKS+&
  & YTRANSPOSED%BUTTERFLY_BLOCKS > 0 .AND. &
  & YTRANSPOSED%HYBRID_COST < YTRANSPOSED%DENSE_COST
IF (.NOT.YTRANSPOSED%SELECTED) CALL RELEASE_HYBRID_BLOCKS(YTRANSPOSED)
END SUBROUTINE CONSTRUCT_TRANSPOSED_HYBRID
!====================================================================
SUBROUTINE ANALYZE_TRANSPOSED_HYBRID(PEPS,KCMAX,PMAT,YHYBRID,&
 & KDENSE,KFACTOR,KBLOCKS,KSELECTED,KCONTRIB_SUM,KCONTRIB_MAX)
REAL(KIND=JPRD),INTENT(IN) :: PEPS,PMAT(:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KCMAX
TYPE(HYBRID_MATRIX),INTENT(IN) :: YHYBRID
INTEGER(KIND=JPIB),INTENT(OUT) :: KDENSE,KFACTOR,KCONTRIB_SUM
INTEGER(KIND=JPIM),INTENT(OUT) :: KBLOCKS,KSELECTED,KCONTRIB_MAX

INTEGER(KIND=JPIM),ALLOCATABLE :: ICONTRIB(:)
TYPE(HYBRID_MATRIX) :: YTRANSPOSED
INTEGER(KIND=JPIM) :: IB

KDENSE=0
KFACTOR=0
KBLOCKS=0
KSELECTED=0
KCONTRIB_SUM=0
KCONTRIB_MAX=0
CALL CONSTRUCT_TRANSPOSED_HYBRID(PEPS,KCMAX,PMAT,YHYBRID,YTRANSPOSED)
IF (.NOT.ALLOCATED(YTRANSPOSED%BLOCKS)) RETURN

ALLOCATE(ICONTRIB(SIZE(PMAT,2)))
ICONTRIB=0
DO IB=1,YTRANSPOSED%BLOCK_COUNT
  ASSOCIATE(B=>YTRANSPOSED%BLOCKS(IB))
  KDENSE=KDENSE+B%DENSE_COST
  KFACTOR=KFACTOR+B%FACTOR_COST
  KBLOCKS=KBLOCKS+1
  IF (B%KIND /= HYBRID_DENSE) KSELECTED=KSELECTED+1
  ICONTRIB(B%FIRST_ROW:B%FIRST_ROW+B%NROWS-1)=&
    & ICONTRIB(B%FIRST_ROW:B%FIRST_ROW+B%NROWS-1)+1
  END ASSOCIATE
ENDDO
KCONTRIB_SUM=SUM(INT(ICONTRIB,JPIB))
KCONTRIB_MAX=MAXVAL(ICONTRIB)
DEALLOCATE(ICONTRIB)
CALL FREE_HYBRID(YTRANSPOSED)
END SUBROUTINE ANALYZE_TRANSPOSED_HYBRID
!====================================================================
LOGICAL FUNCTION LEGENDRE_TRUNCATION_DIAGNOSTICS_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_LEGENDRE_TRUNCATION_DIAGNOSTICS',&
  & ZVALUE,LENGTH=ILENGTH,STATUS=ISTATUS)
LEGENDRE_TRUNCATION_DIAGNOSTICS_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION LEGENDRE_TRUNCATION_DIAGNOSTICS_REQUESTED
!====================================================================
SUBROUTINE ANALYZE_LEGENDRE_TRUNCATION(PMAT,PEPS,KBANDS,KKEPT,PDROPPED2,PTOTAL2)
REAL(KIND=JPRD),INTENT(IN) :: PMAT(:,:),PEPS
INTEGER(KIND=JPIM),INTENT(IN) :: KBANDS(:)
INTEGER(KIND=JPIB),INTENT(OUT) :: KKEPT(:)
REAL(KIND=JPRD),INTENT(OUT) :: PDROPPED2(:),PTOTAL2

INTEGER(KIND=JPIM),ALLOCATABLE :: ICUTOFF(:)
INTEGER(KIND=JPIM) :: IB,IBANDS,IC,ICUT,IR,IR1,IR2
INTEGER(KIND=JPIM) :: INC,INR
REAL(KIND=JPRD) :: ZBUDGET,ZDROPPED2,ZROW2,ZVALUE2

INR=SIZE(PMAT,1)
INC=SIZE(PMAT,2)
KKEPT=0
PDROPPED2=0.0_JPRD
PTOTAL2=0.0_JPRD
IF (INR == 0 .OR. INC == 0) RETURN

ALLOCATE(ICUTOFF(INR))
DO IR=1,INR
  ZROW2=0.0_JPRD
  DO IC=1,INC
    ZROW2=ZROW2+PMAT(IR,IC)*PMAT(IR,IC)
  ENDDO
  PTOTAL2=PTOTAL2+ZROW2
  ZBUDGET=PEPS*PEPS*ZROW2
  ZDROPPED2=0.0_JPRD
  ICUTOFF(IR)=INC
  DO IC=INC,1,-1
    ZVALUE2=PMAT(IR,IC)*PMAT(IR,IC)
    IF (ZDROPPED2+ZVALUE2 > ZBUDGET) EXIT
    ZDROPPED2=ZDROPPED2+ZVALUE2
    ICUTOFF(IR)=IC-1
  ENDDO
ENDDO

DO IB=1,SIZE(KBANDS)
  IF (KBANDS(IB) <= 0) THEN
    DO IR=1,INR
      ICUT=ICUTOFF(IR)
      KKEPT(IB)=KKEPT(IB)+ICUT
      DO IC=ICUT+1,INC
        PDROPPED2(IB)=PDROPPED2(IB)+PMAT(IR,IC)*PMAT(IR,IC)
      ENDDO
    ENDDO
    CYCLE
  ENDIF

  IBANDS=MIN(KBANDS(IB),INR)
  DO IR=1,IBANDS
    IR1=1+(IR-1)*INR/IBANDS
    IR2=IR*INR/IBANDS
    ICUT=MAXVAL(ICUTOFF(IR1:IR2))
    KKEPT(IB)=KKEPT(IB)+INT(IR2-IR1+1,JPIB)*INT(ICUT,JPIB)
    DO IC=ICUT+1,INC
      PDROPPED2(IB)=PDROPPED2(IB)+SUM(PMAT(IR1:IR2,IC)*PMAT(IR1:IR2,IC))
    ENDDO
  ENDDO
ENDDO
DEALLOCATE(ICUTOFF)
END SUBROUTINE ANALYZE_LEGENDRE_TRUNCATION
!====================================================================
INTEGER(KIND=JPIB) FUNCTION BUTTERFLY_COST(YD_STRUCT)
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: YD_STRUCT
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR

BUTTERFLY_COST=0
IF (.NOT.ASSOCIATED(YD_STRUCT%SLEV)) RETURN
DO JK=1,YD_STRUCT%SLEV(0)%IK
  BUTTERFLY_COST=BUTTERFLY_COST+&
    & INT(YD_STRUCT%SLEV(0)%NODE(1,JK)%ICOLS,JPIB)*&
    & INT(YD_STRUCT%SLEV(0)%NODE(1,JK)%IRANK,JPIB)
ENDDO
DO JL=1,YD_STRUCT%N_LEVELS
  DO JK=1,YD_STRUCT%SLEV(JL)%IK
    DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
      IRANKL=YD_STRUCT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)%IRANK
      IRANKR=0
      IF (2*JK <= YD_STRUCT%SLEV(JL-1)%IK) &
        IRANKR=YD_STRUCT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)%IRANK
      BUTTERFLY_COST=BUTTERFLY_COST+INT(IRANKL+IRANKR,JPIB)*&
        & INT(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%IRANK,JPIB)
    ENDDO
  ENDDO
ENDDO
JL=YD_STRUCT%N_LEVELS
DO JK=1,YD_STRUCT%SLEV(JL)%IK
  DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
    BUTTERFLY_COST=BUTTERFLY_COST+&
      & INT(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%IROWS,JPIB)*&
      & INT(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%IRANK,JPIB)
  ENDDO
ENDDO
END FUNCTION BUTTERFLY_COST
!====================================================================
SUBROUTINE FREE_HYBRID(YHYBRID)
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: YHYBRID

CALL RELEASE_HYBRID_BLOCKS(YHYBRID)
YHYBRID%SELECTED=.FALSE.
YHYBRID%CONSTRUCTED=.FALSE.
YHYBRID%DENSE_BLOCKS=0
YHYBRID%LOW_RANK_BLOCKS=0
YHYBRID%BUTTERFLY_BLOCKS=0
YHYBRID%DENSE_COST=0
YHYBRID%HYBRID_COST=0
END SUBROUTINE FREE_HYBRID
!====================================================================
SUBROUTINE RELEASE_HYBRID_BLOCKS(YHYBRID)
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: YHYBRID
INTEGER(KIND=JPIM) :: JB

IF (ALLOCATED(YHYBRID%BLOCKS)) THEN
  DO JB=1,SIZE(YHYBRID%BLOCKS)
    CALL FREE_BUTTERFLY(YHYBRID%BLOCKS(JB)%BUT)
    IF (ALLOCATED(YHYBRID%BLOCKS(JB)%DENSE)) &
      DEALLOCATE(YHYBRID%BLOCKS(JB)%DENSE)
  ENDDO
  DEALLOCATE(YHYBRID%BLOCKS)
ENDIF
YHYBRID%BLOCK_COUNT=0
END SUBROUTINE RELEASE_HYBRID_BLOCKS
!====================================================================
SUBROUTINE FREE_BUTTERFLY(YD_STRUCT)
TYPE(BUTTERFLY_STRUCT),INTENT(INOUT) :: YD_STRUCT
INTEGER(KIND=JPIM) :: JL,JJ,JK

IF (ASSOCIATED(YD_STRUCT%SLEV)) THEN
  DO JL=LBOUND(YD_STRUCT%SLEV,1),UBOUND(YD_STRUCT%SLEV,1)
    IF (ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE)) THEN
      DO JK=1,YD_STRUCT%SLEV(JL)%IK
        DO JJ=1,YD_STRUCT%SLEV(JL)%IJ
          IF (ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%ICLIST)) &
            DEALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%ICLIST)
          IF (ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%PNONIM)) &
            DEALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%PNONIM)
          IF (ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%B)) &
            DEALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%B)
          IF (ASSOCIATED(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%DB)) &
            DEALLOCATE(YD_STRUCT%SLEV(JL)%NODE(JJ,JK)%DB)
        ENDDO
      ENDDO
      DEALLOCATE(YD_STRUCT%SLEV(JL)%NODE)
    ENDIF
  ENDDO
  DEALLOCATE(YD_STRUCT%SLEV)
ENDIF
YD_STRUCT%M_ORDER=0
YD_STRUCT%N_ORDER=0
YD_STRUCT%N_CMAX=0
YD_STRUCT%N_LEVELS=0
YD_STRUCT%IBETALEN_MAX=0
END SUBROUTINE FREE_BUTTERFLY
!====================================================================
END MODULE BUTTERFLY_ALG_DP_MOD
