#if defined CUDAGPU
#define ACC_GET_HIP_STREAM ACC_GET_CUDA_STREAM
#define OPENACC_LIB OPENACC
#endif

MODULE BUTTERFLY_GPU_DP_MOD

USE PARKIND_ECTRANS, ONLY: JPIM,JPIB,JPRBT
USE BUTTERFLY_ALG_DP_MOD, ONLY: BUTTERFLY_STRUCT,NODE_TYPE,BUTTERFLY_GPU_GROUPS,&
  & BUTTERFLY_GPU_PLAN,HYBRID_MATRIX,HYBRID_BLOCK,FREE_HYBRID,&
  & HYBRID_DENSE,HYBRID_LOW_RANK,HYBRID_BUTTERFLY

IMPLICIT NONE

PRIVATE
PUBLIC :: BUILD_GPU_BUTTERFLY_PLANS,FREE_GPU_BUTTERFLY_PLANS
PUBLIC :: APPLY_BUTTERFLY_INVERSE,APPLY_BUTTERFLY_DIRECT
PUBLIC :: BUTTERFLY_WORK_COLUMNS,BUTTERFLY_REQUESTED

REAL(KIND=JPRBT),PARAMETER :: ZERO=0.0_JPRBT,ONE=1.0_JPRBT

CONTAINS

LOGICAL FUNCTION BUTTERFLY_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY',ZVALUE,LENGTH=ILENGTH,&
  & STATUS=ISTATUS)
BUTTERFLY_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_REQUESTED

LOGICAL FUNCTION BUTTERFLY_VALIDATION_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_VALIDATE',ZVALUE,LENGTH=ILENGTH,&
  & STATUS=ISTATUS)
BUTTERFLY_VALIDATION_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_VALIDATION_REQUESTED

SUBROUTINE BUILD_GPU_BUTTERFLY_PLANS
USE TPM_FLT, ONLY: S
USE TPM_GEN, ONLY: NOUT
USE TPM_DISTR, ONLY: D
REAL :: ZRATIO
INTEGER(KIND=JPIM) :: JMLOC

CALL BUILD_ONE_PLAN(S%PLAN_A,.FALSE.)
CALL BUILD_ONE_PLAN(S%PLAN_S,.TRUE.)

WRITE(NOUT,'(A,L1,A,L1)') 'GPU butterfly requested=',BUTTERFLY_REQUESTED(),&
  & ' validation=',BUTTERFLY_VALIDATION_REQUESTED()
ZRATIO=1.0
IF (S%PLAN_A%DENSE_COST > 0) &
  ZRATIO=REAL(S%PLAN_A%HYBRID_COST)/REAL(S%PLAN_A%DENSE_COST)
WRITE(NOUT,'(A,L1,A,I0,A,I0,A,3(I0,1X),A,F7.4,A,I0)') &
  & 'GPU hybrid anti=',S%PLAN_A%ENABLED,' candidates=',S%PLAN_A%CANDIDATE_COUNT,&
  & ' selected=',S%PLAN_A%SELECTED_COUNT,' blocks(d/l/b)=',S%PLAN_A%DENSE_BLOCKS,&
  & S%PLAN_A%LOW_RANK_BLOCKS,S%PLAN_A%BUTTERFLY_BLOCKS,' cost_ratio=',ZRATIO,&
  & ' work_cols=',S%PLAN_A%WORK_COLS
ZRATIO=1.0
IF (S%PLAN_S%DENSE_COST > 0) &
  ZRATIO=REAL(S%PLAN_S%HYBRID_COST)/REAL(S%PLAN_S%DENSE_COST)
WRITE(NOUT,'(A,L1,A,I0,A,I0,A,3(I0,1X),A,F7.4,A,I0)') &
  & 'GPU hybrid sym =',S%PLAN_S%ENABLED,' candidates=',S%PLAN_S%CANDIDATE_COUNT,&
  & ' selected=',S%PLAN_S%SELECTED_COUNT,' blocks(d/l/b)=',S%PLAN_S%DENSE_BLOCKS,&
  & S%PLAN_S%LOW_RANK_BLOCKS,S%PLAN_S%BUTTERFLY_BLOCKS,' cost_ratio=',ZRATIO,&
  & ' work_cols=',S%PLAN_S%WORK_COLS
DO JMLOC=1,D%NUMP
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_A)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_S)
ENDDO
END SUBROUTINE BUILD_GPU_BUTTERFLY_PLANS

SUBROUTINE BUILD_ONE_PLAN(PLAN,LSYM)
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D

TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
LOGICAL,INTENT(IN) :: LSYM

INTEGER(KIND=JPIM) :: JMLOC,JL,I0,IFN,IDENSE
INTEGER(KIND=JPIM),ALLOCATABLE :: IFL(:),IFR(:),IRO(:),IRE(:)
INTEGER(KIND=JPIB) :: IPOS,IFACTORS,IBETA
LOGICAL :: LVALIDATE

ALLOCATE(PLAN%USE_HYBRID(D%NUMP))
PLAN%USE_HYBRID=.FALSE.
LVALIDATE=BUTTERFLY_VALIDATION_REQUESTED()

DO JMLOC=1,D%NUMP
  IF (LSYM) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_S,PLAN,JMLOC)
  ELSE
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_A,PLAN,JMLOC)
  ENDIF
ENDDO

IF (LVALIDATE) THEN
  CALL KEEP_BEST_MATRIX(PLAN)
ENDIF
PLAN%ENABLED=ANY(PLAN%USE_HYBRID)
IF (.NOT.PLAN%ENABLED) RETURN

IBETA=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_S,0,IBETA)
  ELSE
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_A,0,IBETA)
  ENDIF
ENDDO
PLAN%EVEN_BETA_COLS=IBETA
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_S,1,IBETA)
  ELSE
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_A,1,IBETA)
  ENDIF
ENDDO
PLAN%BETA_COLS=IBETA
PLAN%WORK_COLS=IBETA

IF (PLAN%MAX_LEVELS > 0) ALLOCATE(PLAN%LEVEL(1:PLAN%MAX_LEVELS))
IFACTORS=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LSYM) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_S,PLAN,IFACTORS)
  ELSE
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_A,PLAN,IFACTORS)
  ENDIF
ENDDO

CALL ALLOC_GROUP(PLAN%LEVEL0)
CALL ALLOC_GROUP(PLAN%FINAL)
CALL ALLOC_GROUP(PLAN%DENSE)
DO JL=1,PLAN%MAX_LEVELS
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%FWD_LEFT)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%FWD_RIGHT)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%REV_ODD)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
ALLOCATE(PLAN%FACTORS(IFACTORS))
PLAN%FACTORS=ZERO

ALLOCATE(IFL(PLAN%MAX_LEVELS),IFR(PLAN%MAX_LEVELS),&
  & IRO(PLAN%MAX_LEVELS),IRE(PLAN%MAX_LEVELS))
IFL=0
IFR=0
IRO=0
IRE=0
I0=0
IFN=0
IDENSE=0
IPOS=1
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LSYM) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_S,JMLOC,PLAN,IPOS,I0,IFN,&
      & IDENSE,IFL,IFR,IRO,IRE)
  ELSE
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_A,JMLOC,PLAN,IPOS,I0,IFN,&
      & IDENSE,IFL,IFR,IRO,IRE)
  ENDIF
ENDDO
DEALLOCATE(IFL,IFR,IRO,IRE)

#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(PLAN%FACTORS)
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:PLAN%FACTORS)
#endif
END SUBROUTINE BUILD_ONE_PLAN

SUBROUTINE SCAN_HYBRID(HYBRID,PLAN,KMLOC)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
INTEGER(KIND=JPIM) :: JB

IF (HYBRID%CONSTRUCTED) PLAN%CANDIDATE_COUNT=PLAN%CANDIDATE_COUNT+1
PLAN%USE_HYBRID(KMLOC)=HYBRID%SELECTED
IF (.NOT.HYBRID%SELECTED) RETURN
PLAN%SELECTED_COUNT=PLAN%SELECTED_COUNT+1
PLAN%DENSE_BLOCKS=PLAN%DENSE_BLOCKS+HYBRID%DENSE_BLOCKS
PLAN%LOW_RANK_BLOCKS=PLAN%LOW_RANK_BLOCKS+HYBRID%LOW_RANK_BLOCKS
PLAN%BUTTERFLY_BLOCKS=PLAN%BUTTERFLY_BLOCKS+HYBRID%BUTTERFLY_BLOCKS
PLAN%DENSE_COST=PLAN%DENSE_COST+HYBRID%DENSE_COST
PLAN%HYBRID_COST=PLAN%HYBRID_COST+HYBRID%HYBRID_COST
DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND /= HYBRID_DENSE) &
    PLAN%MAX_LEVELS=MAX(PLAN%MAX_LEVELS,HYBRID%BLOCKS(JB)%BUT%N_LEVELS)
ENDDO
END SUBROUTINE SCAN_HYBRID

SUBROUTINE KEEP_BEST_MATRIX(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JBEST,JMLOC

JBEST=0
DO JMLOC=1,SIZE(PLAN%USE_HYBRID)
  IF (PLAN%USE_HYBRID(JMLOC)) THEN
    JBEST=JMLOC
    EXIT
  ENDIF
ENDDO
PLAN%USE_HYBRID=.FALSE.
IF (JBEST > 0) PLAN%USE_HYBRID(JBEST)=.TRUE.
END SUBROUTINE KEEP_BEST_MATRIX

SUBROUTINE ASSIGN_WORK(HYBRID,KPARITY,KBASE)
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: HYBRID
INTEGER(KIND=JPIM),INTENT(IN) :: KPARITY
INTEGER(KIND=JPIB),INTENT(INOUT) :: KBASE
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) CYCLE
  IF (MOD(HYBRID%BLOCKS(JB)%BUT%N_LEVELS,2) /= KPARITY) CYCLE
  HYBRID%BLOCKS(JB)%WORK_BASE=KBASE
  KBASE=KBASE+HYBRID%BLOCKS(JB)%BUT%IBETALEN_MAX
ENDDO
END SUBROUTINE ASSIGN_WORK

SUBROUTINE COUNT_HYBRID(HYBRID,PLAN,KFACTORS)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) THEN
    PLAN%DENSE%COUNT=PLAN%DENSE%COUNT+1
    KFACTORS=KFACTORS+HYBRID%BLOCKS(JB)%DENSE_COST
  ELSE
    CALL COUNT_MATRIX(HYBRID%BLOCKS(JB)%BUT,PLAN,KFACTORS)
  ENDIF
ENDDO
END SUBROUTINE COUNT_HYBRID

SUBROUTINE COUNT_MATRIX(BUT,PLAN,KFACTORS)
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR
TYPE(NODE_TYPE),POINTER :: YNODE

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  PLAN%LEVEL0%COUNT=PLAN%LEVEL0%COUNT+1
  KFACTORS=KFACTORS+INT(YNODE%ICOLS,JPIB)*INT(YNODE%IRANK,JPIB)
ENDDO
DO JL=1,BUT%N_LEVELS
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
      IRANKL=BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)%IRANK
      IRANKR=0
      IF (2*JK <= BUT%SLEV(JL-1)%IK) &
        IRANKR=BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)%IRANK
      PLAN%LEVEL(JL)%FWD_LEFT%COUNT=PLAN%LEVEL(JL)%FWD_LEFT%COUNT+1
      IF (IRANKR > 0) PLAN%LEVEL(JL)%FWD_RIGHT%COUNT=&
        & PLAN%LEVEL(JL)%FWD_RIGHT%COUNT+1
      IF (MOD(JJ,2) == 1) THEN
        PLAN%LEVEL(JL)%REV_ODD%COUNT=PLAN%LEVEL(JL)%REV_ODD%COUNT+1
        IF (IRANKR > 0) PLAN%LEVEL(JL)%REV_ODD%COUNT=&
          & PLAN%LEVEL(JL)%REV_ODD%COUNT+1
      ELSE
        PLAN%LEVEL(JL)%REV_EVEN%COUNT=PLAN%LEVEL(JL)%REV_EVEN%COUNT+1
        IF (IRANKR > 0) PLAN%LEVEL(JL)%REV_EVEN%COUNT=&
          & PLAN%LEVEL(JL)%REV_EVEN%COUNT+1
      ENDIF
      KFACTORS=KFACTORS+INT(IRANKL+IRANKR,JPIB)*INT(YNODE%IRANK,JPIB)
    ENDDO
  ENDDO
ENDDO
JL=BUT%N_LEVELS
DO JK=1,BUT%SLEV(JL)%IK
  DO JJ=1,BUT%SLEV(JL)%IJ
    YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
    PLAN%FINAL%COUNT=PLAN%FINAL%COUNT+1
    KFACTORS=KFACTORS+INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
  ENDDO
ENDDO
END SUBROUTINE COUNT_MATRIX

SUBROUTINE ALLOC_GROUP(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ALLOCATE(GROUP%N(GROUP%COUNT),GROUP%K(GROUP%COUNT),GROUP%LDB(GROUP%COUNT))
ALLOCATE(GROUP%SRC_COL(GROUP%COUNT),GROUP%DST_COL(GROUP%COUNT),&
  & GROUP%FACTOR_OFFSET(GROUP%COUNT))
END SUBROUTINE ALLOC_GROUP

SUBROUTINE SET_GROUP(GROUP,KI,KN,KK,KLDB,KSRC,KDST,KFACTOR)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KN,KK,KLDB
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC,KDST,KFACTOR
GROUP%N(KI)=KN
GROUP%K(KI)=KK
GROUP%LDB(KI)=KLDB
GROUP%SRC_COL(KI)=KSRC
GROUP%DST_COL(KI)=KDST
GROUP%FACTOR_OFFSET(KI)=KFACTOR
END SUBROUTINE SET_GROUP

SUBROUTINE FILL_HYBRID(HYBRID,KMLOC,PLAN,KPOS,K0,KFINAL,KDENSE,KFL,KFR,KRO,KRE)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K0,KFINAL,KDENSE,KFL(:),KFR(:),KRO(:),KRE(:)
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) THEN
    CALL FILL_DENSE(HYBRID%BLOCKS(JB),KMLOC,PLAN,KPOS,KDENSE)
  ELSE
    CALL FILL_MATRIX(HYBRID%BLOCKS(JB)%BUT,KMLOC,&
      & HYBRID%BLOCKS(JB)%FIRST_ROW,HYBRID%BLOCKS(JB)%FIRST_COL,&
      & HYBRID%BLOCKS(JB)%WORK_BASE,PLAN,KPOS,K0,KFINAL,KFL,KFR,KRO,KRE)
  ENDIF
ENDDO
END SUBROUTINE FILL_HYBRID

SUBROUTINE FILL_DENSE(BLOCK,KMLOC,PLAN,KPOS,KDENSE)
USE TPM_DISTR, ONLY: D
TYPE(HYBRID_BLOCK),INTENT(IN) :: BLOCK
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(INOUT) :: KDENSE
INTEGER(KIND=JPIB) :: IOFF
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)

ALLOCATE(ZT(BLOCK%NCOLS,BLOCK%NROWS))
ZT=TRANSPOSE(BLOCK%DENSE)
IOFF=KPOS-1
PLAN%FACTORS(KPOS:KPOS+BLOCK%DENSE_COST-1)=RESHAPE(ZT,[BLOCK%DENSE_COST])
KPOS=KPOS+BLOCK%DENSE_COST
KDENSE=KDENSE+1
CALL SET_GROUP(PLAN%DENSE,KDENSE,BLOCK%NROWS,BLOCK%NCOLS,BLOCK%NCOLS,&
  & D%OFFSETS_GEMM2(KMLOC)+BLOCK%FIRST_COL-1,&
  & D%OFFSETS_GEMM1(KMLOC)+BLOCK%FIRST_ROW-1,IOFF)
DEALLOCATE(ZT)
END SUBROUTINE FILL_DENSE

SUBROUTINE FILL_MATRIX(BUT,KMLOC,KFIRST_ROW,KFIRST_COL,KWORK_BASE,&
  & PLAN,KPOS,K0,KFINAL,KFL,KFR,KRO,KRE)
USE TPM_DISTR, ONLY: D
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC,KFIRST_ROW,KFIRST_COL
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K0,KFINAL,KFL(:),KFR(:),KRO(:),KRE(:)
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR
INTEGER(KIND=JPIB) :: IOFF,IOFFL,IOFFR,ISRC,IDST
TYPE(NODE_TYPE),POINTER :: YNODE,YLEFT,YRIGHT

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  CALL PACK_PROJECTION(YNODE,PLAN%FACTORS,KPOS,IOFF)
  K0=K0+1
  ISRC=D%OFFSETS_GEMM2(KMLOC)+KFIRST_COL+YNODE%IFCOL-2
  IDST=KWORK_BASE+YNODE%IOFFBETA
  CALL SET_GROUP(PLAN%LEVEL0,K0,YNODE%IRANK,YNODE%ICOLS,YNODE%ICOLS,&
    & ISRC,IDST,IOFF)
ENDDO

DO JL=1,BUT%N_LEVELS
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
      YLEFT=>BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)
      IRANKL=YLEFT%IRANK
      IRANKR=0
      IF (2*JK <= BUT%SLEV(JL-1)%IK) THEN
        YRIGHT=>BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)
        IRANKR=YRIGHT%IRANK
      ENDIF
      CALL PACK_SPLIT_PROJECTION(YNODE,IRANKL,IRANKR,PLAN%FACTORS,KPOS,IOFFL,IOFFR)
      ISRC=KWORK_BASE+YLEFT%IOFFBETA
      IDST=KWORK_BASE+YNODE%IOFFBETA
      KFL(JL)=KFL(JL)+1
      CALL SET_GROUP(PLAN%LEVEL(JL)%FWD_LEFT,KFL(JL),YNODE%IRANK,IRANKL,IRANKL,&
        & ISRC,IDST,IOFFL)
      IF (IRANKR > 0) THEN
        ISRC=KWORK_BASE+YRIGHT%IOFFBETA
        KFR(JL)=KFR(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%FWD_RIGHT,KFR(JL),YNODE%IRANK,IRANKR,IRANKR,&
          & ISRC,IDST,IOFFR)
      ENDIF
      IF (MOD(JJ,2) == 1) THEN
        KRO(JL)=KRO(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%REV_ODD,KRO(JL),YNODE%IRANK,IRANKL,IRANKL,&
          & KWORK_BASE+YLEFT%IOFFBETA,IDST,IOFFL)
        IF (IRANKR > 0) THEN
          KRO(JL)=KRO(JL)+1
          CALL SET_GROUP(PLAN%LEVEL(JL)%REV_ODD,KRO(JL),YNODE%IRANK,IRANKR,IRANKR,&
            & KWORK_BASE+YRIGHT%IOFFBETA,IDST,IOFFR)
        ENDIF
      ELSE
        KRE(JL)=KRE(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%REV_EVEN,KRE(JL),YNODE%IRANK,IRANKL,IRANKL,&
          & KWORK_BASE+YLEFT%IOFFBETA,IDST,IOFFL)
        IF (IRANKR > 0) THEN
          KRE(JL)=KRE(JL)+1
          CALL SET_GROUP(PLAN%LEVEL(JL)%REV_EVEN,KRE(JL),YNODE%IRANK,IRANKR,IRANKR,&
            & KWORK_BASE+YRIGHT%IOFFBETA,IDST,IOFFR)
        ENDIF
      ENDIF
    ENDDO
  ENDDO
ENDDO

JL=BUT%N_LEVELS
DO JK=1,BUT%SLEV(JL)%IK
  DO JJ=1,BUT%SLEV(JL)%IJ
    YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
    IOFF=KPOS-1
    PLAN%FACTORS(KPOS:KPOS+INT(YNODE%IROWS,JPIB)*YNODE%IRANK-1)=&
      & RESHAPE(REAL(YNODE%B,JPRBT),[YNODE%IROWS*YNODE%IRANK])
    KPOS=KPOS+INT(YNODE%IROWS,JPIB)*YNODE%IRANK
    KFINAL=KFINAL+1
    CALL SET_GROUP(PLAN%FINAL,KFINAL,YNODE%IROWS,YNODE%IRANK,YNODE%IROWS,&
      & KWORK_BASE+YNODE%IOFFBETA,&
      & D%OFFSETS_GEMM1(KMLOC)+KFIRST_ROW+YNODE%IFROW-2,IOFF)
  ENDDO
ENDDO
END SUBROUTINE FILL_MATRIX

SUBROUTINE PACK_PROJECTION(NODE,PFACTORS,KPOS,KOFFSET)
TYPE(NODE_TYPE),INTENT(IN) :: NODE
REAL(KIND=JPRBT),INTENT(INOUT) :: PFACTORS(:)
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIB),INTENT(OUT) :: KOFFSET
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)
INTEGER(KIND=JPIM) :: JI,JR,IC

ALLOCATE(ZT(NODE%ICOLS,NODE%IRANK))
ZT=ZERO
DO JI=1,NODE%ICOLS
  IC=NODE%ICLIST(JI)
  IF (JI <= NODE%IRANK) THEN
    ZT(IC,JI)=ONE
  ELSE
    DO JR=1,NODE%IRANK
      ZT(IC,JR)=NODE%PNONIM((JI-NODE%IRANK-1)*NODE%IRANK+JR)
    ENDDO
  ENDIF
ENDDO
KOFFSET=KPOS-1
PFACTORS(KPOS:KPOS+INT(NODE%ICOLS,JPIB)*NODE%IRANK-1)=&
  & RESHAPE(ZT,[NODE%ICOLS*NODE%IRANK])
KPOS=KPOS+INT(NODE%ICOLS,JPIB)*NODE%IRANK
DEALLOCATE(ZT)
END SUBROUTINE PACK_PROJECTION

SUBROUTINE PACK_SPLIT_PROJECTION(NODE,KRANKL,KRANKR,PFACTORS,KPOS,KOFFL,KOFFR)
TYPE(NODE_TYPE),INTENT(IN) :: NODE
INTEGER(KIND=JPIM),INTENT(IN) :: KRANKL,KRANKR
REAL(KIND=JPRBT),INTENT(INOUT) :: PFACTORS(:)
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIB),INTENT(OUT) :: KOFFL,KOFFR
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)
INTEGER(KIND=JPIM) :: JI,JR,IC

ALLOCATE(ZT(KRANKL+KRANKR,NODE%IRANK))
ZT=ZERO
DO JI=1,NODE%ICOLS
  IC=NODE%ICLIST(JI)
  IF (JI <= NODE%IRANK) THEN
    ZT(IC,JI)=ONE
  ELSE
    DO JR=1,NODE%IRANK
      ZT(IC,JR)=NODE%PNONIM((JI-NODE%IRANK-1)*NODE%IRANK+JR)
    ENDDO
  ENDIF
ENDDO
KOFFL=KPOS-1
PFACTORS(KPOS:KPOS+INT(KRANKL,JPIB)*NODE%IRANK-1)=&
  & RESHAPE(ZT(1:KRANKL,:),[KRANKL*NODE%IRANK])
KPOS=KPOS+INT(KRANKL,JPIB)*NODE%IRANK
KOFFR=KPOS-1
IF (KRANKR > 0) THEN
  PFACTORS(KPOS:KPOS+INT(KRANKR,JPIB)*NODE%IRANK-1)=&
    & RESHAPE(ZT(KRANKL+1:KRANKL+KRANKR,:),[KRANKR*NODE%IRANK])
  KPOS=KPOS+INT(KRANKR,JPIB)*NODE%IRANK
ENDIF
DEALLOCATE(ZT)
END SUBROUTINE PACK_SPLIT_PROJECTION

FUNCTION BUTTERFLY_WORK_COLUMNS() RESULT(KCOLS)
USE TPM_FLT, ONLY: S
INTEGER(KIND=JPIB) :: KCOLS
KCOLS=MAX(S%PLAN_A%WORK_COLS,S%PLAN_S%WORK_COLS)
END FUNCTION BUTTERFLY_WORK_COLUMNS

SUBROUTINE APPLY_BUTTERFLY_INVERSE(PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PIN(:),POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KIN_BASE,KOUT_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

CALL ZERO_COLUMNS(POUT,KLD,KOUT_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .FALSE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE-1,ALLOCATOR,.TRUE.)
CALL RUN_GROUP(PLAN%LEVEL0,PLAN,PIN,POUT,KLD,0_JPIB,KOUT_BASE,&
  & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE,ALLOCATOR)
DO JL=1,PLAN%MAX_LEVELS
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_GROUP(PLAN%LEVEL(JL)%FWD_LEFT,PLAN,POUT,PIN,KLD,KOUT_BASE,KIN_BASE,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+2*JL-1,ALLOCATOR)
    CALL RUN_GROUP(PLAN%LEVEL(JL)%FWD_RIGHT,PLAN,POUT,PIN,KLD,KOUT_BASE,KIN_BASE,&
      & .FALSE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+2*JL,ALLOCATOR)
  ELSE
    CALL RUN_GROUP(PLAN%LEVEL(JL)%FWD_LEFT,PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+2*JL-1,ALLOCATOR)
    CALL RUN_GROUP(PLAN%LEVEL(JL)%FWD_RIGHT,PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
      & .FALSE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+2*JL,ALLOCATOR)
  ENDIF
ENDDO
CALL COPY_COLUMNS(POUT,PIN,KLD,KOUT_BASE,KIN_BASE,0_JPIB,&
  & PLAN%EVEN_BETA_COLS,KASYNC)
CALL RUN_GROUP(PLAN%FINAL,PLAN,PIN,POUT,KLD,KIN_BASE,0_JPIB,&
  & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
END SUBROUTINE APPLY_BUTTERFLY_INVERSE

SUBROUTINE APPLY_BUTTERFLY_DIRECT(PLAN,PIN,POUT,KLD,KWORK_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

CALL ZERO_COLUMNS(POUT,KLD,KWORK_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+39,ALLOCATOR,.TRUE.)
CALL RUN_GROUP(PLAN%FINAL,PLAN,PIN,POUT,KLD,0_JPIB,KWORK_BASE,&
  & .TRUE.,.TRUE.,ZERO,ISTREAM,KBLAS_BASE+40,ALLOCATOR)
CALL COPY_COLUMNS_INPLACE(POUT,KLD,KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
  & PLAN%EVEN_BETA_COLS,&
  & PLAN%BETA_COLS-PLAN%EVEN_BETA_COLS,KASYNC)
DO JL=PLAN%MAX_LEVELS,1,-1
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_GROUP(PLAN%LEVEL(JL)%REV_ODD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,&
      & .TRUE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+40+2*JL-1,ALLOCATOR)
    CALL RUN_GROUP(PLAN%LEVEL(JL)%REV_EVEN,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,&
      & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+40+2*JL,ALLOCATOR)
  ELSE
    CALL RUN_GROUP(PLAN%LEVEL(JL)%REV_ODD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+40+2*JL-1,ALLOCATOR)
    CALL RUN_GROUP(PLAN%LEVEL(JL)%REV_EVEN,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+40+2*JL,ALLOCATOR)
  ENDIF
ENDDO
CALL RUN_GROUP(PLAN%LEVEL0,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
  & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+70,ALLOCATOR,.TRUE.)
END SUBROUTINE APPLY_BUTTERFLY_DIRECT

SUBROUTINE ZERO_COLUMNS(PBUF,KLD,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KCOUNT
INTEGER(KIND=JPIB) :: J,JEND

JEND=INT(KLD,JPIB)*KCOUNT
IF (JEND <= 0) RETURN
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JEND) MAP(PRESENT:PBUF)
#endif
DO J=1,JEND
  PBUF(J)=ZERO
ENDDO
END SUBROUTINE ZERO_COLUMNS

SUBROUTINE COPY_COLUMNS(PSRC,PDST,KLD,KSRC_BASE,KDST_BASE,KFIRST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PSRC(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PDST(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KFIRST,KCOUNT
INTEGER(KIND=JPIB) :: J,JSTART,JEND
IF (KCOUNT <= 0) RETURN
JSTART=KFIRST*KLD+1
JEND=(KFIRST+KCOUNT)*KLD
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PSRC,PDST) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JSTART,JEND) MAP(PRESENT:PSRC,PDST)
#endif
DO J=JSTART,JEND
  PDST(KDST_BASE*KLD+J)=PSRC(KSRC_BASE*KLD+J)
ENDDO
END SUBROUTINE COPY_COLUMNS

SUBROUTINE COPY_COLUMNS_INPLACE(PBUF,KLD,KSRC_BASE,KDST_BASE,KFIRST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KFIRST,KCOUNT
INTEGER(KIND=JPIB) :: J,JSTART,JEND
IF (KCOUNT <= 0) RETURN
JSTART=KFIRST*KLD+1
JEND=(KFIRST+KCOUNT)*KLD
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JSTART,JEND) MAP(PRESENT:PBUF)
#endif
DO J=JSTART,JEND
  PBUF(KDST_BASE*KLD+J)=PBUF(KSRC_BASE*KLD+J)
ENDDO
END SUBROUTINE COPY_COLUMNS_INPLACE

SUBROUTINE RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
  & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
USE HICBLAS_MOD, ONLY: HIP_DGEMM_GROUPED_ASYNC,HIP_SGEMM_GROUPED_ASYNC,&
  & HIP_DGEMM_GROUPED_ORDERED_ASYNC
USE TPM_GEN, ONLY: NCUR_RESOL
USE ISO_C_BINDING, ONLY: C_LOC,C_INTPTR_T
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PA(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PC(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KBLAS
INTEGER(KIND=JPIB),INTENT(IN) :: KADD_A,KADD_C
LOGICAL,INTENT(IN) :: LREVERSE,LFACTOR_TRANSPOSED
REAL(KIND=JPRBT),INTENT(IN) :: PBETA
INTEGER(C_INTPTR_T),INTENT(IN) :: KSTREAM
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
LOGICAL,INTENT(IN),OPTIONAL :: LORDERED
INTEGER(KIND=JPIM) :: IN(GROUP%COUNT),IK(GROUP%COUNT)
INTEGER(KIND=JPIB) :: IOFFA(GROUP%COUNT),IOFFC(GROUP%COUNT)
CHARACTER(LEN=1) :: CTB
LOGICAL :: LLORDERED

IF (GROUP%COUNT <= 0) RETURN
LLORDERED=.FALSE.
IF (PRESENT(LORDERED)) LLORDERED=LORDERED
IF (LREVERSE) THEN
  IN=GROUP%K
  IK=GROUP%N
  IOFFA=(GROUP%DST_COL+KADD_A)*KLD
  IOFFC=(GROUP%SRC_COL+KADD_C)*KLD
  IF (LFACTOR_TRANSPOSED) THEN
    CTB='N'
  ELSE
    CTB='T'
  ENDIF
ELSE
  IN=GROUP%N
  IK=GROUP%K
  IOFFA=(GROUP%SRC_COL+KADD_A)*KLD
  IOFFC=(GROUP%DST_COL+KADD_C)*KLD
  IF (LFACTOR_TRANSPOSED) THEN
    CTB='T'
  ELSE
    CTB='N'
  ENDIF
ENDIF

ASSOCIATE(PFACTORS=>PLAN%FACTORS)
#ifdef OMPGPU
!$OMP TARGET DATA USE_DEVICE_ADDR(PA,PFACTORS,PC)
#endif
#ifdef ACCGPU
!$ACC HOST_DATA USE_DEVICE(PA,PFACTORS,PC)
#endif
#ifdef TRANS_SINGLE
CALL HIP_SGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
  & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
  & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
#else
IF (LLORDERED) THEN
  CALL HIP_DGEMM_GROUPED_ORDERED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
    & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
    & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
ELSE
  CALL HIP_DGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
    & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
    & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
ENDIF
#endif
#ifdef ACCGPU
!$ACC END HOST_DATA
#endif
#ifdef OMPGPU
!$OMP END TARGET DATA
#endif
END ASSOCIATE
END SUBROUTINE RUN_GROUP

SUBROUTINE FREE_GPU_BUTTERFLY_PLANS
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D
INTEGER(KIND=JPIM) :: JMLOC

CALL FREE_ONE_PLAN(S%PLAN_A)
CALL FREE_ONE_PLAN(S%PLAN_S)
IF (ALLOCATED(S%FA)) THEN
  DO JMLOC=1,D%NUMP
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_A)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_S)
  ENDDO
ENDIF
END SUBROUTINE FREE_GPU_BUTTERFLY_PLANS

SUBROUTINE FREE_ONE_PLAN(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JL
#ifdef ACCGPU
!$ACC EXIT DATA DELETE(PLAN%FACTORS) IF(ASSOCIATED(PLAN%FACTORS))
#endif
#ifdef OMPGPU
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%FACTORS) IF(ASSOCIATED(PLAN%FACTORS))
#endif
CALL FREE_GROUP(PLAN%LEVEL0)
CALL FREE_GROUP(PLAN%FINAL)
CALL FREE_GROUP(PLAN%DENSE)
IF (ALLOCATED(PLAN%LEVEL)) THEN
  DO JL=1,SIZE(PLAN%LEVEL)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%FWD_LEFT)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%FWD_RIGHT)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%REV_ODD)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%REV_EVEN)
  ENDDO
  DEALLOCATE(PLAN%LEVEL)
ENDIF
IF (ASSOCIATED(PLAN%FACTORS)) DEALLOCATE(PLAN%FACTORS)
IF (ALLOCATED(PLAN%USE_HYBRID)) DEALLOCATE(PLAN%USE_HYBRID)
PLAN%ENABLED=.FALSE.
PLAN%MAX_LEVELS=0
PLAN%CANDIDATE_COUNT=0
PLAN%SELECTED_COUNT=0
PLAN%DENSE_BLOCKS=0
PLAN%LOW_RANK_BLOCKS=0
PLAN%BUTTERFLY_BLOCKS=0
PLAN%BETA_COLS=0
PLAN%EVEN_BETA_COLS=0
PLAN%WORK_COLS=0
PLAN%DENSE_COST=0
PLAN%HYBRID_COST=0
END SUBROUTINE FREE_ONE_PLAN

SUBROUTINE FREE_GROUP(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
IF (ALLOCATED(GROUP%N)) DEALLOCATE(GROUP%N)
IF (ALLOCATED(GROUP%K)) DEALLOCATE(GROUP%K)
IF (ALLOCATED(GROUP%LDB)) DEALLOCATE(GROUP%LDB)
IF (ALLOCATED(GROUP%SRC_COL)) DEALLOCATE(GROUP%SRC_COL)
IF (ALLOCATED(GROUP%DST_COL)) DEALLOCATE(GROUP%DST_COL)
IF (ALLOCATED(GROUP%FACTOR_OFFSET)) DEALLOCATE(GROUP%FACTOR_OFFSET)
GROUP%COUNT=0
END SUBROUTINE FREE_GROUP

END MODULE BUTTERFLY_GPU_DP_MOD
