#if defined CUDAGPU
#define ACC_GET_HIP_STREAM ACC_GET_CUDA_STREAM
#define OPENACC_LIB OPENACC
#endif

MODULE BUTTERFLY_GPU_DP_MOD

USE PARKIND_ECTRANS, ONLY: JPIM,JPIB,JPRBT,JPRD
USE BUTTERFLY_ALG_DP_MOD, ONLY: BUTTERFLY_STRUCT,NODE_TYPE,BUTTERFLY_GPU_GROUPS,&
  & BUTTERFLY_GPU_PLAN,HYBRID_MATRIX,HYBRID_BLOCK,FREE_HYBRID,&
  & HYBRID_DENSE,HYBRID_LOW_RANK,HYBRID_BUTTERFLY
USE INTERPOL_DECOMP_MOD, ONLY: COMPUTE_ID

IMPLICIT NONE

PRIVATE
PUBLIC :: BUILD_GPU_BUTTERFLY_PLANS,FREE_GPU_BUTTERFLY_PLANS
PUBLIC :: APPLY_BUTTERFLY_INVERSE,APPLY_BUTTERFLY_DIRECT,&
  & APPLY_BUTTERFLY_DIRECT_FORWARD
PUBLIC :: BUTTERFLY_WORK_COLUMNS,BUTTERFLY_REQUESTED,BUTTERFLY_DIRECT_REQUESTED,&
  & BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED

REAL(KIND=JPRBT),PARAMETER :: ZERO=0.0_JPRBT,ONE=1.0_JPRBT

#ifdef CUDAGPU
INTERFACE
SUBROUTINE BUTTERFLY_PROJECTION_C(PIN,POUT,KLD,KN,KK,KSRC,KDST,KFACTOR,&
  & KPIVOT,KTILE_GROUP,KTILE_START,KPIVOTS,PFACTORS,KADD_A,KADD_C,&
  & KNTILES,KREVERSE,PBETA,KSTREAM) &
  & BIND(C,NAME='ectrans_butterfly_projection_cuda')
USE ISO_C_BINDING, ONLY: C_PTR,C_INT,C_INT64_T,C_DOUBLE,C_INTPTR_T
TYPE(C_PTR),VALUE :: PIN,POUT,PFACTORS
INTEGER(C_INT),INTENT(IN) :: KN(*),KK(*),KTILE_GROUP(*),KTILE_START(*),KPIVOTS(*)
INTEGER(C_INT64_T),INTENT(IN) :: KSRC(*),KDST(*),KFACTOR(*),KPIVOT(*)
INTEGER(C_INT64_T),VALUE :: KADD_A,KADD_C
INTEGER(C_INT),VALUE :: KLD,KNTILES,KREVERSE
REAL(C_DOUBLE),VALUE :: PBETA
INTEGER(C_INTPTR_T),VALUE :: KSTREAM
END SUBROUTINE BUTTERFLY_PROJECTION_C
END INTERFACE
#endif

CONTAINS

LOGICAL FUNCTION BUTTERFLY_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY',ZVALUE,LENGTH=ILENGTH,&
  & STATUS=ISTATUS)
BUTTERFLY_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_REQUESTED

LOGICAL FUNCTION BUTTERFLY_DIRECT_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_DIRECT',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_DIRECT_REQUESTED=ISTATUS /= 0 .OR. ILENGTH == 0 .OR. ZVALUE(1:1) /= '0'
END FUNCTION BUTTERFLY_DIRECT_REQUESTED

LOGICAL FUNCTION BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_TRANSPOSE_DIRECT',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#ifdef CUDAGPU
IF (BUTTERFLY_COMPACT_ID_REQUESTED()) BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED=.TRUE.
#endif
END FUNCTION BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED

LOGICAL FUNCTION BUTTERFLY_INVERSE_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_INVERSE',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_INVERSE_REQUESTED=ISTATUS /= 0 .OR. ILENGTH == 0 .OR. &
  & ZVALUE(1:1) /= '0'
END FUNCTION BUTTERFLY_INVERSE_REQUESTED

LOGICAL FUNCTION BUTTERFLY_FUSE_FINAL_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FUSE_FINAL',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_FUSE_FINAL_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_FUSE_FINAL_REQUESTED

LOGICAL FUNCTION BUTTERFLY_RECOMPRESS_FINAL_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_RECOMPRESS_FINAL',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_RECOMPRESS_FINAL_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_RECOMPRESS_FINAL_REQUESTED

REAL(KIND=JPRD) FUNCTION BUTTERFLY_FINAL_EPS()
CHARACTER(LEN=32) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
BUTTERFLY_FINAL_EPS=1.0E-14_JPRD
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FINAL_EPS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
  READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) BUTTERFLY_FINAL_EPS
  IF (ISTATUS /= 0 .OR. BUTTERFLY_FINAL_EPS <= 0.0_JPRD) &
    & BUTTERFLY_FINAL_EPS=1.0E-14_JPRD
ENDIF
END FUNCTION BUTTERFLY_FINAL_EPS

REAL(KIND=JPRD) FUNCTION BUTTERFLY_FINAL_SELECT_RATIO()
CHARACTER(LEN=32) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
BUTTERFLY_FINAL_SELECT_RATIO=0.8_JPRD
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FINAL_SELECT_RATIO',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
  READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) BUTTERFLY_FINAL_SELECT_RATIO
  IF (ISTATUS /= 0 .OR. BUTTERFLY_FINAL_SELECT_RATIO <= 0.0_JPRD .OR. &
    & BUTTERFLY_FINAL_SELECT_RATIO >= 1.0_JPRD) &
    & BUTTERFLY_FINAL_SELECT_RATIO=0.8_JPRD
ENDIF
END FUNCTION BUTTERFLY_FINAL_SELECT_RATIO

LOGICAL FUNCTION BUTTERFLY_VALIDATION_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_VALIDATE',ZVALUE,LENGTH=ILENGTH,&
  & STATUS=ISTATUS)
BUTTERFLY_VALIDATION_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_VALIDATION_REQUESTED

LOGICAL FUNCTION BUTTERFLY_COMPACT_ID_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
#ifdef CUDAGPU
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_COMPACT_ID',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_COMPACT_ID_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#else
BUTTERFLY_COMPACT_ID_REQUESTED=.FALSE.
#endif
END FUNCTION BUTTERFLY_COMPACT_ID_REQUESTED

SUBROUTINE BUILD_GPU_BUTTERFLY_PLANS
USE TPM_FLT, ONLY: S
USE TPM_GEN, ONLY: NOUT
USE TPM_DISTR, ONLY: D
REAL :: ZRATIO
INTEGER(KIND=JPIM) :: JMLOC

IF (BUTTERFLY_INVERSE_REQUESTED()) THEN
  CALL BUILD_ONE_PLAN(S%PLAN_A,.FALSE.,.FALSE.)
  CALL BUILD_ONE_PLAN(S%PLAN_S,.TRUE.,.FALSE.)
ENDIF
IF (BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED()) THEN
  CALL BUILD_ONE_PLAN(S%PLAN_DIRECT_A,.FALSE.,.TRUE.)
  CALL BUILD_ONE_PLAN(S%PLAN_DIRECT_S,.TRUE.,.TRUE.)
ENDIF

WRITE(NOUT,'(A,L1,A,L1)') 'GPU butterfly requested=',BUTTERFLY_REQUESTED(),&
  & ' validation=',BUTTERFLY_VALIDATION_REQUESTED()
ZRATIO=1.0
IF (S%PLAN_A%DENSE_COST > 0) &
  ZRATIO=REAL(S%PLAN_A%HYBRID_COST)/REAL(S%PLAN_A%DENSE_COST)
WRITE(NOUT,'(A,L1,A,I0,A,I0,A,3(I0,1X),A,F7.4,A,I0)') &
  & 'GPU hybrid anti=',S%PLAN_A%ENABLED,' candidates=',S%PLAN_A%CANDIDATE_COUNT,&
  & ' selected=',S%PLAN_A%SELECTED_COUNT,' blocks(d/l/b)=',S%PLAN_A%DENSE_BLOCKS,&
  & S%PLAN_A%LOW_RANK_BLOCKS,S%PLAN_A%BUTTERFLY_BLOCKS,' cost_ratio=',ZRATIO,&
  & ' work_cols=',S%PLAN_A%WORK_COLS
ZRATIO=1.0
IF (S%PLAN_S%DENSE_COST > 0) &
  ZRATIO=REAL(S%PLAN_S%HYBRID_COST)/REAL(S%PLAN_S%DENSE_COST)
WRITE(NOUT,'(A,L1,A,I0,A,I0,A,3(I0,1X),A,F7.4,A,I0)') &
  & 'GPU hybrid sym =',S%PLAN_S%ENABLED,' candidates=',S%PLAN_S%CANDIDATE_COUNT,&
  & ' selected=',S%PLAN_S%SELECTED_COUNT,' blocks(d/l/b)=',S%PLAN_S%DENSE_BLOCKS,&
  & S%PLAN_S%LOW_RANK_BLOCKS,S%PLAN_S%BUTTERFLY_BLOCKS,' cost_ratio=',ZRATIO,&
  & ' work_cols=',S%PLAN_S%WORK_COLS
IF (BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED()) THEN
  ZRATIO=1.0
  IF (S%PLAN_DIRECT_A%DENSE_COST > 0) &
    ZRATIO=REAL(S%PLAN_DIRECT_A%HYBRID_COST)/REAL(S%PLAN_DIRECT_A%DENSE_COST)
  WRITE(NOUT,'(A,L1,A,I0,A,I0,A,F7.4,A,I0,A,I0,A,I0,A,I0,A,F7.4)') &
    & 'GPU transpose direct anti=',S%PLAN_DIRECT_A%ENABLED,&
    & ' candidates=',S%PLAN_DIRECT_A%CANDIDATE_COUNT,&
    & ' selected=',S%PLAN_DIRECT_A%SELECTED_COUNT,' cost_ratio=',ZRATIO,&
    & ' work_cols=',S%PLAN_DIRECT_A%WORK_COLS,&
    & ' final=',S%PLAN_DIRECT_A%FINAL%COUNT,&
    & ' fused_final=',S%PLAN_DIRECT_A%FINAL_FUSED%COUNT,&
    & ' recompressed=',S%PLAN_DIRECT_A%FINAL_RECOMPRESSED_GROUPS,&
    & ' final_cost_ratio=',REAL(S%PLAN_DIRECT_A%FINAL_EXEC_COST,JPRD)/&
    & REAL(MAX(1_JPIB,S%PLAN_DIRECT_A%FINAL_ORIGINAL_COST),JPRD)
  ZRATIO=1.0
  IF (S%PLAN_DIRECT_S%DENSE_COST > 0) &
    ZRATIO=REAL(S%PLAN_DIRECT_S%HYBRID_COST)/REAL(S%PLAN_DIRECT_S%DENSE_COST)
  WRITE(NOUT,'(A,L1,A,I0,A,I0,A,F7.4,A,I0,A,I0,A,I0,A,I0,A,F7.4)') &
    & 'GPU transpose direct sym =',S%PLAN_DIRECT_S%ENABLED,&
    & ' candidates=',S%PLAN_DIRECT_S%CANDIDATE_COUNT,&
    & ' selected=',S%PLAN_DIRECT_S%SELECTED_COUNT,' cost_ratio=',ZRATIO,&
    & ' work_cols=',S%PLAN_DIRECT_S%WORK_COLS,&
    & ' final=',S%PLAN_DIRECT_S%FINAL%COUNT,&
    & ' fused_final=',S%PLAN_DIRECT_S%FINAL_FUSED%COUNT,&
    & ' recompressed=',S%PLAN_DIRECT_S%FINAL_RECOMPRESSED_GROUPS,&
    & ' final_cost_ratio=',REAL(S%PLAN_DIRECT_S%FINAL_EXEC_COST,JPRD)/&
    & REAL(MAX(1_JPIB,S%PLAN_DIRECT_S%FINAL_ORIGINAL_COST),JPRD)
ENDIF
DO JMLOC=1,D%NUMP
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_A)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_S)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S)
ENDDO
END SUBROUTINE BUILD_GPU_BUTTERFLY_PLANS

SUBROUTINE BUILD_ONE_PLAN(PLAN,LSYM,LDIRECT)
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D

TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
LOGICAL,INTENT(IN) :: LSYM
LOGICAL,INTENT(IN) :: LDIRECT

INTEGER(KIND=JPIM) :: JMLOC,JL,I0,IFN,IDENSE
INTEGER(KIND=JPIM),ALLOCATABLE :: IFW(:),IRO(:),IRE(:)
INTEGER(KIND=JPIB) :: IPOS,IFACTORS,IFACTORS_ALLOC,IBETA,IPIVOTS,IPIVOT_POS
LOGICAL :: LVALIDATE

ALLOCATE(PLAN%USE_HYBRID(D%NUMP))
PLAN%USE_HYBRID=.FALSE.
LVALIDATE=BUTTERFLY_VALIDATION_REQUESTED()
PLAN%COMPACT_ID=BUTTERFLY_COMPACT_ID_REQUESTED()
PLAN%FUSE_FINAL=LDIRECT .AND. BUTTERFLY_FUSE_FINAL_REQUESTED()
PLAN%RECOMPRESS_FINAL=LDIRECT .AND. BUTTERFLY_RECOMPRESS_FINAL_REQUESTED()
PLAN%FUSE_FINAL=PLAN%FUSE_FINAL .OR. PLAN%RECOMPRESS_FINAL

DO JMLOC=1,D%NUMP
  IF (LDIRECT .AND. LSYM) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S,PLAN,JMLOC)
  ELSEIF (LDIRECT) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A,PLAN,JMLOC)
  ELSEIF (LSYM) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_S,PLAN,JMLOC)
  ELSE
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_A,PLAN,JMLOC)
  ENDIF
ENDDO

IF (LVALIDATE) THEN
  CALL KEEP_BEST_MATRIX(PLAN)
ENDIF
PLAN%ENABLED=ANY(PLAN%USE_HYBRID)
IF (.NOT.PLAN%ENABLED) RETURN

IBETA=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_S,0,IBETA)
  ELSEIF (LDIRECT) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_A,0,IBETA)
  ELSEIF (LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_S,0,IBETA)
  ELSE
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_A,0,IBETA)
  ENDIF
ENDDO
PLAN%EVEN_BETA_COLS=IBETA
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_S,1,IBETA)
  ELSEIF (LDIRECT) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_A,1,IBETA)
  ELSEIF (LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_S,1,IBETA)
  ELSE
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_A,1,IBETA)
  ENDIF
ENDDO
PLAN%BETA_COLS=IBETA
PLAN%WORK_COLS=IBETA

IF (PLAN%MAX_LEVELS > 0) ALLOCATE(PLAN%LEVEL(1:PLAN%MAX_LEVELS))
IFACTORS=0
IPIVOTS=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S,PLAN,IFACTORS,IPIVOTS)
  ELSEIF (LDIRECT) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A,PLAN,IFACTORS,IPIVOTS)
  ELSEIF (LSYM) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_S,PLAN,IFACTORS,IPIVOTS)
  ELSE
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_A,PLAN,IFACTORS,IPIVOTS)
  ENDIF
ENDDO

CALL ALLOC_GROUP(PLAN%LEVEL0)
CALL ALLOC_GROUP(PLAN%FINAL)
CALL ALLOC_GROUP(PLAN%DENSE)
DO JL=1,PLAN%MAX_LEVELS
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%FWD)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%REV_ODD)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
IFACTORS_ALLOC=IFACTORS
IF (PLAN%FUSE_FINAL) IFACTORS_ALLOC=IFACTORS_ALLOC+PLAN%FINAL_FACTOR_VALUES
ALLOCATE(PLAN%FACTORS(IFACTORS_ALLOC))
PLAN%FACTORS=ZERO
IF (PLAN%COMPACT_ID) ALLOCATE(PLAN%PIVOTS(IPIVOTS))

ALLOCATE(IFW(PLAN%MAX_LEVELS),IRO(PLAN%MAX_LEVELS),IRE(PLAN%MAX_LEVELS))
IFW=0
IRO=0
IRE=0
I0=0
IFN=0
IDENSE=0
IPOS=1
IPIVOT_POS=1
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S,JMLOC,PLAN,&
      & IPOS,IPIVOT_POS,I0,IFN,IDENSE,IFW,IRO,IRE,LDIRECT)
  ELSEIF (LDIRECT) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A,JMLOC,PLAN,&
      & IPOS,IPIVOT_POS,I0,IFN,IDENSE,IFW,IRO,IRE,LDIRECT)
  ELSEIF (LSYM) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_S,JMLOC,PLAN,IPOS,IPIVOT_POS,I0,IFN,&
      & IDENSE,IFW,IRO,IRE,LDIRECT)
  ELSE
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_A,JMLOC,PLAN,IPOS,IPIVOT_POS,I0,IFN,&
      & IDENSE,IFW,IRO,IRE,LDIRECT)
  ENDIF
ENDDO
DEALLOCATE(IFW,IRO,IRE)
IF (PLAN%COMPACT_ID) CALL BUILD_COMPACT_GROUPS(PLAN)
IF (PLAN%FUSE_FINAL) CALL BUILD_FUSED_FINAL(PLAN,IPOS)

#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(PLAN%FACTORS)
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$ACC ENTER DATA COPYIN(PLAN%PIVOTS)
ENDIF
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$ACC ENTER DATA COPYIN(PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:PLAN%FACTORS)
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$OMP TARGET ENTER DATA MAP(TO:PLAN%PIVOTS)
ENDIF
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$OMP TARGET ENTER DATA MAP(TO:PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
#endif
END SUBROUTINE BUILD_ONE_PLAN

SUBROUTINE SCAN_HYBRID(HYBRID,PLAN,KMLOC)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
INTEGER(KIND=JPIM) :: JB

IF (HYBRID%CONSTRUCTED) PLAN%CANDIDATE_COUNT=PLAN%CANDIDATE_COUNT+1
PLAN%USE_HYBRID(KMLOC)=HYBRID%SELECTED
IF (.NOT.HYBRID%SELECTED) RETURN
PLAN%SELECTED_COUNT=PLAN%SELECTED_COUNT+1
PLAN%DENSE_BLOCKS=PLAN%DENSE_BLOCKS+HYBRID%DENSE_BLOCKS
PLAN%LOW_RANK_BLOCKS=PLAN%LOW_RANK_BLOCKS+HYBRID%LOW_RANK_BLOCKS
PLAN%BUTTERFLY_BLOCKS=PLAN%BUTTERFLY_BLOCKS+HYBRID%BUTTERFLY_BLOCKS
PLAN%DENSE_COST=PLAN%DENSE_COST+HYBRID%DENSE_COST
PLAN%HYBRID_COST=PLAN%HYBRID_COST+HYBRID%HYBRID_COST
DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND /= HYBRID_DENSE) &
    PLAN%MAX_LEVELS=MAX(PLAN%MAX_LEVELS,HYBRID%BLOCKS(JB)%BUT%N_LEVELS)
ENDDO
END SUBROUTINE SCAN_HYBRID

SUBROUTINE KEEP_BEST_MATRIX(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JBEST,JMLOC

JBEST=0
DO JMLOC=1,SIZE(PLAN%USE_HYBRID)
  IF (PLAN%USE_HYBRID(JMLOC)) THEN
    JBEST=JMLOC
    EXIT
  ENDIF
ENDDO
PLAN%USE_HYBRID=.FALSE.
IF (JBEST > 0) PLAN%USE_HYBRID(JBEST)=.TRUE.
END SUBROUTINE KEEP_BEST_MATRIX

SUBROUTINE ASSIGN_WORK(HYBRID,KPARITY,KBASE)
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: HYBRID
INTEGER(KIND=JPIM),INTENT(IN) :: KPARITY
INTEGER(KIND=JPIB),INTENT(INOUT) :: KBASE
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) CYCLE
  IF (MOD(HYBRID%BLOCKS(JB)%BUT%N_LEVELS,2) /= KPARITY) CYCLE
  HYBRID%BLOCKS(JB)%WORK_BASE=KBASE
  KBASE=KBASE+HYBRID%BLOCKS(JB)%BUT%IBETALEN_MAX
ENDDO
END SUBROUTINE ASSIGN_WORK

SUBROUTINE COUNT_HYBRID(HYBRID,PLAN,KFACTORS,KPIVOTS)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS,KPIVOTS
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) THEN
    PLAN%DENSE%COUNT=PLAN%DENSE%COUNT+1
    KFACTORS=KFACTORS+HYBRID%BLOCKS(JB)%DENSE_COST
  ELSE
    CALL COUNT_MATRIX(HYBRID%BLOCKS(JB)%BUT,PLAN,KFACTORS,KPIVOTS)
  ENDIF
ENDDO
END SUBROUTINE COUNT_HYBRID

SUBROUTINE COUNT_MATRIX(BUT,PLAN,KFACTORS,KPIVOTS)
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS,KPIVOTS
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR
TYPE(NODE_TYPE),POINTER :: YNODE

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  PLAN%LEVEL0%COUNT=PLAN%LEVEL0%COUNT+1
  IF (PLAN%COMPACT_ID) THEN
    KFACTORS=KFACTORS+INT(YNODE%ICOLS-YNODE%IRANK,JPIB)*&
      & INT(YNODE%IRANK,JPIB)
    KPIVOTS=KPIVOTS+YNODE%ICOLS
  ELSE
    KFACTORS=KFACTORS+INT(YNODE%ICOLS,JPIB)*INT(YNODE%IRANK,JPIB)
  ENDIF
ENDDO
DO JL=1,BUT%N_LEVELS
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
      IRANKL=BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)%IRANK
      IRANKR=0
      IF (2*JK <= BUT%SLEV(JL-1)%IK) &
        IRANKR=BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)%IRANK
      PLAN%LEVEL(JL)%FWD%COUNT=PLAN%LEVEL(JL)%FWD%COUNT+1
      IF (MOD(JJ,2) == 1) THEN
        PLAN%LEVEL(JL)%REV_ODD%COUNT=PLAN%LEVEL(JL)%REV_ODD%COUNT+1
      ELSE
        PLAN%LEVEL(JL)%REV_EVEN%COUNT=PLAN%LEVEL(JL)%REV_EVEN%COUNT+1
      ENDIF
      IF (PLAN%COMPACT_ID) THEN
        KFACTORS=KFACTORS+INT(IRANKL+IRANKR-YNODE%IRANK,JPIB)*&
          & INT(YNODE%IRANK,JPIB)
        KPIVOTS=KPIVOTS+IRANKL+IRANKR
      ELSE
        KFACTORS=KFACTORS+INT(IRANKL+IRANKR,JPIB)*INT(YNODE%IRANK,JPIB)
      ENDIF
    ENDDO
  ENDDO
ENDDO
JL=BUT%N_LEVELS
DO JK=1,BUT%SLEV(JL)%IK
  DO JJ=1,BUT%SLEV(JL)%IJ
    YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
    PLAN%FINAL%COUNT=PLAN%FINAL%COUNT+1
    KFACTORS=KFACTORS+INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
    PLAN%FINAL_FACTOR_VALUES=PLAN%FINAL_FACTOR_VALUES+&
      & INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
  ENDDO
ENDDO
END SUBROUTINE COUNT_MATRIX

SUBROUTINE ALLOC_GROUP(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ALLOCATE(GROUP%N(GROUP%COUNT),GROUP%K(GROUP%COUNT),GROUP%LDB(GROUP%COUNT))
ALLOCATE(GROUP%SRC_COL(GROUP%COUNT),GROUP%DST_COL(GROUP%COUNT),&
  & GROUP%FACTOR_OFFSET(GROUP%COUNT),GROUP%PIVOT_OFFSET(GROUP%COUNT))
END SUBROUTINE ALLOC_GROUP

SUBROUTINE SET_GROUP(GROUP,KI,KN,KK,KLDB,KSRC,KDST,KFACTOR,KPIVOT)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KN,KK,KLDB
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC,KDST,KFACTOR
INTEGER(KIND=JPIB),INTENT(IN),OPTIONAL :: KPIVOT
GROUP%N(KI)=KN
GROUP%K(KI)=KK
GROUP%LDB(KI)=KLDB
GROUP%SRC_COL(KI)=KSRC
GROUP%DST_COL(KI)=KDST
GROUP%FACTOR_OFFSET(KI)=KFACTOR
GROUP%PIVOT_OFFSET(KI)=-1_JPIB
IF (PRESENT(KPIVOT)) GROUP%PIVOT_OFFSET(KI)=KPIVOT
END SUBROUTINE SET_GROUP

SUBROUTINE BUILD_COMPACT_GROUPS(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JL

CALL BUILD_COMPACT_TILES(PLAN%LEVEL0,.FALSE.)
DO JL=1,PLAN%MAX_LEVELS
  CALL BUILD_COMPACT_TILES(PLAN%LEVEL(JL)%FWD,.FALSE.)
  CALL BUILD_COMPACT_TILES(PLAN%LEVEL(JL)%REV_ODD,.TRUE.)
  CALL BUILD_COMPACT_TILES(PLAN%LEVEL(JL)%REV_EVEN,.TRUE.)
ENDDO
END SUBROUTINE BUILD_COMPACT_GROUPS

SUBROUTINE BUILD_COMPACT_TILES(GROUP,LREVERSE)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
LOGICAL,INTENT(IN) :: LREVERSE
INTEGER(KIND=JPIM),PARAMETER :: IOUTPUTS=8
INTEGER(KIND=JPIM) :: IG,IT,ILIMIT,ISTART

IF (GROUP%COUNT <= 0) RETURN
GROUP%TILE_COUNT=0
DO IG=1,GROUP%COUNT
  ILIMIT=MERGE(GROUP%K(IG),GROUP%N(IG),LREVERSE)
  GROUP%TILE_COUNT=GROUP%TILE_COUNT+(ILIMIT+IOUTPUTS-1)/IOUTPUTS
ENDDO
ALLOCATE(GROUP%TILE_GROUP(GROUP%TILE_COUNT),&
  & GROUP%TILE_START(GROUP%TILE_COUNT))
IT=0
DO IG=1,GROUP%COUNT
  ILIMIT=MERGE(GROUP%K(IG),GROUP%N(IG),LREVERSE)
  DO ISTART=0,ILIMIT-1,IOUTPUTS
    IT=IT+1
    GROUP%TILE_GROUP(IT)=IG-1
    GROUP%TILE_START(IT)=ISTART
  ENDDO
ENDDO
CALL ENTER_COMPACT_GROUP_DEVICE(GROUP)
END SUBROUTINE BUILD_COMPACT_TILES

SUBROUTINE ENTER_COMPACT_GROUP_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
ASSOCIATE(GN=>GROUP%N,GK=>GROUP%K,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
  & GF=>GROUP%FACTOR_OFFSET,GP=>GROUP%PIVOT_OFFSET,&
  & GTG=>GROUP%TILE_GROUP,GTS=>GROUP%TILE_START)
#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(GN,GK,GS,GD,GF,GP,GTG,GTS)
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:GN,GK,GS,GD,GF,GP,GTG,GTS)
#endif
END ASSOCIATE
END SUBROUTINE ENTER_COMPACT_GROUP_DEVICE

SUBROUTINE BUILD_FUSED_FINAL(PLAN,KPOS)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS

INTEGER(KIND=JPIM),ALLOCATABLE :: IORDER(:),ITEMP(:)
INTEGER(KIND=JPIM) :: IN,IWIDTH,ILEFT,IMID,IRIGHT,IOUT,I1,I2,I,ISTART,IEND
INTEGER(KIND=JPIM) :: IDX,IPREV,IGROUP,INOUT,IKTOTAL,JK
INTEGER(KIND=JPIB) :: ICOUNT,IGATHER,IPACK_COL,IGROUP_SRC,ISOURCE

IN=PLAN%FINAL%COUNT
IF (IN <= 0) RETURN
ALLOCATE(IORDER(IN),ITEMP(IN))
DO I=1,IN
  IORDER(I)=I
ENDDO

! Sort final factors by output range so equal destinations can share one GEMM.
IWIDTH=1
DO WHILE(IWIDTH < IN)
  DO ILEFT=1,IN,2*IWIDTH
    IMID=MIN(ILEFT+IWIDTH-1,IN)
    IRIGHT=MIN(ILEFT+2*IWIDTH-1,IN)
    I1=ILEFT
    I2=IMID+1
    DO IOUT=ILEFT,IRIGHT
      IF (I1 > IMID) THEN
        ITEMP(IOUT)=IORDER(I2)
        I2=I2+1
      ELSEIF (I2 > IRIGHT) THEN
        ITEMP(IOUT)=IORDER(I1)
        I1=I1+1
      ELSEIF (FINAL_GROUP_LESS(PLAN%FINAL,IORDER(I1),IORDER(I2))) THEN
        ITEMP(IOUT)=IORDER(I1)
        I1=I1+1
      ELSE
        ITEMP(IOUT)=IORDER(I2)
        I2=I2+1
      ENDIF
    ENDDO
  ENDDO
  IORDER=ITEMP
  IWIDTH=2*IWIDTH
ENDDO

IGROUP=1
IPREV=IORDER(1)
DO I=2,IN
  IDX=IORDER(I)
  IF (.NOT.FINAL_GROUP_SAME(PLAN%FINAL,IPREV,IDX)) IGROUP=IGROUP+1
  IPREV=IDX
ENDDO
PLAN%FINAL_FUSED%COUNT=IGROUP
PLAN%FINAL_ORIGINAL_COST=SUM(INT(PLAN%FINAL%N,JPIB)*INT(PLAN%FINAL%K,JPIB))
PLAN%FINAL_EXEC_COST=PLAN%FINAL_ORIGINAL_COST
PLAN%FINAL_DIRECT_GROUPS=IGROUP
IF (.NOT.PLAN%RECOMPRESS_FINAL .AND. IGROUP == IN) THEN
  PLAN%FUSE_FINAL=.FALSE.
  PLAN%FINAL_FUSED%COUNT=0
  DEALLOCATE(IORDER,ITEMP)
  RETURN
ENDIF
IF (PLAN%RECOMPRESS_FINAL) THEN
  CALL BUILD_RECOMPRESSED_FINAL(PLAN,KPOS,IORDER,IGROUP)
  DEALLOCATE(IORDER,ITEMP)
  RETURN
ENDIF
CALL ALLOC_GROUP(PLAN%FINAL_FUSED)
PLAN%FINAL_GATHER_COUNT=SUM(INT(PLAN%FINAL%K,JPIB))
ALLOCATE(PLAN%FINAL_GATHER_SRC(PLAN%FINAL_GATHER_COUNT),&
  & PLAN%FINAL_GATHER_DST(PLAN%FINAL_GATHER_COUNT))

I=1
IGROUP=0
IGATHER=0
IPACK_COL=0
DO WHILE(I <= IN)
  ISTART=I
  IDX=IORDER(I)
  INOUT=PLAN%FINAL%N(IDX)
  IKTOTAL=0
  DO WHILE(I <= IN)
    IF (.NOT.FINAL_GROUP_SAME(PLAN%FINAL,IORDER(ISTART),IORDER(I))) EXIT
    IKTOTAL=IKTOTAL+PLAN%FINAL%K(IORDER(I))
    I=I+1
  ENDDO
  IEND=I-1
  IGROUP=IGROUP+1
  IGROUP_SRC=IPACK_COL
  CALL SET_GROUP(PLAN%FINAL_FUSED,IGROUP,INOUT,IKTOTAL,INOUT,&
    & IGROUP_SRC,PLAN%FINAL%DST_COL(IDX),KPOS-1)
  DO IOUT=ISTART,IEND
    IDX=IORDER(IOUT)
    ICOUNT=INT(INOUT,JPIB)*INT(PLAN%FINAL%K(IDX),JPIB)
    ISOURCE=PLAN%FINAL%FACTOR_OFFSET(IDX)+1
    PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=&
      & PLAN%FACTORS(ISOURCE:ISOURCE+ICOUNT-1)
    KPOS=KPOS+ICOUNT
    DO JK=0,PLAN%FINAL%K(IDX)-1
      IGATHER=IGATHER+1
      PLAN%FINAL_GATHER_SRC(IGATHER)=PLAN%FINAL%SRC_COL(IDX)+JK
      PLAN%FINAL_GATHER_DST(IGATHER)=IPACK_COL
      IPACK_COL=IPACK_COL+1
    ENDDO
  ENDDO
ENDDO
DEALLOCATE(IORDER,ITEMP)
END SUBROUTINE BUILD_FUSED_FINAL

SUBROUTINE BUILD_RECOMPRESSED_FINAL(PLAN,KPOS,KORDER,KGROUPS)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(IN) :: KORDER(:),KGROUPS

INTEGER(KIND=JPIM) :: I,ISTART,IEND,IDX,INOUT,IKTOTAL,IRANK
INTEGER(KIND=JPIM) :: J,JK,JI,IC,IGROUP,IPROJECT,IBASIS,IDIRECT
INTEGER(KIND=JPIM),ALLOCATABLE :: ICLIST(:)
INTEGER(KIND=JPIB) :: IGATHER,IPACK_COL,IGAMMA_COL,ISOURCE,ICOUNT
INTEGER(KIND=JPIB) :: IORIGINAL_COST,IRECOMPRESSED_COST,IOFF
REAL(KIND=JPRD) :: ZEPS,ZSELECT_RATIO
REAL(KIND=JPRD),ALLOCATABLE :: ZB(:,:),ZPNONIM(:,:),ZPROJ(:,:)
LOGICAL :: LSELECT

PLAN%FINAL_FUSED%COUNT=KGROUPS
PLAN%FINAL_PROJECT%COUNT=KGROUPS
PLAN%FINAL_BASIS%COUNT=KGROUPS
CALL ALLOC_GROUP(PLAN%FINAL_FUSED)
CALL ALLOC_GROUP(PLAN%FINAL_PROJECT)
CALL ALLOC_GROUP(PLAN%FINAL_BASIS)
PLAN%FINAL_GATHER_COUNT=SUM(INT(PLAN%FINAL%K,JPIB))
ALLOCATE(PLAN%FINAL_GATHER_SRC(PLAN%FINAL_GATHER_COUNT),&
  & PLAN%FINAL_GATHER_DST(PLAN%FINAL_GATHER_COUNT))

ZEPS=BUTTERFLY_FINAL_EPS()
ZSELECT_RATIO=BUTTERFLY_FINAL_SELECT_RATIO()
I=1
IGROUP=0
IPROJECT=0
IBASIS=0
IDIRECT=0
IGATHER=0
IPACK_COL=0
IGAMMA_COL=0
PLAN%FINAL_EXEC_COST=0
PLAN%FINAL_RECOMPRESSED_GROUPS=0
PLAN%FINAL_DIRECT_GROUPS=0
DO WHILE(I <= SIZE(KORDER))
  ISTART=I
  IDX=KORDER(I)
  INOUT=PLAN%FINAL%N(IDX)
  IKTOTAL=0
  DO WHILE(I <= SIZE(KORDER))
    IF (.NOT.FINAL_GROUP_SAME(PLAN%FINAL,KORDER(ISTART),KORDER(I))) EXIT
    IKTOTAL=IKTOTAL+PLAN%FINAL%K(KORDER(I))
    I=I+1
  ENDDO
  IEND=I-1
  IGROUP=IGROUP+1
  ALLOCATE(ZB(INOUT,IKTOTAL),ICLIST(IKTOTAL),&
    & ZPNONIM(MAX(1,MIN(INOUT,IKTOTAL)),MAX(1,IKTOTAL)))
  J=0
  DO JI=ISTART,IEND
    IDX=KORDER(JI)
    ISOURCE=PLAN%FINAL%FACTOR_OFFSET(IDX)+1
    DO JK=1,PLAN%FINAL%K(IDX)
      J=J+1
      ZB(:,J)=REAL(PLAN%FACTORS(ISOURCE+(JK-1)*INOUT:&
        & ISOURCE+JK*INOUT-1),JPRD)
      IGATHER=IGATHER+1
      PLAN%FINAL_GATHER_SRC(IGATHER)=PLAN%FINAL%SRC_COL(IDX)+JK-1
      PLAN%FINAL_GATHER_DST(IGATHER)=IPACK_COL
      IPACK_COL=IPACK_COL+1
    ENDDO
  ENDDO

  CALL COMPUTE_ID(ZEPS,INOUT,IKTOTAL,ZB,IRANK,ICLIST,ZPNONIM)
  IORIGINAL_COST=INT(INOUT,JPIB)*INT(IKTOTAL,JPIB)
  IRECOMPRESSED_COST=INT(IRANK,JPIB)*INT(INOUT+IKTOTAL,JPIB)
  LSELECT=IRANK < MIN(INOUT,IKTOTAL) .AND. &
    & REAL(IRECOMPRESSED_COST,JPRD) < ZSELECT_RATIO*REAL(IORIGINAL_COST,JPRD)
  IF (LSELECT) THEN
    ALLOCATE(ZPROJ(IKTOTAL,IRANK))
    ZPROJ=0.0_JPRD
    DO JI=1,IKTOTAL
      IC=ICLIST(JI)
      IF (JI <= IRANK) THEN
        ZPROJ(IC,JI)=1.0_JPRD
      ELSE
        ZPROJ(IC,1:IRANK)=ZPNONIM(1:IRANK,JI-IRANK)
      ENDIF
    ENDDO
    IOFF=KPOS-1
    ICOUNT=INT(IKTOTAL,JPIB)*INT(IRANK,JPIB)
    PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=&
      & RESHAPE(REAL(ZPROJ,JPRBT),[ICOUNT])
    KPOS=KPOS+ICOUNT
    IPROJECT=IPROJECT+1
    CALL SET_GROUP(PLAN%FINAL_PROJECT,IPROJECT,IRANK,IKTOTAL,IKTOTAL,&
      & IPACK_COL-IKTOTAL,IGAMMA_COL,IOFF)

    IOFF=KPOS-1
    ICOUNT=INT(INOUT,JPIB)*INT(IRANK,JPIB)
    PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=&
      & RESHAPE(REAL(ZB(:,ICLIST(1:IRANK)),JPRBT),[ICOUNT])
    KPOS=KPOS+ICOUNT
    IBASIS=IBASIS+1
    CALL SET_GROUP(PLAN%FINAL_BASIS,IBASIS,INOUT,IRANK,INOUT,&
      & IGAMMA_COL,PLAN%FINAL%DST_COL(IDX),IOFF)
    IGAMMA_COL=IGAMMA_COL+IRANK
    PLAN%FINAL_EXEC_COST=PLAN%FINAL_EXEC_COST+IRECOMPRESSED_COST
    PLAN%FINAL_RECOMPRESSED_GROUPS=PLAN%FINAL_RECOMPRESSED_GROUPS+1
    DEALLOCATE(ZPROJ)
  ELSE
    IOFF=KPOS-1
    PLAN%FACTORS(KPOS:KPOS+IORIGINAL_COST-1)=&
      & RESHAPE(REAL(ZB,JPRBT),[IORIGINAL_COST])
    KPOS=KPOS+IORIGINAL_COST
    IDIRECT=IDIRECT+1
    CALL SET_GROUP(PLAN%FINAL_FUSED,IDIRECT,INOUT,IKTOTAL,INOUT,&
      & IPACK_COL-IKTOTAL,PLAN%FINAL%DST_COL(IDX),IOFF)
    PLAN%FINAL_EXEC_COST=PLAN%FINAL_EXEC_COST+IORIGINAL_COST
    PLAN%FINAL_DIRECT_GROUPS=PLAN%FINAL_DIRECT_GROUPS+1
  ENDIF
  DEALLOCATE(ZB,ICLIST,ZPNONIM)
ENDDO
PLAN%FINAL_PROJECT%COUNT=IPROJECT
PLAN%FINAL_BASIS%COUNT=IBASIS
PLAN%FINAL_FUSED%COUNT=IDIRECT
IF (IPROJECT == 0 .AND. IDIRECT == PLAN%FINAL%COUNT) THEN
  PLAN%FUSE_FINAL=.FALSE.
  PLAN%RECOMPRESS_FINAL=.FALSE.
ENDIF
END SUBROUTINE BUILD_RECOMPRESSED_FINAL

LOGICAL FUNCTION FINAL_GROUP_LESS(GROUP,KI,KJ)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KJ
FINAL_GROUP_LESS=GROUP%DST_COL(KI) < GROUP%DST_COL(KJ) .OR. &
  & (GROUP%DST_COL(KI) == GROUP%DST_COL(KJ) .AND. &
  & GROUP%N(KI) <= GROUP%N(KJ))
END FUNCTION FINAL_GROUP_LESS

LOGICAL FUNCTION FINAL_GROUP_SAME(GROUP,KI,KJ)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KJ
FINAL_GROUP_SAME=GROUP%DST_COL(KI) == GROUP%DST_COL(KJ) .AND. &
  & GROUP%N(KI) == GROUP%N(KJ)
END FUNCTION FINAL_GROUP_SAME

SUBROUTINE FILL_HYBRID(HYBRID,KMLOC,PLAN,KPOS,KPIVOT_POS,K0,KFINAL,KDENSE,KFW,KRO,KRE,&
  & LTRANSPOSED)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K0,KFINAL,KDENSE,KFW(:),KRO(:),KRE(:)
LOGICAL,INTENT(IN) :: LTRANSPOSED
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) THEN
    CALL FILL_DENSE(HYBRID%BLOCKS(JB),KMLOC,PLAN,KPOS,KDENSE,LTRANSPOSED)
  ELSE
    CALL FILL_MATRIX(HYBRID%BLOCKS(JB)%BUT,KMLOC,&
      & HYBRID%BLOCKS(JB)%FIRST_ROW,HYBRID%BLOCKS(JB)%FIRST_COL,&
      & HYBRID%BLOCKS(JB)%WORK_BASE,PLAN,KPOS,KPIVOT_POS,K0,KFINAL,KFW,KRO,KRE,&
      & LTRANSPOSED)
  ENDIF
ENDDO
END SUBROUTINE FILL_HYBRID

SUBROUTINE FILL_DENSE(BLOCK,KMLOC,PLAN,KPOS,KDENSE,LTRANSPOSED)
USE TPM_DISTR, ONLY: D
TYPE(HYBRID_BLOCK),INTENT(IN) :: BLOCK
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(INOUT) :: KDENSE
LOGICAL,INTENT(IN) :: LTRANSPOSED
INTEGER(KIND=JPIB) :: IOFF
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)

ALLOCATE(ZT(BLOCK%NCOLS,BLOCK%NROWS))
ZT=TRANSPOSE(BLOCK%DENSE)
IOFF=KPOS-1
PLAN%FACTORS(KPOS:KPOS+BLOCK%DENSE_COST-1)=RESHAPE(ZT,[BLOCK%DENSE_COST])
KPOS=KPOS+BLOCK%DENSE_COST
KDENSE=KDENSE+1
IF (LTRANSPOSED) THEN
  CALL SET_GROUP(PLAN%DENSE,KDENSE,BLOCK%NROWS,BLOCK%NCOLS,BLOCK%NCOLS,&
    & D%OFFSETS_GEMM1(KMLOC)+BLOCK%FIRST_COL-1,&
    & D%OFFSETS_GEMM2(KMLOC)+BLOCK%FIRST_ROW-1,IOFF)
ELSE
  CALL SET_GROUP(PLAN%DENSE,KDENSE,BLOCK%NROWS,BLOCK%NCOLS,BLOCK%NCOLS,&
    & D%OFFSETS_GEMM2(KMLOC)+BLOCK%FIRST_COL-1,&
    & D%OFFSETS_GEMM1(KMLOC)+BLOCK%FIRST_ROW-1,IOFF)
ENDIF
DEALLOCATE(ZT)
END SUBROUTINE FILL_DENSE

SUBROUTINE FILL_MATRIX(BUT,KMLOC,KFIRST_ROW,KFIRST_COL,KWORK_BASE,&
  & PLAN,KPOS,KPIVOT_POS,K0,KFINAL,KFW,KRO,KRE,LTRANSPOSED)
USE TPM_DISTR, ONLY: D
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC,KFIRST_ROW,KFIRST_COL
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K0,KFINAL,KFW(:),KRO(:),KRE(:)
LOGICAL,INTENT(IN) :: LTRANSPOSED
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR
INTEGER(KIND=JPIB) :: IOFF,IPIVOT_OFF,ISRC,IDST
TYPE(NODE_TYPE),POINTER :: YNODE,YLEFT,YRIGHT

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  CALL PACK_PLAN_PROJECTION(YNODE,PLAN,KPOS,KPIVOT_POS,IOFF,IPIVOT_OFF)
  K0=K0+1
  IF (LTRANSPOSED) THEN
    ISRC=D%OFFSETS_GEMM1(KMLOC)+KFIRST_COL+YNODE%IFCOL-2
  ELSE
    ISRC=D%OFFSETS_GEMM2(KMLOC)+KFIRST_COL+YNODE%IFCOL-2
  ENDIF
  IDST=KWORK_BASE+YNODE%IOFFBETA
  CALL SET_GROUP(PLAN%LEVEL0,K0,YNODE%IRANK,YNODE%ICOLS,YNODE%ICOLS,&
    & ISRC,IDST,IOFF,IPIVOT_OFF)
ENDDO

DO JL=1,BUT%N_LEVELS
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
      YLEFT=>BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)
      IRANKL=YLEFT%IRANK
      IRANKR=0
      IF (2*JK <= BUT%SLEV(JL-1)%IK) THEN
        YRIGHT=>BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)
        IRANKR=YRIGHT%IRANK
      ENDIF
      CALL PACK_PLAN_PROJECTION(YNODE,PLAN,KPOS,KPIVOT_POS,IOFF,IPIVOT_OFF)
      ISRC=KWORK_BASE+YLEFT%IOFFBETA
      IDST=KWORK_BASE+YNODE%IOFFBETA
      KFW(JL)=KFW(JL)+1
      CALL SET_GROUP(PLAN%LEVEL(JL)%FWD,KFW(JL),YNODE%IRANK,IRANKL+IRANKR,&
        & IRANKL+IRANKR,ISRC,IDST,IOFF,IPIVOT_OFF)
      IF (MOD(JJ,2) == 1) THEN
        KRO(JL)=KRO(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%REV_ODD,KRO(JL),YNODE%IRANK,&
          & IRANKL+IRANKR,IRANKL+IRANKR,ISRC,IDST,IOFF,IPIVOT_OFF)
      ELSE
        KRE(JL)=KRE(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%REV_EVEN,KRE(JL),YNODE%IRANK,&
          & IRANKL+IRANKR,IRANKL+IRANKR,ISRC,IDST,IOFF,IPIVOT_OFF)
      ENDIF
    ENDDO
  ENDDO
ENDDO

JL=BUT%N_LEVELS
DO JK=1,BUT%SLEV(JL)%IK
  DO JJ=1,BUT%SLEV(JL)%IJ
    YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
    IOFF=KPOS-1
    PLAN%FACTORS(KPOS:KPOS+INT(YNODE%IROWS,JPIB)*YNODE%IRANK-1)=&
      & RESHAPE(REAL(YNODE%B,JPRBT),[YNODE%IROWS*YNODE%IRANK])
    KPOS=KPOS+INT(YNODE%IROWS,JPIB)*YNODE%IRANK
    KFINAL=KFINAL+1
    IF (LTRANSPOSED) THEN
      CALL SET_GROUP(PLAN%FINAL,KFINAL,YNODE%IROWS,YNODE%IRANK,YNODE%IROWS,&
        & KWORK_BASE+YNODE%IOFFBETA,&
        & D%OFFSETS_GEMM2(KMLOC)+KFIRST_ROW+YNODE%IFROW-2,IOFF)
    ELSE
      CALL SET_GROUP(PLAN%FINAL,KFINAL,YNODE%IROWS,YNODE%IRANK,YNODE%IROWS,&
        & KWORK_BASE+YNODE%IOFFBETA,&
        & D%OFFSETS_GEMM1(KMLOC)+KFIRST_ROW+YNODE%IFROW-2,IOFF)
    ENDIF
  ENDDO
ENDDO
END SUBROUTINE FILL_MATRIX

SUBROUTINE PACK_PLAN_PROJECTION(NODE,PLAN,KPOS,KPIVOT_POS,KOFFSET,KPIVOT_OFFSET)
TYPE(NODE_TYPE),INTENT(IN) :: NODE
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIB),INTENT(OUT) :: KOFFSET,KPIVOT_OFFSET
INTEGER(KIND=JPIB) :: ICOUNT

IF (.NOT.PLAN%COMPACT_ID) THEN
  CALL PACK_PROJECTION(NODE,PLAN%FACTORS,KPOS,KOFFSET)
  KPIVOT_OFFSET=-1_JPIB
  RETURN
ENDIF

KOFFSET=KPOS-1
ICOUNT=INT(NODE%IRANK,JPIB)*INT(NODE%ICOLS-NODE%IRANK,JPIB)
IF (ICOUNT > 0) THEN
  PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=NODE%PNONIM(1:ICOUNT)
  KPOS=KPOS+ICOUNT
ENDIF
KPIVOT_OFFSET=KPIVOT_POS-1
PLAN%PIVOTS(KPIVOT_POS:KPIVOT_POS+NODE%ICOLS-1)=NODE%ICLIST-1
KPIVOT_POS=KPIVOT_POS+NODE%ICOLS
END SUBROUTINE PACK_PLAN_PROJECTION

SUBROUTINE PACK_PROJECTION(NODE,PFACTORS,KPOS,KOFFSET)
TYPE(NODE_TYPE),INTENT(IN) :: NODE
REAL(KIND=JPRBT),INTENT(INOUT) :: PFACTORS(:)
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIB),INTENT(OUT) :: KOFFSET
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)
INTEGER(KIND=JPIM) :: JI,JR,IC

ALLOCATE(ZT(NODE%ICOLS,NODE%IRANK))
ZT=ZERO
DO JI=1,NODE%ICOLS
  IC=NODE%ICLIST(JI)
  IF (JI <= NODE%IRANK) THEN
    ZT(IC,JI)=ONE
  ELSE
    DO JR=1,NODE%IRANK
      ZT(IC,JR)=NODE%PNONIM((JI-NODE%IRANK-1)*NODE%IRANK+JR)
    ENDDO
  ENDIF
ENDDO
KOFFSET=KPOS-1
PFACTORS(KPOS:KPOS+INT(NODE%ICOLS,JPIB)*NODE%IRANK-1)=&
  & RESHAPE(ZT,[NODE%ICOLS*NODE%IRANK])
KPOS=KPOS+INT(NODE%ICOLS,JPIB)*NODE%IRANK
DEALLOCATE(ZT)
END SUBROUTINE PACK_PROJECTION

FUNCTION BUTTERFLY_WORK_COLUMNS() RESULT(KCOLS)
USE TPM_FLT, ONLY: S
INTEGER(KIND=JPIB) :: KCOLS
KCOLS=MAX(S%PLAN_A%WORK_COLS,S%PLAN_S%WORK_COLS,&
  & S%PLAN_DIRECT_A%WORK_COLS,S%PLAN_DIRECT_S%WORK_COLS)
END FUNCTION BUTTERFLY_WORK_COLUMNS

SUBROUTINE APPLY_BUTTERFLY_INVERSE(PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PIN(:),POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KIN_BASE,KOUT_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

CALL ZERO_COLUMNS(POUT,KLD,KOUT_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .FALSE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE-1,ALLOCATOR,.TRUE.)
CALL RUN_PROJECTION(PLAN%LEVEL0,PLAN,PIN,POUT,KLD,0_JPIB,KOUT_BASE,&
  & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE,ALLOCATOR)
DO JL=1,PLAN%MAX_LEVELS
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,POUT,PIN,KLD,KOUT_BASE,KIN_BASE,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+2*JL-1,ALLOCATOR)
  ELSE
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+2*JL-1,ALLOCATOR)
  ENDIF
ENDDO
CALL COPY_COLUMNS(POUT,PIN,KLD,KOUT_BASE,KIN_BASE,0_JPIB,&
  & PLAN%EVEN_BETA_COLS,KASYNC)
CALL RUN_GROUP(PLAN%FINAL,PLAN,PIN,POUT,KLD,KIN_BASE,0_JPIB,&
  & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
END SUBROUTINE APPLY_BUTTERFLY_INVERSE

SUBROUTINE APPLY_BUTTERFLY_DIRECT(PLAN,PIN,POUT,KLD,KWORK_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

CALL ZERO_COLUMNS(POUT,KLD,KWORK_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+39,ALLOCATOR,.TRUE.)
CALL RUN_GROUP(PLAN%FINAL,PLAN,PIN,POUT,KLD,0_JPIB,KWORK_BASE,&
  & .TRUE.,.TRUE.,ZERO,ISTREAM,KBLAS_BASE+40,ALLOCATOR)
CALL COPY_COLUMNS_INPLACE(POUT,KLD,KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
  & PLAN%EVEN_BETA_COLS,&
  & PLAN%BETA_COLS-PLAN%EVEN_BETA_COLS,KASYNC)
DO JL=PLAN%MAX_LEVELS,1,-1
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_ODD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,&
      & .TRUE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+40+2*JL-1,ALLOCATOR)
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_EVEN,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,&
      & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+40+2*JL,ALLOCATOR)
  ELSE
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_ODD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+40+2*JL-1,ALLOCATOR)
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_EVEN,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+40+2*JL,ALLOCATOR)
  ENDIF
ENDDO
CALL RUN_PROJECTION(PLAN%LEVEL0,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
  & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+70,ALLOCATOR,.TRUE.)
END SUBROUTINE APPLY_BUTTERFLY_DIRECT

SUBROUTINE APPLY_BUTTERFLY_DIRECT_FORWARD(PLAN,PIN,POUT,KLD,KWORK_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

CALL ZERO_COLUMNS(POUT,KLD,KWORK_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .FALSE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE-1,ALLOCATOR,.TRUE.)
CALL RUN_PROJECTION(PLAN%LEVEL0,PLAN,PIN,POUT,KLD,0_JPIB,KWORK_BASE,&
  & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE,ALLOCATOR)
DO JL=1,PLAN%MAX_LEVELS
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,POUT,POUT,KLD,KWORK_BASE,&
      & KWORK_BASE+PLAN%BETA_COLS,.FALSE.,.FALSE.,ZERO,ISTREAM,&
      & KBLAS_BASE+2*JL-1,ALLOCATOR)
  ELSE
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,.FALSE.,.FALSE.,ZERO,ISTREAM,&
      & KBLAS_BASE+2*JL-1,ALLOCATOR)
  ENDIF
ENDDO
CALL COPY_COLUMNS_INPLACE(POUT,KLD,KWORK_BASE,&
  & KWORK_BASE+PLAN%BETA_COLS,0_JPIB,PLAN%EVEN_BETA_COLS,KASYNC)
IF (PLAN%FUSE_FINAL) THEN
  CALL GATHER_FINAL_COLUMNS(POUT,KLD,KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,&
    & PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST,&
    & PLAN%FINAL_GATHER_COUNT,KASYNC)
  IF (PLAN%RECOMPRESS_FINAL) THEN
    CALL RUN_GROUP(PLAN%FINAL_PROJECT,PLAN,POUT,POUT,KLD,KWORK_BASE,&
      & KWORK_BASE+PLAN%BETA_COLS,.FALSE.,.FALSE.,ZERO,ISTREAM,&
      & KBLAS_BASE+29,ALLOCATOR)
    CALL RUN_GROUP(PLAN%FINAL_FUSED,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
      & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
    CALL RUN_GROUP(PLAN%FINAL_BASIS,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,0_JPIB,.FALSE.,.TRUE.,ONE,ISTREAM,&
      & KBLAS_BASE+31,ALLOCATOR,.TRUE.)
  ELSE
    CALL RUN_GROUP(PLAN%FINAL_FUSED,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
      & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
  ENDIF
ELSE
  CALL RUN_GROUP(PLAN%FINAL,PLAN,POUT,POUT,KLD,&
    & KWORK_BASE+PLAN%BETA_COLS,0_JPIB,.FALSE.,.TRUE.,ONE,ISTREAM,&
    & KBLAS_BASE+30,ALLOCATOR,.TRUE.)
ENDIF
END SUBROUTINE APPLY_BUTTERFLY_DIRECT_FORWARD

SUBROUTINE GATHER_FINAL_COLUMNS(PBUF,KLD,KSRC_BASE,KDST_BASE,&
  & KSRC,KDST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KCOUNT
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC(:),KDST(:)
INTEGER(KIND=JPIB) :: J,ICOL,IFIELD,JEND

IF (KCOUNT <= 0) RETURN
JEND=INT(KLD,JPIB)*KCOUNT
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF,KSRC,KDST) &
!$ACC& ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JEND,KLD,KSRC_BASE,KDST_BASE) &
!$OMP& MAP(PRESENT:PBUF,KSRC,KDST)
#endif
DO J=1,JEND
  ICOL=(J-1)/KLD+1
  IFIELD=MOD(J-1,INT(KLD,JPIB))+1
  PBUF((KDST_BASE+KDST(ICOL))*KLD+IFIELD)=&
    & PBUF((KSRC_BASE+KSRC(ICOL))*KLD+IFIELD)
ENDDO
END SUBROUTINE GATHER_FINAL_COLUMNS

SUBROUTINE ZERO_COLUMNS(PBUF,KLD,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KCOUNT
INTEGER(KIND=JPIB) :: J,JEND

JEND=INT(KLD,JPIB)*KCOUNT
IF (JEND <= 0) RETURN
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JEND) MAP(PRESENT:PBUF)
#endif
DO J=1,JEND
  PBUF(J)=ZERO
ENDDO
END SUBROUTINE ZERO_COLUMNS

SUBROUTINE COPY_COLUMNS(PSRC,PDST,KLD,KSRC_BASE,KDST_BASE,KFIRST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PSRC(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PDST(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KFIRST,KCOUNT
INTEGER(KIND=JPIB) :: J,JSTART,JEND
IF (KCOUNT <= 0) RETURN
JSTART=KFIRST*KLD+1
JEND=(KFIRST+KCOUNT)*KLD
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PSRC,PDST) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JSTART,JEND) MAP(PRESENT:PSRC,PDST)
#endif
DO J=JSTART,JEND
  PDST(KDST_BASE*KLD+J)=PSRC(KSRC_BASE*KLD+J)
ENDDO
END SUBROUTINE COPY_COLUMNS

SUBROUTINE COPY_COLUMNS_INPLACE(PBUF,KLD,KSRC_BASE,KDST_BASE,KFIRST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KFIRST,KCOUNT
INTEGER(KIND=JPIB) :: J,JSTART,JEND
IF (KCOUNT <= 0) RETURN
JSTART=KFIRST*KLD+1
JEND=(KFIRST+KCOUNT)*KLD
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JSTART,JEND) MAP(PRESENT:PBUF)
#endif
DO J=JSTART,JEND
  PBUF(KDST_BASE*KLD+J)=PBUF(KSRC_BASE*KLD+J)
ENDDO
END SUBROUTINE COPY_COLUMNS_INPLACE

SUBROUTINE RUN_PROJECTION(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
  & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
USE ISO_C_BINDING, ONLY: C_LOC,C_INT,C_INT64_T,C_INTPTR_T
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PA(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PC(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KBLAS
INTEGER(KIND=JPIB),INTENT(IN) :: KADD_A,KADD_C
LOGICAL,INTENT(IN) :: LREVERSE,LFACTOR_TRANSPOSED
REAL(KIND=JPRBT),INTENT(IN) :: PBETA
INTEGER(C_INTPTR_T),INTENT(IN) :: KSTREAM
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
LOGICAL,INTENT(IN),OPTIONAL :: LORDERED

IF (GROUP%COUNT <= 0) RETURN
IF (.NOT.PLAN%COMPACT_ID .OR. LFACTOR_TRANSPOSED) THEN
  IF (PRESENT(LORDERED)) THEN
    CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
      & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
  ELSE
    CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
      & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR)
  ENDIF
  RETURN
ENDIF

#ifdef CUDAGPU
ASSOCIATE(PFACTORS=>PLAN%FACTORS,PPIVOTS=>PLAN%PIVOTS,&
  & GN=>GROUP%N,GK=>GROUP%K,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
  & GF=>GROUP%FACTOR_OFFSET,GP=>GROUP%PIVOT_OFFSET,&
  & GTG=>GROUP%TILE_GROUP,GTS=>GROUP%TILE_START)
#ifdef ACCGPU
!$ACC HOST_DATA USE_DEVICE(PA,PC,PFACTORS,PPIVOTS,GN,GK,GS,GD,GF,GP,GTG,GTS)
#endif
#ifdef OMPGPU
!$OMP TARGET DATA USE_DEVICE_ADDR(PA,PC,PFACTORS,PPIVOTS,GN,GK,GS,GD,GF,GP,GTG,GTS)
#endif
CALL BUTTERFLY_PROJECTION_C(C_LOC(PA),C_LOC(PC),INT(KLD,C_INT),GN,GK,GS,GD,&
  & GF,GP,GTG,GTS,PPIVOTS,C_LOC(PFACTORS),INT(KADD_A,C_INT64_T),&
  & INT(KADD_C,C_INT64_T),INT(GROUP%TILE_COUNT,C_INT),&
  & MERGE(1_C_INT,0_C_INT,LREVERSE),PBETA,KSTREAM)
#ifdef OMPGPU
!$OMP END TARGET DATA
#endif
#ifdef ACCGPU
!$ACC END HOST_DATA
#endif
END ASSOCIATE
#else
IF (PRESENT(LORDERED)) THEN
  CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
    & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
ELSE
  CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
    & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR)
ENDIF
#endif
END SUBROUTINE RUN_PROJECTION

SUBROUTINE RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
  & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
USE HICBLAS_MOD, ONLY: HIP_DGEMM_GROUPED_ASYNC,HIP_SGEMM_GROUPED_ASYNC,&
  & HIP_DGEMM_GROUPED_ORDERED_ASYNC
USE TPM_GEN, ONLY: NCUR_RESOL
USE ISO_C_BINDING, ONLY: C_LOC,C_INTPTR_T
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PA(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PC(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KBLAS
INTEGER(KIND=JPIB),INTENT(IN) :: KADD_A,KADD_C
LOGICAL,INTENT(IN) :: LREVERSE,LFACTOR_TRANSPOSED
REAL(KIND=JPRBT),INTENT(IN) :: PBETA
INTEGER(C_INTPTR_T),INTENT(IN) :: KSTREAM
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
LOGICAL,INTENT(IN),OPTIONAL :: LORDERED
INTEGER(KIND=JPIM) :: IN(GROUP%COUNT),IK(GROUP%COUNT)
INTEGER(KIND=JPIB) :: IOFFA(GROUP%COUNT),IOFFC(GROUP%COUNT)
CHARACTER(LEN=1) :: CTB
LOGICAL :: LLORDERED

IF (GROUP%COUNT <= 0) RETURN
LLORDERED=.FALSE.
IF (PRESENT(LORDERED)) LLORDERED=LORDERED
IF (LREVERSE) THEN
  IN=GROUP%K
  IK=GROUP%N
  IOFFA=(GROUP%DST_COL+KADD_A)*KLD
  IOFFC=(GROUP%SRC_COL+KADD_C)*KLD
  IF (LFACTOR_TRANSPOSED) THEN
    CTB='N'
  ELSE
    CTB='T'
  ENDIF
ELSE
  IN=GROUP%N
  IK=GROUP%K
  IOFFA=(GROUP%SRC_COL+KADD_A)*KLD
  IOFFC=(GROUP%DST_COL+KADD_C)*KLD
  IF (LFACTOR_TRANSPOSED) THEN
    CTB='T'
  ELSE
    CTB='N'
  ENDIF
ENDIF

ASSOCIATE(PFACTORS=>PLAN%FACTORS)
#ifdef OMPGPU
!$OMP TARGET DATA USE_DEVICE_ADDR(PA,PFACTORS,PC)
#endif
#ifdef ACCGPU
!$ACC HOST_DATA USE_DEVICE(PA,PFACTORS,PC)
#endif
#ifdef TRANS_SINGLE
CALL HIP_SGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
  & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
  & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
#else
IF (LLORDERED) THEN
  CALL HIP_DGEMM_GROUPED_ORDERED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
    & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
    & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
ELSE
  CALL HIP_DGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
    & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
    & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
ENDIF
#endif
#ifdef ACCGPU
!$ACC END HOST_DATA
#endif
#ifdef OMPGPU
!$OMP END TARGET DATA
#endif
END ASSOCIATE
END SUBROUTINE RUN_GROUP

SUBROUTINE FREE_GPU_BUTTERFLY_PLANS
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D
INTEGER(KIND=JPIM) :: JMLOC

CALL FREE_ONE_PLAN(S%PLAN_A)
CALL FREE_ONE_PLAN(S%PLAN_S)
CALL FREE_ONE_PLAN(S%PLAN_DIRECT_A)
CALL FREE_ONE_PLAN(S%PLAN_DIRECT_S)
IF (ALLOCATED(S%FA)) THEN
  DO JMLOC=1,D%NUMP
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_A)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_S)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S)
  ENDDO
ENDIF
END SUBROUTINE FREE_GPU_BUTTERFLY_PLANS

SUBROUTINE FREE_ONE_PLAN(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JL
IF (PLAN%COMPACT_ID) CALL EXIT_COMPACT_GROUPS_DEVICE(PLAN)
#ifdef ACCGPU
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$ACC EXIT DATA DELETE(PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
!$ACC EXIT DATA DELETE(PLAN%FACTORS) IF(ASSOCIATED(PLAN%FACTORS))
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$ACC EXIT DATA DELETE(PLAN%PIVOTS)
ENDIF
#endif
#ifdef OMPGPU
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%FACTORS) IF(ASSOCIATED(PLAN%FACTORS))
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%PIVOTS)
ENDIF
#endif
CALL FREE_GROUP(PLAN%LEVEL0)
CALL FREE_GROUP(PLAN%FINAL)
CALL FREE_GROUP(PLAN%FINAL_FUSED)
CALL FREE_GROUP(PLAN%FINAL_PROJECT)
CALL FREE_GROUP(PLAN%FINAL_BASIS)
CALL FREE_GROUP(PLAN%DENSE)
IF (ALLOCATED(PLAN%LEVEL)) THEN
  DO JL=1,SIZE(PLAN%LEVEL)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%FWD)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%REV_ODD)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%REV_EVEN)
  ENDDO
  DEALLOCATE(PLAN%LEVEL)
ENDIF
IF (ASSOCIATED(PLAN%FACTORS)) DEALLOCATE(PLAN%FACTORS)
IF (ALLOCATED(PLAN%PIVOTS)) DEALLOCATE(PLAN%PIVOTS)
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) DEALLOCATE(PLAN%FINAL_GATHER_SRC)
IF (ALLOCATED(PLAN%FINAL_GATHER_DST)) DEALLOCATE(PLAN%FINAL_GATHER_DST)
IF (ALLOCATED(PLAN%USE_HYBRID)) DEALLOCATE(PLAN%USE_HYBRID)
PLAN%ENABLED=.FALSE.
PLAN%COMPACT_ID=.FALSE.
PLAN%FUSE_FINAL=.FALSE.
PLAN%RECOMPRESS_FINAL=.FALSE.
PLAN%MAX_LEVELS=0
PLAN%CANDIDATE_COUNT=0
PLAN%SELECTED_COUNT=0
PLAN%DENSE_BLOCKS=0
PLAN%LOW_RANK_BLOCKS=0
PLAN%BUTTERFLY_BLOCKS=0
PLAN%BETA_COLS=0
PLAN%EVEN_BETA_COLS=0
PLAN%WORK_COLS=0
PLAN%DENSE_COST=0
PLAN%HYBRID_COST=0
PLAN%FINAL_FACTOR_VALUES=0
PLAN%FINAL_GATHER_COUNT=0
PLAN%FINAL_ORIGINAL_COST=0
PLAN%FINAL_EXEC_COST=0
PLAN%FINAL_RECOMPRESSED_GROUPS=0
PLAN%FINAL_DIRECT_GROUPS=0
END SUBROUTINE FREE_ONE_PLAN

SUBROUTINE EXIT_COMPACT_GROUPS_DEVICE(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
INTEGER(KIND=JPIM) :: JL

CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL0)
DO JL=1,PLAN%MAX_LEVELS
  CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL(JL)%FWD)
  CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_ODD)
  CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
END SUBROUTINE EXIT_COMPACT_GROUPS_DEVICE

SUBROUTINE EXIT_COMPACT_GROUP_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
IF (.NOT.ALLOCATED(GROUP%TILE_GROUP)) RETURN
ASSOCIATE(GN=>GROUP%N,GK=>GROUP%K,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
  & GF=>GROUP%FACTOR_OFFSET,GP=>GROUP%PIVOT_OFFSET,&
  & GTG=>GROUP%TILE_GROUP,GTS=>GROUP%TILE_START)
#ifdef ACCGPU
!$ACC EXIT DATA DELETE(GN,GK,GS,GD,GF,GP,GTG,GTS)
#endif
#ifdef OMPGPU
!$OMP TARGET EXIT DATA MAP(DELETE:GN,GK,GS,GD,GF,GP,GTG,GTS)
#endif
END ASSOCIATE
END SUBROUTINE EXIT_COMPACT_GROUP_DEVICE

SUBROUTINE FREE_GROUP(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
IF (ALLOCATED(GROUP%N)) DEALLOCATE(GROUP%N)
IF (ALLOCATED(GROUP%K)) DEALLOCATE(GROUP%K)
IF (ALLOCATED(GROUP%LDB)) DEALLOCATE(GROUP%LDB)
IF (ALLOCATED(GROUP%SRC_COL)) DEALLOCATE(GROUP%SRC_COL)
IF (ALLOCATED(GROUP%DST_COL)) DEALLOCATE(GROUP%DST_COL)
IF (ALLOCATED(GROUP%FACTOR_OFFSET)) DEALLOCATE(GROUP%FACTOR_OFFSET)
IF (ALLOCATED(GROUP%PIVOT_OFFSET)) DEALLOCATE(GROUP%PIVOT_OFFSET)
IF (ALLOCATED(GROUP%TILE_GROUP)) DEALLOCATE(GROUP%TILE_GROUP)
IF (ALLOCATED(GROUP%TILE_START)) DEALLOCATE(GROUP%TILE_START)
GROUP%COUNT=0
GROUP%TILE_COUNT=0
END SUBROUTINE FREE_GROUP

END MODULE BUTTERFLY_GPU_DP_MOD
