#if defined CUDAGPU
#define ACC_GET_HIP_STREAM ACC_GET_CUDA_STREAM
#define OPENACC_LIB OPENACC
#endif

MODULE BUTTERFLY_GPU_DP_MOD

USE PARKIND_ECTRANS, ONLY: JPIM,JPIB,JPRBT,JPRD
USE BUTTERFLY_ALG_DP_MOD, ONLY: BUTTERFLY_STRUCT,NODE_TYPE,BUTTERFLY_GPU_GROUPS,&
  & BUTTERFLY_GPU_PLAN,BUTTERFLY_GPU_FUSED_LEAF,HYBRID_MATRIX,HYBRID_BLOCK,FREE_HYBRID,&
  & HYBRID_DENSE,HYBRID_LOW_RANK,HYBRID_BUTTERFLY
USE INTERPOL_DECOMP_MOD, ONLY: COMPUTE_ID

IMPLICIT NONE

PRIVATE
PUBLIC :: BUILD_GPU_BUTTERFLY_PLANS,FREE_GPU_BUTTERFLY_PLANS
PUBLIC :: APPLY_BUTTERFLY_INVERSE,APPLY_BUTTERFLY_DIRECT,&
  & APPLY_BUTTERFLY_DIRECT_FORWARD
PUBLIC :: BUTTERFLY_WORK_COLUMNS,BUTTERFLY_REQUESTED,BUTTERFLY_DIRECT_REQUESTED,&
  & BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED,BUTTERFLY_DIRECT_OVERLAP_REQUESTED

REAL(KIND=JPRBT),PARAMETER :: ZERO=0.0_JPRBT,ONE=1.0_JPRBT

#ifdef CUDAGPU
INTERFACE
SUBROUTINE BUTTERFLY_PROJECTION_C(PIN,POUT,KLD,KN,KK,KSRC,KDST,KPIVOT,&
  & KSCRATCH,KTILE_GROUP,KTILE_START,KPIVOTS,KADD_A,KADD_C,KADD_SCRATCH,&
  & KNTILES,KREVERSE,PBETA,KSTREAM) &
  & BIND(C,NAME='ectrans_butterfly_projection_cuda')
USE ISO_C_BINDING, ONLY: C_PTR,C_INT,C_INT64_T,C_DOUBLE,C_INTPTR_T
TYPE(C_PTR),VALUE :: PIN,POUT
INTEGER(C_INT),INTENT(IN) :: KN(*),KK(*),KTILE_GROUP(*),KTILE_START(*),KPIVOTS(*)
INTEGER(C_INT64_T),INTENT(IN) :: KSRC(*),KDST(*),KPIVOT(*),KSCRATCH(*)
INTEGER(C_INT64_T),VALUE :: KADD_A,KADD_C,KADD_SCRATCH
INTEGER(C_INT),VALUE :: KLD,KNTILES,KREVERSE
REAL(C_DOUBLE),VALUE :: PBETA
INTEGER(C_INTPTR_T),VALUE :: KSTREAM
END SUBROUTINE BUTTERFLY_PROJECTION_C

SUBROUTINE BUTTERFLY_GROUPED_GEMM_C(PIN,PFACTORS,POUT,KLD,KN,KK,KLDB,&
  & KSRC,KDST,KFACTOR,KADD_A,KADD_C,KCOUNT,KMAX_N,KTRANSPOSED,KATOMIC,&
  & PBETA,KSTREAM) &
  & BIND(C,NAME='ectrans_butterfly_grouped_gemm_cuda')
USE ISO_C_BINDING, ONLY: C_PTR,C_INT,C_INT64_T,C_DOUBLE,C_INTPTR_T
TYPE(C_PTR),VALUE :: PIN,PFACTORS,POUT
INTEGER(C_INT),VALUE :: KLD,KCOUNT,KMAX_N,KTRANSPOSED,KATOMIC
INTEGER(C_INT),INTENT(IN) :: KN(*),KK(*),KLDB(*)
INTEGER(C_INT64_T),INTENT(IN) :: KSRC(*),KDST(*),KFACTOR(*)
INTEGER(C_INT64_T),VALUE :: KADD_A,KADD_C
REAL(C_DOUBLE),VALUE :: PBETA
INTEGER(C_INTPTR_T),VALUE :: KSTREAM
END SUBROUTINE BUTTERFLY_GROUPED_GEMM_C

SUBROUTINE BUTTERFLY_COMPACT_PROJECTION_C(PIN,PFACTORS,POUT,KLD,KN,KK,&
  & KSRC,KDST,KPIVOT,KFACTOR,KPIVOTS,KADD_A,KADD_C,KCOUNT,KMAX_N,PBETA,KSTREAM) &
  & BIND(C,NAME='ectrans_butterfly_compact_projection_cuda')
USE ISO_C_BINDING, ONLY: C_PTR,C_INT,C_INT64_T,C_DOUBLE,C_INTPTR_T
TYPE(C_PTR),VALUE :: PIN,PFACTORS,POUT
INTEGER(C_INT),VALUE :: KLD,KCOUNT,KMAX_N
INTEGER(C_INT),INTENT(IN) :: KN(*),KK(*)
INTEGER(C_INT64_T),INTENT(IN) :: KSRC(*),KDST(*),KPIVOT(*),KFACTOR(*)
INTEGER(C_INT),INTENT(IN) :: KPIVOTS(*)
INTEGER(C_INT64_T),VALUE :: KADD_A,KADD_C
REAL(C_DOUBLE),VALUE :: PBETA
INTEGER(C_INTPTR_T),VALUE :: KSTREAM
END SUBROUTINE BUTTERFLY_COMPACT_PROJECTION_C

SUBROUTINE BUTTERFLY_COMPACT_REVERSE_C(PIN,PFACTORS,POUT,KLD,KN,KK,&
  & KSRC,KDST,KPIVOT,KFACTOR,KPIVOTS,KADD_A,KADD_C,KCOUNT,KMAX_COLS,PBETA,KSTREAM) &
  & BIND(C,NAME='ectrans_butterfly_compact_reverse_cuda')
USE ISO_C_BINDING, ONLY: C_PTR,C_INT,C_INT64_T,C_DOUBLE,C_INTPTR_T
TYPE(C_PTR),VALUE :: PIN,PFACTORS,POUT
INTEGER(C_INT),VALUE :: KLD,KCOUNT,KMAX_COLS
INTEGER(C_INT),INTENT(IN) :: KN(*),KK(*)
INTEGER(C_INT64_T),INTENT(IN) :: KSRC(*),KDST(*),KPIVOT(*),KFACTOR(*)
INTEGER(C_INT),INTENT(IN) :: KPIVOTS(*)
INTEGER(C_INT64_T),VALUE :: KADD_A,KADD_C
REAL(C_DOUBLE),VALUE :: PBETA
INTEGER(C_INTPTR_T),VALUE :: KSTREAM
END SUBROUTINE BUTTERFLY_COMPACT_REVERSE_C

SUBROUTINE BUTTERFLY_FUSED_LEAF_DIRECT_C(PIN,PFACTORS,POUT,KLD,KROWS,KRANKS,&
  & KCOLS,KINPUT,KOUTPUT,KFINAL_FACTOR,KPROJECTION_FACTOR,KPIVOT,KPIVOTS,&
  & KCOUNT,KMAX_RANK,KSTREAM) &
  & BIND(C,NAME='ectrans_butterfly_fused_leaf_direct_cuda')
USE ISO_C_BINDING, ONLY: C_PTR,C_INT,C_INT64_T,C_INTPTR_T
TYPE(C_PTR),VALUE :: PIN,PFACTORS,POUT
INTEGER(C_INT),VALUE :: KLD,KCOUNT,KMAX_RANK
INTEGER(C_INT),INTENT(IN) :: KROWS(*),KRANKS(*),KCOLS(*),KPIVOTS(*)
INTEGER(C_INT64_T),INTENT(IN) :: KINPUT(*),KOUTPUT(*),KFINAL_FACTOR(*),&
  & KPROJECTION_FACTOR(*),KPIVOT(*)
INTEGER(C_INTPTR_T),VALUE :: KSTREAM
END SUBROUTINE BUTTERFLY_FUSED_LEAF_DIRECT_C
END INTERFACE
#endif

CONTAINS

LOGICAL FUNCTION BUTTERFLY_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY',ZVALUE,LENGTH=ILENGTH,&
  & STATUS=ISTATUS)
BUTTERFLY_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_REQUESTED

LOGICAL FUNCTION BUTTERFLY_DIRECT_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_DIRECT',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_DIRECT_REQUESTED=ISTATUS /= 0 .OR. ILENGTH == 0 .OR. ZVALUE(1:1) /= '0'
END FUNCTION BUTTERFLY_DIRECT_REQUESTED

LOGICAL FUNCTION BUTTERFLY_DIRECT_OVERLAP_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_OVERLAP_DIRECT',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_DIRECT_OVERLAP_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_DIRECT_OVERLAP_REQUESTED

LOGICAL FUNCTION BUTTERFLY_NATIVE_GROUPED_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
#ifdef CUDAGPU
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_NATIVE_GROUPED',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_NATIVE_GROUPED_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#else
BUTTERFLY_NATIVE_GROUPED_REQUESTED=.FALSE.
#endif
END FUNCTION BUTTERFLY_NATIVE_GROUPED_REQUESTED

LOGICAL FUNCTION BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_TRANSPOSE_DIRECT',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#ifdef CUDAGPU
IF ((ISTATUS /= 0 .OR. ILENGTH == 0) .AND. BUTTERFLY_COMPACT_ID_REQUESTED()) &
  & BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED=.TRUE.
#endif
END FUNCTION BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED

LOGICAL FUNCTION BUTTERFLY_INVERSE_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_INVERSE',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_INVERSE_REQUESTED=ISTATUS /= 0 .OR. ILENGTH == 0 .OR. &
  & ZVALUE(1:1) /= '0'
END FUNCTION BUTTERFLY_INVERSE_REQUESTED

LOGICAL FUNCTION BUTTERFLY_FUSE_FINAL_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FUSE_FINAL',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_FUSE_FINAL_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_FUSE_FINAL_REQUESTED

LOGICAL FUNCTION BUTTERFLY_RECOMPRESS_FINAL_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_RECOMPRESS_FINAL',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_RECOMPRESS_FINAL_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_RECOMPRESS_FINAL_REQUESTED

REAL(KIND=JPRD) FUNCTION BUTTERFLY_FINAL_EPS()
CHARACTER(LEN=32) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
BUTTERFLY_FINAL_EPS=1.0E-14_JPRD
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FINAL_EPS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
  READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) BUTTERFLY_FINAL_EPS
  IF (ISTATUS /= 0 .OR. BUTTERFLY_FINAL_EPS <= 0.0_JPRD) &
    & BUTTERFLY_FINAL_EPS=1.0E-14_JPRD
ENDIF
END FUNCTION BUTTERFLY_FINAL_EPS

REAL(KIND=JPRD) FUNCTION BUTTERFLY_FINAL_SELECT_RATIO()
CHARACTER(LEN=32) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
BUTTERFLY_FINAL_SELECT_RATIO=0.8_JPRD
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FINAL_SELECT_RATIO',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
IF (ISTATUS == 0 .AND. ILENGTH > 0) THEN
  READ(ZVALUE(1:ILENGTH),*,IOSTAT=ISTATUS) BUTTERFLY_FINAL_SELECT_RATIO
  IF (ISTATUS /= 0 .OR. BUTTERFLY_FINAL_SELECT_RATIO <= 0.0_JPRD .OR. &
    & BUTTERFLY_FINAL_SELECT_RATIO >= 1.0_JPRD) &
    & BUTTERFLY_FINAL_SELECT_RATIO=0.8_JPRD
ENDIF
END FUNCTION BUTTERFLY_FINAL_SELECT_RATIO

LOGICAL FUNCTION BUTTERFLY_VALIDATION_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_VALIDATE',ZVALUE,LENGTH=ILENGTH,&
  & STATUS=ISTATUS)
BUTTERFLY_VALIDATION_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_VALIDATION_REQUESTED

LOGICAL FUNCTION BUTTERFLY_COMPACT_ID_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
#ifdef CUDAGPU
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_COMPACT_ID',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_COMPACT_ID_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#else
BUTTERFLY_COMPACT_ID_REQUESTED=.FALSE.
#endif
END FUNCTION BUTTERFLY_COMPACT_ID_REQUESTED

LOGICAL FUNCTION BUTTERFLY_FUSION_DIAGNOSTICS_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FUSION_DIAGNOSTICS',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_FUSION_DIAGNOSTICS_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION BUTTERFLY_FUSION_DIAGNOSTICS_REQUESTED

LOGICAL FUNCTION BUTTERFLY_FUSE_LEAF_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
#if defined(CUDAGPU) && !defined(TRANS_SINGLE)
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FUSE_LEAF',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_FUSE_LEAF_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#else
BUTTERFLY_FUSE_LEAF_REQUESTED=.FALSE.
#endif
END FUNCTION BUTTERFLY_FUSE_LEAF_REQUESTED

LOGICAL FUNCTION BUTTERFLY_FUSE_REVERSE_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS
#if defined(CUDAGPU) && !defined(TRANS_SINGLE)
CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_BUTTERFLY_FUSE_REVERSE',ZVALUE,&
  & LENGTH=ILENGTH,STATUS=ISTATUS)
BUTTERFLY_FUSE_REVERSE_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
#else
BUTTERFLY_FUSE_REVERSE_REQUESTED=.FALSE.
#endif
END FUNCTION BUTTERFLY_FUSE_REVERSE_REQUESTED

SUBROUTINE BUILD_GPU_BUTTERFLY_PLANS
USE TPM_FLT, ONLY: S
USE TPM_GEN, ONLY: NOUT
USE TPM_DISTR, ONLY: D
REAL :: ZRATIO
INTEGER(KIND=JPIM) :: JMLOC

IF (BUTTERFLY_INVERSE_REQUESTED()) THEN
  CALL BUILD_ONE_PLAN(S%PLAN_A,.FALSE.,.FALSE.)
  CALL BUILD_ONE_PLAN(S%PLAN_S,.TRUE.,.FALSE.)
ENDIF
IF (BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED()) THEN
  CALL BUILD_ONE_PLAN(S%PLAN_DIRECT_A,.FALSE.,.TRUE.)
  CALL BUILD_ONE_PLAN(S%PLAN_DIRECT_S,.TRUE.,.TRUE.)
ENDIF

WRITE(NOUT,'(A,L1,A,L1)') 'GPU butterfly requested=',BUTTERFLY_REQUESTED(),&
  & ' validation=',BUTTERFLY_VALIDATION_REQUESTED()
ZRATIO=1.0
IF (S%PLAN_A%DENSE_COST > 0) &
  ZRATIO=REAL(S%PLAN_A%HYBRID_COST)/REAL(S%PLAN_A%DENSE_COST)
WRITE(NOUT,'(A,L1,A,I0,A,I0,A,3(I0,1X),A,F7.4,A,I0)') &
  & 'GPU hybrid anti=',S%PLAN_A%ENABLED,' candidates=',S%PLAN_A%CANDIDATE_COUNT,&
  & ' selected=',S%PLAN_A%SELECTED_COUNT,' blocks(d/l/b)=',S%PLAN_A%DENSE_BLOCKS,&
  & S%PLAN_A%LOW_RANK_BLOCKS,S%PLAN_A%BUTTERFLY_BLOCKS,' cost_ratio=',ZRATIO,&
  & ' work_cols=',S%PLAN_A%WORK_COLS
CALL PRINT_PLAN_PROJECTION_STATS(NOUT,'inverse anti',S%PLAN_A)
CALL PRINT_PLAN_EXEC_STATS(NOUT,'inverse anti',S%PLAN_A)
CALL PRINT_PLAN_FUSION_STATS(NOUT,'inverse anti',S%PLAN_A,.FALSE.,.FALSE.)
ZRATIO=1.0
IF (S%PLAN_S%DENSE_COST > 0) &
  ZRATIO=REAL(S%PLAN_S%HYBRID_COST)/REAL(S%PLAN_S%DENSE_COST)
WRITE(NOUT,'(A,L1,A,I0,A,I0,A,3(I0,1X),A,F7.4,A,I0)') &
  & 'GPU hybrid sym =',S%PLAN_S%ENABLED,' candidates=',S%PLAN_S%CANDIDATE_COUNT,&
  & ' selected=',S%PLAN_S%SELECTED_COUNT,' blocks(d/l/b)=',S%PLAN_S%DENSE_BLOCKS,&
  & S%PLAN_S%LOW_RANK_BLOCKS,S%PLAN_S%BUTTERFLY_BLOCKS,' cost_ratio=',ZRATIO,&
  & ' work_cols=',S%PLAN_S%WORK_COLS
CALL PRINT_PLAN_PROJECTION_STATS(NOUT,'inverse sym',S%PLAN_S)
CALL PRINT_PLAN_EXEC_STATS(NOUT,'inverse sym',S%PLAN_S)
CALL PRINT_PLAN_FUSION_STATS(NOUT,'inverse sym',S%PLAN_S,.TRUE.,.FALSE.)
IF (BUTTERFLY_TRANSPOSE_DIRECT_REQUESTED()) THEN
  ZRATIO=1.0
  IF (S%PLAN_DIRECT_A%DENSE_COST > 0) &
    ZRATIO=REAL(S%PLAN_DIRECT_A%HYBRID_COST)/REAL(S%PLAN_DIRECT_A%DENSE_COST)
  WRITE(NOUT,'(A,L1,A,I0,A,I0,A,F7.4,A,I0,A,I0,A,I0,A,I0,A,F7.4)') &
    & 'GPU transpose direct anti=',S%PLAN_DIRECT_A%ENABLED,&
    & ' candidates=',S%PLAN_DIRECT_A%CANDIDATE_COUNT,&
    & ' selected=',S%PLAN_DIRECT_A%SELECTED_COUNT,' cost_ratio=',ZRATIO,&
    & ' work_cols=',S%PLAN_DIRECT_A%WORK_COLS,&
    & ' final=',S%PLAN_DIRECT_A%FINAL%COUNT,&
    & ' fused_final=',S%PLAN_DIRECT_A%FINAL_FUSED%COUNT,&
    & ' recompressed=',S%PLAN_DIRECT_A%FINAL_RECOMPRESSED_GROUPS,&
    & ' final_cost_ratio=',REAL(S%PLAN_DIRECT_A%FINAL_EXEC_COST,JPRD)/&
    & REAL(MAX(1_JPIB,S%PLAN_DIRECT_A%FINAL_ORIGINAL_COST),JPRD)
  CALL PRINT_PLAN_PROJECTION_STATS(NOUT,'direct anti',S%PLAN_DIRECT_A)
  CALL PRINT_PLAN_EXEC_STATS(NOUT,'direct anti',S%PLAN_DIRECT_A)
  CALL PRINT_PLAN_FUSION_STATS(NOUT,'direct anti',S%PLAN_DIRECT_A,.FALSE.,.TRUE.)
  IF (S%PLAN_DIRECT_A%FUSE_LEAF) WRITE(NOUT,'(A,I0,A,I0)') &
    & 'GPU fused leaf direct anti count=',S%PLAN_DIRECT_A%FUSED_LEAF%COUNT,&
    & ' max_rank=',S%PLAN_DIRECT_A%FUSED_LEAF%MAX_RANK
  WRITE(NOUT,'(A,L1)') 'GPU direct inline crop anti=',&
    & S%PLAN_DIRECT_A%DIRECT_INLINE_CROP
  WRITE(NOUT,'(A,L1,A,I0)') 'GPU direct native blocks anti=',&
    & S%PLAN_DIRECT_A%DIRECT_NATIVE_BLOCKS,' groups=',&
    & S%PLAN_DIRECT_A%DIRECT_GROUP_COUNT
  ZRATIO=1.0
  IF (S%PLAN_DIRECT_S%DENSE_COST > 0) &
    ZRATIO=REAL(S%PLAN_DIRECT_S%HYBRID_COST)/REAL(S%PLAN_DIRECT_S%DENSE_COST)
  WRITE(NOUT,'(A,L1,A,I0,A,I0,A,F7.4,A,I0,A,I0,A,I0,A,I0,A,F7.4)') &
    & 'GPU transpose direct sym =',S%PLAN_DIRECT_S%ENABLED,&
    & ' candidates=',S%PLAN_DIRECT_S%CANDIDATE_COUNT,&
    & ' selected=',S%PLAN_DIRECT_S%SELECTED_COUNT,' cost_ratio=',ZRATIO,&
    & ' work_cols=',S%PLAN_DIRECT_S%WORK_COLS,&
    & ' final=',S%PLAN_DIRECT_S%FINAL%COUNT,&
    & ' fused_final=',S%PLAN_DIRECT_S%FINAL_FUSED%COUNT,&
    & ' recompressed=',S%PLAN_DIRECT_S%FINAL_RECOMPRESSED_GROUPS,&
    & ' final_cost_ratio=',REAL(S%PLAN_DIRECT_S%FINAL_EXEC_COST,JPRD)/&
    & REAL(MAX(1_JPIB,S%PLAN_DIRECT_S%FINAL_ORIGINAL_COST),JPRD)
  CALL PRINT_PLAN_PROJECTION_STATS(NOUT,'direct sym',S%PLAN_DIRECT_S)
  CALL PRINT_PLAN_EXEC_STATS(NOUT,'direct sym',S%PLAN_DIRECT_S)
  CALL PRINT_PLAN_FUSION_STATS(NOUT,'direct sym',S%PLAN_DIRECT_S,.TRUE.,.TRUE.)
  IF (S%PLAN_DIRECT_S%FUSE_LEAF) WRITE(NOUT,'(A,I0,A,I0)') &
    & 'GPU fused leaf direct sym count=',S%PLAN_DIRECT_S%FUSED_LEAF%COUNT,&
    & ' max_rank=',S%PLAN_DIRECT_S%FUSED_LEAF%MAX_RANK
  WRITE(NOUT,'(A,L1)') 'GPU direct inline crop sym =',&
    & S%PLAN_DIRECT_S%DIRECT_INLINE_CROP
  WRITE(NOUT,'(A,L1,A,I0)') 'GPU direct native blocks sym =',&
    & S%PLAN_DIRECT_S%DIRECT_NATIVE_BLOCKS,' groups=',&
    & S%PLAN_DIRECT_S%DIRECT_GROUP_COUNT
ENDIF
DO JMLOC=1,D%NUMP
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_A)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_S)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A)
  CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S)
ENDDO
END SUBROUTINE BUILD_GPU_BUTTERFLY_PLANS

SUBROUTINE PRINT_PLAN_PROJECTION_STATS(KUNIT,CNAME,PLAN)
INTEGER,INTENT(IN) :: KUNIT
CHARACTER(LEN=*),INTENT(IN) :: CNAME
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
INTEGER(KIND=JPIB) :: ICOMPACT_TOTAL
REAL(KIND=JPRD) :: ZRATIO

IF (.NOT.PLAN%ENABLED .OR. PLAN%PROJECTION_FULL_VALUES <= 0) RETURN
ICOMPACT_TOTAL=PLAN%HYBRID_COST-PLAN%PROJECTION_FULL_VALUES+&
  & PLAN%PROJECTION_COMPACT_VALUES
ZRATIO=REAL(ICOMPACT_TOTAL,JPRD)/REAL(MAX(1_JPIB,PLAN%HYBRID_COST),JPRD)
WRITE(KUNIT,'(A,A,A,I0,A,I0,A,I0,A,I0,A,F7.4)') &
  & 'GPU projection plan=',TRIM(CNAME),&
  & ' full=',PLAN%PROJECTION_FULL_VALUES,&
  & ' nonidentity=',PLAN%PROJECTION_COMPACT_VALUES,&
  & ' identity=',PLAN%PROJECTION_FULL_VALUES-PLAN%PROJECTION_COMPACT_VALUES,&
  & ' final=',PLAN%FINAL_FACTOR_VALUES,' compact_total_ratio=',ZRATIO
END SUBROUTINE PRINT_PLAN_PROJECTION_STATS

SUBROUTINE PRINT_PLAN_EXEC_STATS(KUNIT,CNAME,PLAN)
INTEGER,INTENT(IN) :: KUNIT
CHARACTER(LEN=*),INTENT(IN) :: CNAME
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN

IF (PLAN%DENSE_EXEC_COST <= 0) RETURN
WRITE(KUNIT,'(A,A,A,I0,A,I0,A,F7.4)') 'GPU tile cost ',TRIM(CNAME),&
  & ' dense=',PLAN%DENSE_EXEC_COST,' selected=',PLAN%HYBRID_EXEC_COST,&
  & ' ratio=',REAL(PLAN%HYBRID_EXEC_COST,JPRD)/REAL(PLAN%DENSE_EXEC_COST,JPRD)
END SUBROUTINE PRINT_PLAN_EXEC_STATS

SUBROUTINE PRINT_PLAN_FUSION_STATS(KUNIT,CNAME,PLAN,LSYM,LDIRECT)
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D
INTEGER,INTENT(IN) :: KUNIT
CHARACTER(LEN=*),INTENT(IN) :: CNAME
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
LOGICAL,INTENT(IN) :: LSYM,LDIRECT
INTEGER(KIND=JPIM) :: JMLOC,ICOUNT,IMAX_COLS,IMAX_LEVELS
INTEGER(KIND=JPIM) :: IFIT1,IFIT2,IFIT4,IFIT8
INTEGER(KIND=JPIM) :: IFIT16,IFIT32,IFIT64,IFIT100,ILEVELS(0:8)
INTEGER(KIND=JPIB) :: ITOTAL_COLS,IINTERMEDIATE

IF (.NOT.BUTTERFLY_FUSION_DIAGNOSTICS_REQUESTED() .OR. .NOT.PLAN%ENABLED) RETURN
ICOUNT=0
IMAX_COLS=0
IMAX_LEVELS=0
IFIT1=0
IFIT2=0
IFIT4=0
IFIT8=0
IFIT16=0
IFIT32=0
IFIT64=0
IFIT100=0
ILEVELS=0
ITOTAL_COLS=0
IINTERMEDIATE=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL COLLECT_FUSION_STATS(S%FA(JMLOC)%YHYBRID_DIRECT_S,ICOUNT,&
      & ITOTAL_COLS,IMAX_COLS,IMAX_LEVELS,IFIT1,IFIT2,IFIT4,IFIT8,&
      & IFIT16,IFIT32,IFIT64,IFIT100,ILEVELS,IINTERMEDIATE)
  ELSEIF (LDIRECT) THEN
    CALL COLLECT_FUSION_STATS(S%FA(JMLOC)%YHYBRID_DIRECT_A,ICOUNT,&
      & ITOTAL_COLS,IMAX_COLS,IMAX_LEVELS,IFIT1,IFIT2,IFIT4,IFIT8,&
      & IFIT16,IFIT32,IFIT64,IFIT100,ILEVELS,IINTERMEDIATE)
  ELSEIF (LSYM) THEN
    CALL COLLECT_FUSION_STATS(S%FA(JMLOC)%YHYBRID_S,ICOUNT,&
      & ITOTAL_COLS,IMAX_COLS,IMAX_LEVELS,IFIT1,IFIT2,IFIT4,IFIT8,&
      & IFIT16,IFIT32,IFIT64,IFIT100,ILEVELS,IINTERMEDIATE)
  ELSE
    CALL COLLECT_FUSION_STATS(S%FA(JMLOC)%YHYBRID_A,ICOUNT,&
      & ITOTAL_COLS,IMAX_COLS,IMAX_LEVELS,IFIT1,IFIT2,IFIT4,IFIT8,&
      & IFIT16,IFIT32,IFIT64,IFIT100,ILEVELS,IINTERMEDIATE)
  ENDIF
ENDDO
IF (ICOUNT == 0) RETURN
WRITE(KUNIT,'(A,A,A,I0,A,F9.1,A,I0,A,I0)') 'GPU fusion workset ',TRIM(CNAME),&
  & ' blocks=',ICOUNT,' avg_cols=',REAL(ITOTAL_COLS,JPRD)/REAL(ICOUNT,JPRD),&
  & ' max_cols=',IMAX_COLS,' max_levels=',IMAX_LEVELS
WRITE(KUNIT,'(A,A,A,4(I0,1X),A,I0,A,F10.3)') 'GPU fusion fit ',TRIM(CNAME),&
  & ' field(1/2/4/8)=',IFIT1,IFIT2,IFIT4,IFIT8,&
  & ' intermediate_cols=',IINTERMEDIATE,&
  & ' traffic_mib(field100)=',REAL(16_JPIB*100_JPIB*IINTERMEDIATE,JPRD)/1048576.0_JPRD
WRITE(KUNIT,'(A,A,A,4(I0,1X),A,5(I0,1X))') 'GPU fusion batch ',TRIM(CNAME),&
  & ' field(16/32/64/100)=',IFIT16,IFIT32,IFIT64,IFIT100,&
  & ' levels(0/1/2/3/4)=',ILEVELS(0:4)
END SUBROUTINE PRINT_PLAN_FUSION_STATS

SUBROUTINE COLLECT_FUSION_STATS(HYBRID,KCOUNT,KTOTAL_COLS,KMAX_COLS,&
  & KMAX_LEVELS,KFIT1,KFIT2,KFIT4,KFIT8,KFIT16,KFIT32,KFIT64,KFIT100,&
  & KLEVELS,KINTERMEDIATE)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCOUNT,KMAX_COLS,KMAX_LEVELS
INTEGER(KIND=JPIM),INTENT(INOUT) :: KFIT1,KFIT2,KFIT4,KFIT8
INTEGER(KIND=JPIM),INTENT(INOUT) :: KFIT16,KFIT32,KFIT64,KFIT100,KLEVELS(0:)
INTEGER(KIND=JPIB),INTENT(INOUT) :: KTOTAL_COLS,KINTERMEDIATE
INTEGER(KIND=JPIM) :: JB,JL,ICOLS
INTEGER(KIND=JPIB),PARAMETER :: ISHARED_BYTES=224_JPIB*1024_JPIB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) CYCLE
  ICOLS=HYBRID%BLOCKS(JB)%BUT%IBETALEN_MAX
  KCOUNT=KCOUNT+1
  KTOTAL_COLS=KTOTAL_COLS+INT(ICOLS,JPIB)
  KMAX_COLS=MAX(KMAX_COLS,ICOLS)
  KMAX_LEVELS=MAX(KMAX_LEVELS,HYBRID%BLOCKS(JB)%BUT%N_LEVELS)
  KLEVELS(MIN(UBOUND(KLEVELS,1),HYBRID%BLOCKS(JB)%BUT%N_LEVELS))=&
    & KLEVELS(MIN(UBOUND(KLEVELS,1),HYBRID%BLOCKS(JB)%BUT%N_LEVELS))+1
  IF (16_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT1=KFIT1+1
  IF (32_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT2=KFIT2+1
  IF (64_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT4=KFIT4+1
  IF (128_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT8=KFIT8+1
  IF (256_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT16=KFIT16+1
  IF (512_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT32=KFIT32+1
  IF (1024_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT64=KFIT64+1
  IF (1600_JPIB*INT(ICOLS,JPIB) <= ISHARED_BYTES) KFIT100=KFIT100+1
  DO JL=0,HYBRID%BLOCKS(JB)%BUT%N_LEVELS
    KINTERMEDIATE=KINTERMEDIATE+INT(HYBRID%BLOCKS(JB)%BUT%SLEV(JL)%IBETALEN,JPIB)
  ENDDO
ENDDO
END SUBROUTINE COLLECT_FUSION_STATS

SUBROUTINE BUILD_ONE_PLAN(PLAN,LSYM,LDIRECT)
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D

TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
LOGICAL,INTENT(IN) :: LSYM
LOGICAL,INTENT(IN) :: LDIRECT

INTEGER(KIND=JPIM) :: JMLOC,JL,I0,IFN,IDENSE,IFUSED
INTEGER(KIND=JPIM),ALLOCATABLE :: IFW(:),IRO(:),IRE(:)
INTEGER(KIND=JPIB) :: IPOS,IFACTORS,IFACTORS_ALLOC,IBETA,IPIVOTS,IPIVOT_POS
LOGICAL :: LVALIDATE

ALLOCATE(PLAN%USE_HYBRID(D%NUMP))
PLAN%USE_HYBRID=.FALSE.
LVALIDATE=BUTTERFLY_VALIDATION_REQUESTED()
PLAN%COMPACT_ID=BUTTERFLY_COMPACT_ID_REQUESTED()
PLAN%NATIVE_GROUPED=BUTTERFLY_NATIVE_GROUPED_REQUESTED()
PLAN%FUSE_REVERSE=PLAN%COMPACT_ID .AND. PLAN%NATIVE_GROUPED .AND. &
  & BUTTERFLY_FUSE_REVERSE_REQUESTED()
PLAN%DENSE_DISJOINT=.TRUE.
PLAN%FUSE_LEAF=LDIRECT .AND. PLAN%COMPACT_ID .AND. BUTTERFLY_FUSE_LEAF_REQUESTED()
PLAN%FUSE_FINAL=LDIRECT .AND. BUTTERFLY_FUSE_FINAL_REQUESTED()
PLAN%RECOMPRESS_FINAL=LDIRECT .AND. BUTTERFLY_RECOMPRESS_FINAL_REQUESTED()
PLAN%FUSE_FINAL=PLAN%FUSE_FINAL .OR. PLAN%RECOMPRESS_FINAL

DO JMLOC=1,D%NUMP
  IF (LDIRECT .AND. LSYM) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S,PLAN,JMLOC)
  ELSEIF (LDIRECT) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A,PLAN,JMLOC)
  ELSEIF (LSYM) THEN
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_S,PLAN,JMLOC)
  ELSE
    CALL SCAN_HYBRID(S%FA(JMLOC)%YHYBRID_A,PLAN,JMLOC)
  ENDIF
ENDDO

IF (LVALIDATE) THEN
  CALL KEEP_BEST_MATRIX(PLAN)
ENDIF
PLAN%ENABLED=ANY(PLAN%USE_HYBRID)
IF (.NOT.PLAN%ENABLED) RETURN
IF (LDIRECT) CALL BUILD_DIRECT_INLINE_CROP(PLAN,LSYM)
IF (PLAN%DIRECT_INLINE_CROP) RETURN
IF (LDIRECT) CALL BUILD_DIRECT_NATIVE_BLOCKS(PLAN,LSYM)
IF (PLAN%DIRECT_NATIVE_BLOCKS) RETURN

IBETA=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_S,0,IBETA,PLAN%FUSE_LEAF)
  ELSEIF (LDIRECT) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_A,0,IBETA,PLAN%FUSE_LEAF)
  ELSEIF (LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_S,0,IBETA,PLAN%FUSE_LEAF)
  ELSE
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_A,0,IBETA,PLAN%FUSE_LEAF)
  ENDIF
ENDDO
PLAN%EVEN_BETA_COLS=IBETA
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_S,1,IBETA,PLAN%FUSE_LEAF)
  ELSEIF (LDIRECT) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_DIRECT_A,1,IBETA,PLAN%FUSE_LEAF)
  ELSEIF (LSYM) THEN
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_S,1,IBETA,PLAN%FUSE_LEAF)
  ELSE
    CALL ASSIGN_WORK(S%FA(JMLOC)%YHYBRID_A,1,IBETA,PLAN%FUSE_LEAF)
  ENDIF
ENDDO
PLAN%BETA_COLS=IBETA
PLAN%WORK_COLS=IBETA

IF (PLAN%MAX_LEVELS > 0) ALLOCATE(PLAN%LEVEL(1:PLAN%MAX_LEVELS))
IFACTORS=0
IPIVOTS=0
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S,PLAN,IFACTORS,IPIVOTS)
  ELSEIF (LDIRECT) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A,PLAN,IFACTORS,IPIVOTS)
  ELSEIF (LSYM) THEN
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_S,PLAN,IFACTORS,IPIVOTS)
  ELSE
    CALL COUNT_HYBRID(S%FA(JMLOC)%YHYBRID_A,PLAN,IFACTORS,IPIVOTS)
  ENDIF
ENDDO

CALL ALLOC_GROUP(PLAN%LEVEL0)
CALL ALLOC_GROUP(PLAN%FINAL)
CALL ALLOC_GROUP(PLAN%DENSE)
CALL ALLOC_FUSED_LEAF(PLAN%FUSED_LEAF)
DO JL=1,PLAN%MAX_LEVELS
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%FWD)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%REV_ODD)
  CALL ALLOC_GROUP(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
IFACTORS_ALLOC=IFACTORS
IF (PLAN%FUSE_FINAL) IFACTORS_ALLOC=IFACTORS_ALLOC+PLAN%FINAL_FACTOR_VALUES
ALLOCATE(PLAN%FACTORS(IFACTORS_ALLOC))
PLAN%FACTORS=ZERO
IF (PLAN%COMPACT_ID) ALLOCATE(PLAN%PIVOTS(IPIVOTS))

ALLOCATE(IFW(PLAN%MAX_LEVELS),IRO(PLAN%MAX_LEVELS),IRE(PLAN%MAX_LEVELS))
IFW=0
IRO=0
IRE=0
I0=0
IFN=0
IDENSE=0
IFUSED=0
IPOS=1
IPIVOT_POS=1
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LDIRECT .AND. LSYM) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S,JMLOC,PLAN,&
      & IPOS,IPIVOT_POS,I0,IFN,IDENSE,IFUSED,IFW,IRO,IRE,LDIRECT)
  ELSEIF (LDIRECT) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A,JMLOC,PLAN,&
      & IPOS,IPIVOT_POS,I0,IFN,IDENSE,IFUSED,IFW,IRO,IRE,LDIRECT)
  ELSEIF (LSYM) THEN
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_S,JMLOC,PLAN,IPOS,IPIVOT_POS,I0,IFN,&
      & IDENSE,IFUSED,IFW,IRO,IRE,LDIRECT)
  ELSE
    CALL FILL_HYBRID(S%FA(JMLOC)%YHYBRID_A,JMLOC,PLAN,IPOS,IPIVOT_POS,I0,IFN,&
      & IDENSE,IFUSED,IFW,IRO,IRE,LDIRECT)
  ENDIF
ENDDO
DEALLOCATE(IFW,IRO,IRE)
IF (PLAN%COMPACT_ID) THEN
  CALL BUILD_COMPACT_GROUPS(PLAN)
  IF (.NOT.(LDIRECT .AND. PLAN%NATIVE_GROUPED)) &
    & PLAN%WORK_COLS=PLAN%BETA_COLS+PLAN%COMPACT_SCRATCH_COLS
ENDIF
IF (PLAN%FUSE_FINAL) CALL BUILD_FUSED_FINAL(PLAN,IPOS)
IF (PLAN%NATIVE_GROUPED) CALL ENTER_NATIVE_GROUPS_DEVICE(PLAN)
IF (PLAN%FUSE_LEAF) CALL ENTER_FUSED_LEAF_DEVICE(PLAN%FUSED_LEAF)

#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(PLAN%FACTORS)
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$ACC ENTER DATA COPYIN(PLAN%PIVOTS)
ENDIF
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$ACC ENTER DATA COPYIN(PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:PLAN%FACTORS)
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$OMP TARGET ENTER DATA MAP(TO:PLAN%PIVOTS)
ENDIF
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$OMP TARGET ENTER DATA MAP(TO:PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
#endif
END SUBROUTINE BUILD_ONE_PLAN

SUBROUTINE BUILD_DIRECT_INLINE_CROP(PLAN,LSYM)
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
LOGICAL,INTENT(IN) :: LSYM
INTEGER(KIND=JPIM) :: JMLOC
LOGICAL :: LVALID

PLAN%DIRECT_INLINE_CROP=PLAN%DENSE_DISJOINT .AND. &
  & PLAN%DENSE_BLOCKS == PLAN%SELECTED_COUNT .AND. &
  & PLAN%LOW_RANK_BLOCKS == 0 .AND. PLAN%BUTTERFLY_BLOCKS == 0
IF (.NOT.PLAN%DIRECT_INLINE_CROP) RETURN
ALLOCATE(PLAN%DIRECT_CROP_FIRST(D%NUMP),PLAN%DIRECT_CROP_COUNT(D%NUMP))
PLAN%DIRECT_CROP_FIRST=1
PLAN%DIRECT_CROP_COUNT=0
LVALID=.TRUE.
DO JMLOC=1,D%NUMP
  IF (.NOT.PLAN%USE_HYBRID(JMLOC)) CYCLE
  IF (LSYM) THEN
    CALL SET_DIRECT_INLINE_CROP(S%FA(JMLOC)%YHYBRID_DIRECT_S,PLAN,JMLOC,LVALID)
  ELSE
    CALL SET_DIRECT_INLINE_CROP(S%FA(JMLOC)%YHYBRID_DIRECT_A,PLAN,JMLOC,LVALID)
  ENDIF
ENDDO
IF (.NOT.LVALID) THEN
  DEALLOCATE(PLAN%DIRECT_CROP_FIRST,PLAN%DIRECT_CROP_COUNT)
  PLAN%DIRECT_INLINE_CROP=.FALSE.
ENDIF
END SUBROUTINE BUILD_DIRECT_INLINE_CROP

SUBROUTINE SET_DIRECT_INLINE_CROP(HYBRID,PLAN,KMLOC,LVALID)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
LOGICAL,INTENT(INOUT) :: LVALID

IF (.NOT.LVALID) RETURN
IF (HYBRID%BLOCK_COUNT /= 1 .OR. HYBRID%BLOCKS(1)%KIND /= HYBRID_DENSE .OR. &
  & HYBRID%BLOCKS(1)%FIRST_ROW /= 1 .OR. HYBRID%BLOCKS(1)%FIRST_COL < 1 .OR. &
  & HYBRID%BLOCKS(1)%NCOLS < 1) THEN
  LVALID=.FALSE.
  RETURN
ENDIF
PLAN%DIRECT_CROP_FIRST(KMLOC)=HYBRID%BLOCKS(1)%FIRST_COL
PLAN%DIRECT_CROP_COUNT(KMLOC)=HYBRID%BLOCKS(1)%NCOLS
END SUBROUTINE SET_DIRECT_INLINE_CROP

SUBROUTINE BUILD_DIRECT_NATIVE_BLOCKS(PLAN,LSYM)
USE TPM_DIM, ONLY: R
USE TPM_DISTR, ONLY: D
USE TPM_FLT, ONLY: S
USE TPM_GEOMETRY, ONLY: G
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
LOGICAL,INTENT(IN) :: LSYM
INTEGER(KIND=JPIM) :: ICOUNT,JMLOC,KM
LOGICAL :: LVALID

PLAN%DIRECT_NATIVE_BLOCKS=PLAN%DENSE_DISJOINT .AND. &
  & PLAN%DENSE_BLOCKS > PLAN%SELECTED_COUNT .AND. &
  & PLAN%LOW_RANK_BLOCKS == 0 .AND. PLAN%BUTTERFLY_BLOCKS == 0
IF (.NOT.PLAN%DIRECT_NATIVE_BLOCKS) RETURN

ICOUNT=0
DO JMLOC=1,D%NUMP
  KM=D%MYMS(JMLOC)
  IF (KM == 0) CYCLE
  IF (PLAN%USE_HYBRID(JMLOC)) THEN
    IF (LSYM) THEN
      ICOUNT=ICOUNT+S%FA(JMLOC)%YHYBRID_DIRECT_S%BLOCK_COUNT
    ELSE
      ICOUNT=ICOUNT+S%FA(JMLOC)%YHYBRID_DIRECT_A%BLOCK_COUNT
    ENDIF
  ELSE
    ICOUNT=ICOUNT+1
  ENDIF
ENDDO
IF (ICOUNT <= 0) THEN
  PLAN%DIRECT_NATIVE_BLOCKS=.FALSE.
  RETURN
ENDIF

PLAN%DIRECT_GROUP_COUNT=ICOUNT
ALLOCATE(PLAN%DIRECT_GROUP_MLOC(ICOUNT),PLAN%DIRECT_GROUP_FIRST_ROW(ICOUNT),&
  & PLAN%DIRECT_GROUP_FIRST_COL(ICOUNT),PLAN%DIRECT_GROUP_N(ICOUNT),&
  & PLAN%DIRECT_GROUP_K(ICOUNT))
ICOUNT=0
LVALID=.TRUE.
DO JMLOC=1,D%NUMP
  KM=D%MYMS(JMLOC)
  IF (KM == 0) CYCLE
  IF (PLAN%USE_HYBRID(JMLOC)) THEN
    IF (LSYM) THEN
      CALL APPEND_DIRECT_NATIVE_BLOCKS(S%FA(JMLOC)%YHYBRID_DIRECT_S,&
        & PLAN,JMLOC,ICOUNT,LVALID)
    ELSE
      CALL APPEND_DIRECT_NATIVE_BLOCKS(S%FA(JMLOC)%YHYBRID_DIRECT_A,&
        & PLAN,JMLOC,ICOUNT,LVALID)
    ENDIF
  ELSE
    ICOUNT=ICOUNT+1
    PLAN%DIRECT_GROUP_MLOC(ICOUNT)=JMLOC
    PLAN%DIRECT_GROUP_FIRST_ROW(ICOUNT)=1
    PLAN%DIRECT_GROUP_FIRST_COL(ICOUNT)=1
    PLAN%DIRECT_GROUP_N(ICOUNT)=MERGE((R%NSMAX-KM+3)/2,&
      & (R%NSMAX-KM+2)/2,LSYM)
    PLAN%DIRECT_GROUP_K(ICOUNT)=G%NDGLU(KM)
  ENDIF
ENDDO
IF (.NOT.LVALID .OR. ICOUNT /= PLAN%DIRECT_GROUP_COUNT) THEN
  DEALLOCATE(PLAN%DIRECT_GROUP_MLOC,PLAN%DIRECT_GROUP_FIRST_ROW,&
    & PLAN%DIRECT_GROUP_FIRST_COL,PLAN%DIRECT_GROUP_N,PLAN%DIRECT_GROUP_K)
  PLAN%DIRECT_GROUP_COUNT=0
  PLAN%DIRECT_NATIVE_BLOCKS=.FALSE.
ENDIF
END SUBROUTINE BUILD_DIRECT_NATIVE_BLOCKS

SUBROUTINE APPEND_DIRECT_NATIVE_BLOCKS(HYBRID,PLAN,KMLOC,KCOUNT,LVALID)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCOUNT
LOGICAL,INTENT(INOUT) :: LVALID
INTEGER(KIND=JPIM) :: JB

IF (.NOT.LVALID) RETURN
DO JB=1,HYBRID%BLOCK_COUNT
  ASSOCIATE(B=>HYBRID%BLOCKS(JB))
  IF (B%KIND /= HYBRID_DENSE .OR. B%FIRST_ROW < 1 .OR. B%FIRST_COL < 1 .OR. &
    & B%NROWS < 1 .OR. B%NCOLS < 1) THEN
    LVALID=.FALSE.
    RETURN
  ENDIF
  KCOUNT=KCOUNT+1
  PLAN%DIRECT_GROUP_MLOC(KCOUNT)=KMLOC
  PLAN%DIRECT_GROUP_FIRST_ROW(KCOUNT)=B%FIRST_ROW
  PLAN%DIRECT_GROUP_FIRST_COL(KCOUNT)=B%FIRST_COL
  PLAN%DIRECT_GROUP_N(KCOUNT)=B%NROWS
  PLAN%DIRECT_GROUP_K(KCOUNT)=B%NCOLS
  END ASSOCIATE
ENDDO
END SUBROUTINE APPEND_DIRECT_NATIVE_BLOCKS

SUBROUTINE SCAN_HYBRID(HYBRID,PLAN,KMLOC)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
INTEGER(KIND=JPIM) :: JB

IF (HYBRID%CONSTRUCTED) PLAN%CANDIDATE_COUNT=PLAN%CANDIDATE_COUNT+1
PLAN%USE_HYBRID(KMLOC)=HYBRID%SELECTED
IF (HYBRID%DENSE_EXEC_COST > 0) THEN
  PLAN%DENSE_EXEC_COST=PLAN%DENSE_EXEC_COST+HYBRID%DENSE_EXEC_COST
  IF (HYBRID%SELECTED) THEN
    PLAN%HYBRID_EXEC_COST=PLAN%HYBRID_EXEC_COST+HYBRID%HYBRID_EXEC_COST
  ELSE
    PLAN%HYBRID_EXEC_COST=PLAN%HYBRID_EXEC_COST+HYBRID%DENSE_EXEC_COST
  ENDIF
ENDIF
IF (.NOT.HYBRID%SELECTED) RETURN
PLAN%DENSE_DISJOINT=PLAN%DENSE_DISJOINT .AND. HYBRID%DISJOINT_OUTPUT
PLAN%SELECTED_COUNT=PLAN%SELECTED_COUNT+1
PLAN%DENSE_BLOCKS=PLAN%DENSE_BLOCKS+HYBRID%DENSE_BLOCKS
PLAN%LOW_RANK_BLOCKS=PLAN%LOW_RANK_BLOCKS+HYBRID%LOW_RANK_BLOCKS
PLAN%BUTTERFLY_BLOCKS=PLAN%BUTTERFLY_BLOCKS+HYBRID%BUTTERFLY_BLOCKS
PLAN%DENSE_COST=PLAN%DENSE_COST+HYBRID%DENSE_COST
PLAN%HYBRID_COST=PLAN%HYBRID_COST+HYBRID%HYBRID_COST
DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND /= HYBRID_DENSE) &
    PLAN%MAX_LEVELS=MAX(PLAN%MAX_LEVELS,HYBRID%BLOCKS(JB)%BUT%N_LEVELS)
ENDDO
END SUBROUTINE SCAN_HYBRID

SUBROUTINE KEEP_BEST_MATRIX(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JBEST,JMLOC

JBEST=0
DO JMLOC=1,SIZE(PLAN%USE_HYBRID)
  IF (PLAN%USE_HYBRID(JMLOC)) THEN
    JBEST=JMLOC
    EXIT
  ENDIF
ENDDO
PLAN%USE_HYBRID=.FALSE.
IF (JBEST > 0) PLAN%USE_HYBRID(JBEST)=.TRUE.
END SUBROUTINE KEEP_BEST_MATRIX

SUBROUTINE ASSIGN_WORK(HYBRID,KPARITY,KBASE,LFUSE_LEAF)
TYPE(HYBRID_MATRIX),INTENT(INOUT) :: HYBRID
INTEGER(KIND=JPIM),INTENT(IN) :: KPARITY
INTEGER(KIND=JPIB),INTENT(INOUT) :: KBASE
LOGICAL,INTENT(IN) :: LFUSE_LEAF
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) CYCLE
  IF (LFUSE_LEAF .AND. HYBRID%BLOCKS(JB)%BUT%N_LEVELS == 0 .AND. &
    & HYBRID%BLOCKS(JB)%BUT%SLEV(0)%IJ == 1) CYCLE
  IF (MOD(HYBRID%BLOCKS(JB)%BUT%N_LEVELS,2) /= KPARITY) CYCLE
  HYBRID%BLOCKS(JB)%WORK_BASE=KBASE
  KBASE=KBASE+HYBRID%BLOCKS(JB)%BUT%IBETALEN_MAX
ENDDO
END SUBROUTINE ASSIGN_WORK

SUBROUTINE COUNT_HYBRID(HYBRID,PLAN,KFACTORS,KPIVOTS)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS,KPIVOTS
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) THEN
    PLAN%DENSE%COUNT=PLAN%DENSE%COUNT+1
    KFACTORS=KFACTORS+HYBRID%BLOCKS(JB)%DENSE_COST
  ELSEIF (FUSIBLE_LEAF(PLAN,HYBRID%BLOCKS(JB)%BUT)) THEN
    CALL COUNT_FUSED_LEAF(HYBRID%BLOCKS(JB)%BUT,PLAN,KFACTORS,KPIVOTS)
  ELSE
    CALL COUNT_MATRIX(HYBRID%BLOCKS(JB)%BUT,PLAN,KFACTORS,KPIVOTS)
  ENDIF
ENDDO
END SUBROUTINE COUNT_HYBRID

LOGICAL FUNCTION FUSIBLE_LEAF(PLAN,BUT)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
FUSIBLE_LEAF=PLAN%FUSE_LEAF .AND. BUT%N_LEVELS == 0 .AND. &
  & BUT%SLEV(0)%IJ == 1
END FUNCTION FUSIBLE_LEAF

SUBROUTINE COUNT_FUSED_LEAF(BUT,PLAN,KFACTORS,KPIVOTS)
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS,KPIVOTS
INTEGER(KIND=JPIM) :: JK
TYPE(NODE_TYPE),POINTER :: YNODE

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  PLAN%FUSED_LEAF%COUNT=PLAN%FUSED_LEAF%COUNT+1
  PLAN%FUSED_LEAF%MAX_RANK=MAX(PLAN%FUSED_LEAF%MAX_RANK,YNODE%IRANK)
  KFACTORS=KFACTORS+INT(YNODE%ICOLS-YNODE%IRANK,JPIB)*&
    & INT(YNODE%IRANK,JPIB)+INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
  KPIVOTS=KPIVOTS+YNODE%ICOLS
  PLAN%PROJECTION_FULL_VALUES=PLAN%PROJECTION_FULL_VALUES+&
    & INT(YNODE%ICOLS,JPIB)*INT(YNODE%IRANK,JPIB)
  PLAN%PROJECTION_COMPACT_VALUES=PLAN%PROJECTION_COMPACT_VALUES+&
    & INT(YNODE%ICOLS-YNODE%IRANK,JPIB)*INT(YNODE%IRANK,JPIB)
  PLAN%FINAL_FACTOR_VALUES=PLAN%FINAL_FACTOR_VALUES+&
    & INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
ENDDO
END SUBROUTINE COUNT_FUSED_LEAF

SUBROUTINE COUNT_MATRIX(BUT,PLAN,KFACTORS,KPIVOTS)
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KFACTORS,KPIVOTS
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR
TYPE(NODE_TYPE),POINTER :: YNODE

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  PLAN%LEVEL0%COUNT=PLAN%LEVEL0%COUNT+1
  PLAN%PROJECTION_FULL_VALUES=PLAN%PROJECTION_FULL_VALUES+&
    & INT(YNODE%ICOLS,JPIB)*INT(YNODE%IRANK,JPIB)
  PLAN%PROJECTION_COMPACT_VALUES=PLAN%PROJECTION_COMPACT_VALUES+&
    & INT(YNODE%ICOLS-YNODE%IRANK,JPIB)*INT(YNODE%IRANK,JPIB)
  IF (PLAN%COMPACT_ID) THEN
    KFACTORS=KFACTORS+INT(YNODE%ICOLS-YNODE%IRANK,JPIB)*&
      & INT(YNODE%IRANK,JPIB)
    KPIVOTS=KPIVOTS+YNODE%ICOLS
  ELSE
    KFACTORS=KFACTORS+INT(YNODE%ICOLS,JPIB)*INT(YNODE%IRANK,JPIB)
  ENDIF
ENDDO
DO JL=1,BUT%N_LEVELS
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
      IRANKL=BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)%IRANK
      IRANKR=0
      IF (2*JK <= BUT%SLEV(JL-1)%IK) &
        IRANKR=BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)%IRANK
      PLAN%LEVEL(JL)%FWD%COUNT=PLAN%LEVEL(JL)%FWD%COUNT+1
      IF (MOD(JJ,2) == 1) THEN
        PLAN%LEVEL(JL)%REV_ODD%COUNT=PLAN%LEVEL(JL)%REV_ODD%COUNT+1
      ELSE
        PLAN%LEVEL(JL)%REV_EVEN%COUNT=PLAN%LEVEL(JL)%REV_EVEN%COUNT+1
      ENDIF
      PLAN%PROJECTION_FULL_VALUES=PLAN%PROJECTION_FULL_VALUES+&
        & INT(IRANKL+IRANKR,JPIB)*INT(YNODE%IRANK,JPIB)
      PLAN%PROJECTION_COMPACT_VALUES=PLAN%PROJECTION_COMPACT_VALUES+&
        & INT(IRANKL+IRANKR-YNODE%IRANK,JPIB)*INT(YNODE%IRANK,JPIB)
      IF (PLAN%COMPACT_ID) THEN
        KFACTORS=KFACTORS+INT(IRANKL+IRANKR-YNODE%IRANK,JPIB)*&
          & INT(YNODE%IRANK,JPIB)
        KPIVOTS=KPIVOTS+IRANKL+IRANKR
      ELSE
        KFACTORS=KFACTORS+INT(IRANKL+IRANKR,JPIB)*INT(YNODE%IRANK,JPIB)
      ENDIF
    ENDDO
  ENDDO
ENDDO
JL=BUT%N_LEVELS
DO JK=1,BUT%SLEV(JL)%IK
  DO JJ=1,BUT%SLEV(JL)%IJ
    YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
    PLAN%FINAL%COUNT=PLAN%FINAL%COUNT+1
    KFACTORS=KFACTORS+INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
    PLAN%FINAL_FACTOR_VALUES=PLAN%FINAL_FACTOR_VALUES+&
      & INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
  ENDDO
ENDDO
END SUBROUTINE COUNT_MATRIX

SUBROUTINE ALLOC_GROUP(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ALLOCATE(GROUP%N(GROUP%COUNT),GROUP%K(GROUP%COUNT),GROUP%LDB(GROUP%COUNT))
ALLOCATE(GROUP%SRC_COL(GROUP%COUNT),GROUP%DST_COL(GROUP%COUNT),&
  & GROUP%FACTOR_OFFSET(GROUP%COUNT),GROUP%PIVOT_OFFSET(GROUP%COUNT))
END SUBROUTINE ALLOC_GROUP

SUBROUTINE ALLOC_FUSED_LEAF(GROUP)
TYPE(BUTTERFLY_GPU_FUSED_LEAF),INTENT(INOUT) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ALLOCATE(GROUP%ROWS(GROUP%COUNT),GROUP%RANKS(GROUP%COUNT),&
  & GROUP%COLUMNS(GROUP%COUNT))
ALLOCATE(GROUP%INPUT_COL(GROUP%COUNT),GROUP%OUTPUT_COL(GROUP%COUNT),&
  & GROUP%FINAL_FACTOR_OFFSET(GROUP%COUNT),&
  & GROUP%PROJECTION_FACTOR_OFFSET(GROUP%COUNT),GROUP%PIVOT_OFFSET(GROUP%COUNT))
END SUBROUTINE ALLOC_FUSED_LEAF

SUBROUTINE SET_GROUP(GROUP,KI,KN,KK,KLDB,KSRC,KDST,KFACTOR,KPIVOT)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KN,KK,KLDB
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC,KDST,KFACTOR
INTEGER(KIND=JPIB),INTENT(IN),OPTIONAL :: KPIVOT
GROUP%N(KI)=KN
GROUP%K(KI)=KK
GROUP%LDB(KI)=KLDB
GROUP%SRC_COL(KI)=KSRC
GROUP%DST_COL(KI)=KDST
GROUP%FACTOR_OFFSET(KI)=KFACTOR
GROUP%PIVOT_OFFSET(KI)=-1_JPIB
IF (PRESENT(KPIVOT)) GROUP%PIVOT_OFFSET(KI)=KPIVOT
END SUBROUTINE SET_GROUP

SUBROUTINE BUILD_COMPACT_GROUPS(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JL

CALL BUILD_COMPACT_TILES(PLAN%LEVEL0)
PLAN%COMPACT_SCRATCH_COLS=PLAN%LEVEL0%SCRATCH_COLS
DO JL=1,PLAN%MAX_LEVELS
  CALL BUILD_COMPACT_TILES(PLAN%LEVEL(JL)%FWD)
  CALL BUILD_COMPACT_TILES(PLAN%LEVEL(JL)%REV_ODD)
  CALL BUILD_COMPACT_TILES(PLAN%LEVEL(JL)%REV_EVEN)
  PLAN%COMPACT_SCRATCH_COLS=MAX(PLAN%COMPACT_SCRATCH_COLS,&
    & PLAN%LEVEL(JL)%FWD%SCRATCH_COLS,PLAN%LEVEL(JL)%REV_ODD%SCRATCH_COLS,&
    & PLAN%LEVEL(JL)%REV_EVEN%SCRATCH_COLS)
ENDDO
END SUBROUTINE BUILD_COMPACT_GROUPS

SUBROUTINE ENTER_NATIVE_GROUPS_DEVICE(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
INTEGER(KIND=JPIM) :: JL

CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%DENSE)
CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%LEVEL0)
CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%FINAL)
CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%FINAL_FUSED)
CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%FINAL_PROJECT)
CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%FINAL_BASIS)
DO JL=1,PLAN%MAX_LEVELS
  CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%LEVEL(JL)%FWD)
  CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_ODD)
  CALL ENTER_NATIVE_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
END SUBROUTINE ENTER_NATIVE_GROUPS_DEVICE

SUBROUTINE ENTER_NATIVE_GROUP_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ASSOCIATE(GN=>GROUP%N,GK=>GROUP%K,GLDB=>GROUP%LDB,GS=>GROUP%SRC_COL,&
  & GD=>GROUP%DST_COL,GF=>GROUP%FACTOR_OFFSET)
#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(GN,GK,GLDB,GS,GD,GF)
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:GN,GK,GLDB,GS,GD,GF)
#endif
END ASSOCIATE
END SUBROUTINE ENTER_NATIVE_GROUP_DEVICE

SUBROUTINE ENTER_FUSED_LEAF_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_FUSED_LEAF),INTENT(IN) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ASSOCIATE(GR=>GROUP%ROWS,GK=>GROUP%RANKS,GC=>GROUP%COLUMNS,&
  & GI=>GROUP%INPUT_COL,GO=>GROUP%OUTPUT_COL,GF=>GROUP%FINAL_FACTOR_OFFSET,&
  & GP=>GROUP%PROJECTION_FACTOR_OFFSET,GV=>GROUP%PIVOT_OFFSET)
#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(GR,GK,GC,GI,GO,GF,GP,GV)
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:GR,GK,GC,GI,GO,GF,GP,GV)
#endif
END ASSOCIATE
END SUBROUTINE ENTER_FUSED_LEAF_DEVICE

SUBROUTINE BUILD_COMPACT_TILES(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
INTEGER(KIND=JPIM),PARAMETER :: IOUTPUTS=8
INTEGER(KIND=JPIM) :: IG,IT,ILIMIT,ISTART

IF (GROUP%COUNT <= 0) RETURN
GROUP%TILE_COUNT=0
GROUP%SCRATCH_COLS=0
ALLOCATE(GROUP%SCRATCH_OFFSET(GROUP%COUNT))
DO IG=1,GROUP%COUNT
  GROUP%SCRATCH_OFFSET(IG)=GROUP%SCRATCH_COLS
  GROUP%SCRATCH_COLS=GROUP%SCRATCH_COLS+MAX(0, GROUP%K(IG)-GROUP%N(IG))
  ILIMIT=GROUP%K(IG)
  GROUP%TILE_COUNT=GROUP%TILE_COUNT+(ILIMIT+IOUTPUTS-1)/IOUTPUTS
ENDDO
ALLOCATE(GROUP%TILE_GROUP(GROUP%TILE_COUNT),&
  & GROUP%TILE_START(GROUP%TILE_COUNT))
IT=0
DO IG=1,GROUP%COUNT
  ILIMIT=GROUP%K(IG)
  DO ISTART=0,ILIMIT-1,IOUTPUTS
    IT=IT+1
    GROUP%TILE_GROUP(IT)=IG-1
    GROUP%TILE_START(IT)=ISTART
  ENDDO
ENDDO
CALL ENTER_COMPACT_GROUP_DEVICE(GROUP)
END SUBROUTINE BUILD_COMPACT_TILES

SUBROUTINE ENTER_COMPACT_GROUP_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
ASSOCIATE(GN=>GROUP%N,GK=>GROUP%K,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
  & GF=>GROUP%FACTOR_OFFSET,GP=>GROUP%PIVOT_OFFSET,GW=>GROUP%SCRATCH_OFFSET,&
  & GTG=>GROUP%TILE_GROUP,GTS=>GROUP%TILE_START)
#ifdef ACCGPU
!$ACC ENTER DATA COPYIN(GN,GK,GS,GD,GF,GP,GW,GTG,GTS)
#endif
#ifdef OMPGPU
!$OMP TARGET ENTER DATA MAP(TO:GN,GK,GS,GD,GF,GP,GW,GTG,GTS)
#endif
END ASSOCIATE
END SUBROUTINE ENTER_COMPACT_GROUP_DEVICE

SUBROUTINE BUILD_FUSED_FINAL(PLAN,KPOS)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS

INTEGER(KIND=JPIM),ALLOCATABLE :: IORDER(:),ITEMP(:)
INTEGER(KIND=JPIM) :: IN,IWIDTH,ILEFT,IMID,IRIGHT,IOUT,I1,I2,I,ISTART,IEND
INTEGER(KIND=JPIM) :: IDX,IPREV,IGROUP,INOUT,IKTOTAL,JK
INTEGER(KIND=JPIB) :: ICOUNT,IGATHER,IPACK_COL,IGROUP_SRC,ISOURCE

IN=PLAN%FINAL%COUNT
IF (IN <= 0) RETURN
ALLOCATE(IORDER(IN),ITEMP(IN))
DO I=1,IN
  IORDER(I)=I
ENDDO

! Sort final factors by output range so equal destinations can share one GEMM.
IWIDTH=1
DO WHILE(IWIDTH < IN)
  DO ILEFT=1,IN,2*IWIDTH
    IMID=MIN(ILEFT+IWIDTH-1,IN)
    IRIGHT=MIN(ILEFT+2*IWIDTH-1,IN)
    I1=ILEFT
    I2=IMID+1
    DO IOUT=ILEFT,IRIGHT
      IF (I1 > IMID) THEN
        ITEMP(IOUT)=IORDER(I2)
        I2=I2+1
      ELSEIF (I2 > IRIGHT) THEN
        ITEMP(IOUT)=IORDER(I1)
        I1=I1+1
      ELSEIF (FINAL_GROUP_LESS(PLAN%FINAL,IORDER(I1),IORDER(I2))) THEN
        ITEMP(IOUT)=IORDER(I1)
        I1=I1+1
      ELSE
        ITEMP(IOUT)=IORDER(I2)
        I2=I2+1
      ENDIF
    ENDDO
  ENDDO
  IORDER=ITEMP
  IWIDTH=2*IWIDTH
ENDDO

IGROUP=1
IPREV=IORDER(1)
DO I=2,IN
  IDX=IORDER(I)
  IF (.NOT.FINAL_GROUP_SAME(PLAN%FINAL,IPREV,IDX)) IGROUP=IGROUP+1
  IPREV=IDX
ENDDO
PLAN%FINAL_FUSED%COUNT=IGROUP
PLAN%FINAL_ORIGINAL_COST=SUM(INT(PLAN%FINAL%N,JPIB)*INT(PLAN%FINAL%K,JPIB))
PLAN%FINAL_EXEC_COST=PLAN%FINAL_ORIGINAL_COST
PLAN%FINAL_DIRECT_GROUPS=IGROUP
IF (.NOT.PLAN%RECOMPRESS_FINAL .AND. IGROUP == IN) THEN
  PLAN%FUSE_FINAL=.FALSE.
  PLAN%FINAL_FUSED%COUNT=0
  DEALLOCATE(IORDER,ITEMP)
  RETURN
ENDIF
IF (PLAN%RECOMPRESS_FINAL) THEN
  CALL BUILD_RECOMPRESSED_FINAL(PLAN,KPOS,IORDER,IGROUP)
  DEALLOCATE(IORDER,ITEMP)
  RETURN
ENDIF
CALL ALLOC_GROUP(PLAN%FINAL_FUSED)
PLAN%FINAL_GATHER_COUNT=SUM(INT(PLAN%FINAL%K,JPIB))
ALLOCATE(PLAN%FINAL_GATHER_SRC(PLAN%FINAL_GATHER_COUNT),&
  & PLAN%FINAL_GATHER_DST(PLAN%FINAL_GATHER_COUNT))

I=1
IGROUP=0
IGATHER=0
IPACK_COL=0
DO WHILE(I <= IN)
  ISTART=I
  IDX=IORDER(I)
  INOUT=PLAN%FINAL%N(IDX)
  IKTOTAL=0
  DO WHILE(I <= IN)
    IF (.NOT.FINAL_GROUP_SAME(PLAN%FINAL,IORDER(ISTART),IORDER(I))) EXIT
    IKTOTAL=IKTOTAL+PLAN%FINAL%K(IORDER(I))
    I=I+1
  ENDDO
  IEND=I-1
  IGROUP=IGROUP+1
  IGROUP_SRC=IPACK_COL
  CALL SET_GROUP(PLAN%FINAL_FUSED,IGROUP,INOUT,IKTOTAL,INOUT,&
    & IGROUP_SRC,PLAN%FINAL%DST_COL(IDX),KPOS-1)
  DO IOUT=ISTART,IEND
    IDX=IORDER(IOUT)
    ICOUNT=INT(INOUT,JPIB)*INT(PLAN%FINAL%K(IDX),JPIB)
    ISOURCE=PLAN%FINAL%FACTOR_OFFSET(IDX)+1
    PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=&
      & PLAN%FACTORS(ISOURCE:ISOURCE+ICOUNT-1)
    KPOS=KPOS+ICOUNT
    DO JK=0,PLAN%FINAL%K(IDX)-1
      IGATHER=IGATHER+1
      PLAN%FINAL_GATHER_SRC(IGATHER)=PLAN%FINAL%SRC_COL(IDX)+JK
      PLAN%FINAL_GATHER_DST(IGATHER)=IPACK_COL
      IPACK_COL=IPACK_COL+1
    ENDDO
  ENDDO
ENDDO
DEALLOCATE(IORDER,ITEMP)
END SUBROUTINE BUILD_FUSED_FINAL

SUBROUTINE BUILD_RECOMPRESSED_FINAL(PLAN,KPOS,KORDER,KGROUPS)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(IN) :: KORDER(:),KGROUPS

INTEGER(KIND=JPIM) :: I,ISTART,IEND,IDX,INOUT,IKTOTAL,IRANK
INTEGER(KIND=JPIM) :: J,JK,JI,IC,IGROUP,IPROJECT,IBASIS,IDIRECT
INTEGER(KIND=JPIM),ALLOCATABLE :: ICLIST(:)
INTEGER(KIND=JPIB) :: IGATHER,IPACK_COL,IGAMMA_COL,ISOURCE,ICOUNT
INTEGER(KIND=JPIB) :: IORIGINAL_COST,IRECOMPRESSED_COST,IOFF
REAL(KIND=JPRD) :: ZEPS,ZSELECT_RATIO
REAL(KIND=JPRD),ALLOCATABLE :: ZB(:,:),ZPNONIM(:,:),ZPROJ(:,:)
LOGICAL :: LSELECT

PLAN%FINAL_FUSED%COUNT=KGROUPS
PLAN%FINAL_PROJECT%COUNT=KGROUPS
PLAN%FINAL_BASIS%COUNT=KGROUPS
CALL ALLOC_GROUP(PLAN%FINAL_FUSED)
CALL ALLOC_GROUP(PLAN%FINAL_PROJECT)
CALL ALLOC_GROUP(PLAN%FINAL_BASIS)
PLAN%FINAL_GATHER_COUNT=SUM(INT(PLAN%FINAL%K,JPIB))
ALLOCATE(PLAN%FINAL_GATHER_SRC(PLAN%FINAL_GATHER_COUNT),&
  & PLAN%FINAL_GATHER_DST(PLAN%FINAL_GATHER_COUNT))

ZEPS=BUTTERFLY_FINAL_EPS()
ZSELECT_RATIO=BUTTERFLY_FINAL_SELECT_RATIO()
I=1
IGROUP=0
IPROJECT=0
IBASIS=0
IDIRECT=0
IGATHER=0
IPACK_COL=0
IGAMMA_COL=0
PLAN%FINAL_EXEC_COST=0
PLAN%FINAL_RECOMPRESSED_GROUPS=0
PLAN%FINAL_DIRECT_GROUPS=0
DO WHILE(I <= SIZE(KORDER))
  ISTART=I
  IDX=KORDER(I)
  INOUT=PLAN%FINAL%N(IDX)
  IKTOTAL=0
  DO WHILE(I <= SIZE(KORDER))
    IF (.NOT.FINAL_GROUP_SAME(PLAN%FINAL,KORDER(ISTART),KORDER(I))) EXIT
    IKTOTAL=IKTOTAL+PLAN%FINAL%K(KORDER(I))
    I=I+1
  ENDDO
  IEND=I-1
  IGROUP=IGROUP+1
  ALLOCATE(ZB(INOUT,IKTOTAL),ICLIST(IKTOTAL),&
    & ZPNONIM(MAX(1,MIN(INOUT,IKTOTAL)),MAX(1,IKTOTAL)))
  J=0
  DO JI=ISTART,IEND
    IDX=KORDER(JI)
    ISOURCE=PLAN%FINAL%FACTOR_OFFSET(IDX)+1
    DO JK=1,PLAN%FINAL%K(IDX)
      J=J+1
      ZB(:,J)=REAL(PLAN%FACTORS(ISOURCE+(JK-1)*INOUT:&
        & ISOURCE+JK*INOUT-1),JPRD)
      IGATHER=IGATHER+1
      PLAN%FINAL_GATHER_SRC(IGATHER)=PLAN%FINAL%SRC_COL(IDX)+JK-1
      PLAN%FINAL_GATHER_DST(IGATHER)=IPACK_COL
      IPACK_COL=IPACK_COL+1
    ENDDO
  ENDDO

  CALL COMPUTE_ID(ZEPS,INOUT,IKTOTAL,ZB,IRANK,ICLIST,ZPNONIM)
  IORIGINAL_COST=INT(INOUT,JPIB)*INT(IKTOTAL,JPIB)
  IRECOMPRESSED_COST=INT(IRANK,JPIB)*INT(INOUT+IKTOTAL,JPIB)
  LSELECT=IRANK < MIN(INOUT,IKTOTAL) .AND. &
    & REAL(IRECOMPRESSED_COST,JPRD) < ZSELECT_RATIO*REAL(IORIGINAL_COST,JPRD)
  IF (LSELECT) THEN
    ALLOCATE(ZPROJ(IKTOTAL,IRANK))
    ZPROJ=0.0_JPRD
    DO JI=1,IKTOTAL
      IC=ICLIST(JI)
      IF (JI <= IRANK) THEN
        ZPROJ(IC,JI)=1.0_JPRD
      ELSE
        ZPROJ(IC,1:IRANK)=ZPNONIM(1:IRANK,JI-IRANK)
      ENDIF
    ENDDO
    IOFF=KPOS-1
    ICOUNT=INT(IKTOTAL,JPIB)*INT(IRANK,JPIB)
    PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=&
      & RESHAPE(REAL(ZPROJ,JPRBT),[ICOUNT])
    KPOS=KPOS+ICOUNT
    IPROJECT=IPROJECT+1
    CALL SET_GROUP(PLAN%FINAL_PROJECT,IPROJECT,IRANK,IKTOTAL,IKTOTAL,&
      & IPACK_COL-IKTOTAL,IGAMMA_COL,IOFF)

    IOFF=KPOS-1
    ICOUNT=INT(INOUT,JPIB)*INT(IRANK,JPIB)
    PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=&
      & RESHAPE(REAL(ZB(:,ICLIST(1:IRANK)),JPRBT),[ICOUNT])
    KPOS=KPOS+ICOUNT
    IBASIS=IBASIS+1
    CALL SET_GROUP(PLAN%FINAL_BASIS,IBASIS,INOUT,IRANK,INOUT,&
      & IGAMMA_COL,PLAN%FINAL%DST_COL(IDX),IOFF)
    IGAMMA_COL=IGAMMA_COL+IRANK
    PLAN%FINAL_EXEC_COST=PLAN%FINAL_EXEC_COST+IRECOMPRESSED_COST
    PLAN%FINAL_RECOMPRESSED_GROUPS=PLAN%FINAL_RECOMPRESSED_GROUPS+1
    DEALLOCATE(ZPROJ)
  ELSE
    IOFF=KPOS-1
    PLAN%FACTORS(KPOS:KPOS+IORIGINAL_COST-1)=&
      & RESHAPE(REAL(ZB,JPRBT),[IORIGINAL_COST])
    KPOS=KPOS+IORIGINAL_COST
    IDIRECT=IDIRECT+1
    CALL SET_GROUP(PLAN%FINAL_FUSED,IDIRECT,INOUT,IKTOTAL,INOUT,&
      & IPACK_COL-IKTOTAL,PLAN%FINAL%DST_COL(IDX),IOFF)
    PLAN%FINAL_EXEC_COST=PLAN%FINAL_EXEC_COST+IORIGINAL_COST
    PLAN%FINAL_DIRECT_GROUPS=PLAN%FINAL_DIRECT_GROUPS+1
  ENDIF
  DEALLOCATE(ZB,ICLIST,ZPNONIM)
ENDDO
PLAN%FINAL_PROJECT%COUNT=IPROJECT
PLAN%FINAL_BASIS%COUNT=IBASIS
PLAN%FINAL_FUSED%COUNT=IDIRECT
IF (IPROJECT == 0 .AND. IDIRECT == PLAN%FINAL%COUNT) THEN
  PLAN%FUSE_FINAL=.FALSE.
  PLAN%RECOMPRESS_FINAL=.FALSE.
ENDIF
END SUBROUTINE BUILD_RECOMPRESSED_FINAL

LOGICAL FUNCTION FINAL_GROUP_LESS(GROUP,KI,KJ)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KJ
FINAL_GROUP_LESS=GROUP%DST_COL(KI) < GROUP%DST_COL(KJ) .OR. &
  & (GROUP%DST_COL(KI) == GROUP%DST_COL(KJ) .AND. &
  & GROUP%N(KI) <= GROUP%N(KJ))
END FUNCTION FINAL_GROUP_LESS

LOGICAL FUNCTION FINAL_GROUP_SAME(GROUP,KI,KJ)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
INTEGER(KIND=JPIM),INTENT(IN) :: KI,KJ
FINAL_GROUP_SAME=GROUP%DST_COL(KI) == GROUP%DST_COL(KJ) .AND. &
  & GROUP%N(KI) == GROUP%N(KJ)
END FUNCTION FINAL_GROUP_SAME

SUBROUTINE FILL_HYBRID(HYBRID,KMLOC,PLAN,KPOS,KPIVOT_POS,K0,KFINAL,KDENSE,&
  & KFUSED,KFW,KRO,KRE,LTRANSPOSED)
TYPE(HYBRID_MATRIX),INTENT(IN) :: HYBRID
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K0,KFINAL,KDENSE,KFUSED,KFW(:),KRO(:),KRE(:)
LOGICAL,INTENT(IN) :: LTRANSPOSED
INTEGER(KIND=JPIM) :: JB

DO JB=1,HYBRID%BLOCK_COUNT
  IF (HYBRID%BLOCKS(JB)%KIND == HYBRID_DENSE) THEN
    CALL FILL_DENSE(HYBRID%BLOCKS(JB),KMLOC,PLAN,KPOS,KDENSE,LTRANSPOSED)
  ELSEIF (FUSIBLE_LEAF(PLAN,HYBRID%BLOCKS(JB)%BUT)) THEN
    CALL FILL_FUSED_LEAF(HYBRID%BLOCKS(JB),KMLOC,PLAN,KPOS,KPIVOT_POS,KFUSED)
  ELSE
    CALL FILL_MATRIX(HYBRID%BLOCKS(JB)%BUT,KMLOC,&
      & HYBRID%BLOCKS(JB)%FIRST_ROW,HYBRID%BLOCKS(JB)%FIRST_COL,&
      & HYBRID%BLOCKS(JB)%WORK_BASE,PLAN,KPOS,KPIVOT_POS,K0,KFINAL,KFW,KRO,KRE,&
      & LTRANSPOSED)
  ENDIF
ENDDO
END SUBROUTINE FILL_HYBRID

SUBROUTINE FILL_FUSED_LEAF(BLOCK,KMLOC,PLAN,KPOS,KPIVOT_POS,KFUSED)
USE TPM_DISTR, ONLY: D
TYPE(HYBRID_BLOCK),INTENT(IN) :: BLOCK
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIM),INTENT(INOUT) :: KFUSED
INTEGER(KIND=JPIM) :: JK
INTEGER(KIND=JPIB) :: IPROJECTION,IPIVOT,IFINAL,ICOUNT
TYPE(NODE_TYPE),POINTER :: YNODE

DO JK=1,BLOCK%BUT%SLEV(0)%IK
  YNODE=>BLOCK%BUT%SLEV(0)%NODE(1,JK)
  CALL PACK_PLAN_PROJECTION(YNODE,PLAN,KPOS,KPIVOT_POS,IPROJECTION,IPIVOT)
  IFINAL=KPOS-1
  ICOUNT=INT(YNODE%IROWS,JPIB)*INT(YNODE%IRANK,JPIB)
  PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=RESHAPE(REAL(YNODE%B,JPRBT),[ICOUNT])
  KPOS=KPOS+ICOUNT
  KFUSED=KFUSED+1
  PLAN%FUSED_LEAF%ROWS(KFUSED)=YNODE%IROWS
  PLAN%FUSED_LEAF%RANKS(KFUSED)=YNODE%IRANK
  PLAN%FUSED_LEAF%COLUMNS(KFUSED)=YNODE%ICOLS
  PLAN%FUSED_LEAF%INPUT_COL(KFUSED)=D%OFFSETS_GEMM1(KMLOC)+&
    & BLOCK%FIRST_COL+YNODE%IFCOL-2
  PLAN%FUSED_LEAF%OUTPUT_COL(KFUSED)=D%OFFSETS_GEMM2(KMLOC)+&
    & BLOCK%FIRST_ROW+YNODE%IFROW-2
  PLAN%FUSED_LEAF%FINAL_FACTOR_OFFSET(KFUSED)=IFINAL
  PLAN%FUSED_LEAF%PROJECTION_FACTOR_OFFSET(KFUSED)=IPROJECTION
  PLAN%FUSED_LEAF%PIVOT_OFFSET(KFUSED)=IPIVOT
ENDDO
END SUBROUTINE FILL_FUSED_LEAF

SUBROUTINE FILL_DENSE(BLOCK,KMLOC,PLAN,KPOS,KDENSE,LTRANSPOSED)
USE TPM_DISTR, ONLY: D
TYPE(HYBRID_BLOCK),INTENT(IN) :: BLOCK
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIM),INTENT(INOUT) :: KDENSE
LOGICAL,INTENT(IN) :: LTRANSPOSED
INTEGER(KIND=JPIB) :: IOFF
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)

ALLOCATE(ZT(BLOCK%NCOLS,BLOCK%NROWS))
ZT=TRANSPOSE(BLOCK%DENSE)
IOFF=KPOS-1
PLAN%FACTORS(KPOS:KPOS+BLOCK%DENSE_COST-1)=RESHAPE(ZT,[BLOCK%DENSE_COST])
KPOS=KPOS+BLOCK%DENSE_COST
KDENSE=KDENSE+1
IF (LTRANSPOSED) THEN
  CALL SET_GROUP(PLAN%DENSE,KDENSE,BLOCK%NROWS,BLOCK%NCOLS,BLOCK%NCOLS,&
    & D%OFFSETS_GEMM1(KMLOC)+BLOCK%FIRST_COL-1,&
    & D%OFFSETS_GEMM2(KMLOC)+BLOCK%FIRST_ROW-1,IOFF)
ELSE
  CALL SET_GROUP(PLAN%DENSE,KDENSE,BLOCK%NROWS,BLOCK%NCOLS,BLOCK%NCOLS,&
    & D%OFFSETS_GEMM2(KMLOC)+BLOCK%FIRST_COL-1,&
    & D%OFFSETS_GEMM1(KMLOC)+BLOCK%FIRST_ROW-1,IOFF)
ENDIF
DEALLOCATE(ZT)
END SUBROUTINE FILL_DENSE

SUBROUTINE FILL_MATRIX(BUT,KMLOC,KFIRST_ROW,KFIRST_COL,KWORK_BASE,&
  & PLAN,KPOS,KPIVOT_POS,K0,KFINAL,KFW,KRO,KRE,LTRANSPOSED)
USE TPM_DISTR, ONLY: D
TYPE(BUTTERFLY_STRUCT),INTENT(IN) :: BUT
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC,KFIRST_ROW,KFIRST_COL
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K0,KFINAL,KFW(:),KRO(:),KRE(:)
LOGICAL,INTENT(IN) :: LTRANSPOSED
INTEGER(KIND=JPIM) :: JL,JJ,JK,IRANKL,IRANKR
INTEGER(KIND=JPIB) :: IOFF,IPIVOT_OFF,ISRC,IDST
TYPE(NODE_TYPE),POINTER :: YNODE,YLEFT,YRIGHT

DO JK=1,BUT%SLEV(0)%IK
  YNODE=>BUT%SLEV(0)%NODE(1,JK)
  CALL PACK_PLAN_PROJECTION(YNODE,PLAN,KPOS,KPIVOT_POS,IOFF,IPIVOT_OFF)
  K0=K0+1
  IF (LTRANSPOSED) THEN
    ISRC=D%OFFSETS_GEMM1(KMLOC)+KFIRST_COL+YNODE%IFCOL-2
  ELSE
    ISRC=D%OFFSETS_GEMM2(KMLOC)+KFIRST_COL+YNODE%IFCOL-2
  ENDIF
  IDST=KWORK_BASE+YNODE%IOFFBETA
  CALL SET_GROUP(PLAN%LEVEL0,K0,YNODE%IRANK,YNODE%ICOLS,YNODE%ICOLS,&
    & ISRC,IDST,IOFF,IPIVOT_OFF)
ENDDO

DO JL=1,BUT%N_LEVELS
  DO JK=1,BUT%SLEV(JL)%IK
    DO JJ=1,BUT%SLEV(JL)%IJ
      YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
      YLEFT=>BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK-1)
      IRANKL=YLEFT%IRANK
      IRANKR=0
      IF (2*JK <= BUT%SLEV(JL-1)%IK) THEN
        YRIGHT=>BUT%SLEV(JL-1)%NODE((JJ+1)/2,2*JK)
        IRANKR=YRIGHT%IRANK
      ENDIF
      CALL PACK_PLAN_PROJECTION(YNODE,PLAN,KPOS,KPIVOT_POS,IOFF,IPIVOT_OFF)
      ISRC=KWORK_BASE+YLEFT%IOFFBETA
      IDST=KWORK_BASE+YNODE%IOFFBETA
      KFW(JL)=KFW(JL)+1
      CALL SET_GROUP(PLAN%LEVEL(JL)%FWD,KFW(JL),YNODE%IRANK,IRANKL+IRANKR,&
        & IRANKL+IRANKR,ISRC,IDST,IOFF,IPIVOT_OFF)
      IF (MOD(JJ,2) == 1) THEN
        KRO(JL)=KRO(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%REV_ODD,KRO(JL),YNODE%IRANK,&
          & IRANKL+IRANKR,IRANKL+IRANKR,ISRC,IDST,IOFF,IPIVOT_OFF)
      ELSE
        KRE(JL)=KRE(JL)+1
        CALL SET_GROUP(PLAN%LEVEL(JL)%REV_EVEN,KRE(JL),YNODE%IRANK,&
          & IRANKL+IRANKR,IRANKL+IRANKR,ISRC,IDST,IOFF,IPIVOT_OFF)
      ENDIF
    ENDDO
  ENDDO
ENDDO

JL=BUT%N_LEVELS
DO JK=1,BUT%SLEV(JL)%IK
  DO JJ=1,BUT%SLEV(JL)%IJ
    YNODE=>BUT%SLEV(JL)%NODE(JJ,JK)
    IOFF=KPOS-1
    PLAN%FACTORS(KPOS:KPOS+INT(YNODE%IROWS,JPIB)*YNODE%IRANK-1)=&
      & RESHAPE(REAL(YNODE%B,JPRBT),[YNODE%IROWS*YNODE%IRANK])
    KPOS=KPOS+INT(YNODE%IROWS,JPIB)*YNODE%IRANK
    KFINAL=KFINAL+1
    IF (LTRANSPOSED) THEN
      CALL SET_GROUP(PLAN%FINAL,KFINAL,YNODE%IROWS,YNODE%IRANK,YNODE%IROWS,&
        & KWORK_BASE+YNODE%IOFFBETA,&
        & D%OFFSETS_GEMM2(KMLOC)+KFIRST_ROW+YNODE%IFROW-2,IOFF)
    ELSE
      CALL SET_GROUP(PLAN%FINAL,KFINAL,YNODE%IROWS,YNODE%IRANK,YNODE%IROWS,&
        & KWORK_BASE+YNODE%IOFFBETA,&
        & D%OFFSETS_GEMM1(KMLOC)+KFIRST_ROW+YNODE%IFROW-2,IOFF)
    ENDIF
  ENDDO
ENDDO
END SUBROUTINE FILL_MATRIX

SUBROUTINE PACK_PLAN_PROJECTION(NODE,PLAN,KPOS,KPIVOT_POS,KOFFSET,KPIVOT_OFFSET)
TYPE(NODE_TYPE),INTENT(IN) :: NODE
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS,KPIVOT_POS
INTEGER(KIND=JPIB),INTENT(OUT) :: KOFFSET,KPIVOT_OFFSET
INTEGER(KIND=JPIB) :: ICOUNT

IF (.NOT.PLAN%COMPACT_ID) THEN
  CALL PACK_PROJECTION(NODE,PLAN%FACTORS,KPOS,KOFFSET)
  KPIVOT_OFFSET=-1_JPIB
  RETURN
ENDIF

KOFFSET=KPOS-1
ICOUNT=INT(NODE%IRANK,JPIB)*INT(NODE%ICOLS-NODE%IRANK,JPIB)
IF (ICOUNT > 0) THEN
  PLAN%FACTORS(KPOS:KPOS+ICOUNT-1)=NODE%PNONIM(1:ICOUNT)
  KPOS=KPOS+ICOUNT
ENDIF
KPIVOT_OFFSET=KPIVOT_POS-1
PLAN%PIVOTS(KPIVOT_POS:KPIVOT_POS+NODE%ICOLS-1)=NODE%ICLIST-1
KPIVOT_POS=KPIVOT_POS+NODE%ICOLS
END SUBROUTINE PACK_PLAN_PROJECTION

SUBROUTINE PACK_PROJECTION(NODE,PFACTORS,KPOS,KOFFSET)
TYPE(NODE_TYPE),INTENT(IN) :: NODE
REAL(KIND=JPRBT),INTENT(INOUT) :: PFACTORS(:)
INTEGER(KIND=JPIB),INTENT(INOUT) :: KPOS
INTEGER(KIND=JPIB),INTENT(OUT) :: KOFFSET
REAL(KIND=JPRBT),ALLOCATABLE :: ZT(:,:)
INTEGER(KIND=JPIM) :: JI,JR,IC

ALLOCATE(ZT(NODE%ICOLS,NODE%IRANK))
ZT=ZERO
DO JI=1,NODE%ICOLS
  IC=NODE%ICLIST(JI)
  IF (JI <= NODE%IRANK) THEN
    ZT(IC,JI)=ONE
  ELSE
    DO JR=1,NODE%IRANK
      ZT(IC,JR)=NODE%PNONIM((JI-NODE%IRANK-1)*NODE%IRANK+JR)
    ENDDO
  ENDIF
ENDDO
KOFFSET=KPOS-1
PFACTORS(KPOS:KPOS+INT(NODE%ICOLS,JPIB)*NODE%IRANK-1)=&
  & RESHAPE(ZT,[NODE%ICOLS*NODE%IRANK])
KPOS=KPOS+INT(NODE%ICOLS,JPIB)*NODE%IRANK
DEALLOCATE(ZT)
END SUBROUTINE PACK_PROJECTION

FUNCTION BUTTERFLY_WORK_COLUMNS() RESULT(KCOLS)
USE TPM_FLT, ONLY: S
INTEGER(KIND=JPIB) :: KCOLS
KCOLS=MAX(S%PLAN_A%WORK_COLS,S%PLAN_S%WORK_COLS,&
  & S%PLAN_DIRECT_A%WORK_COLS,S%PLAN_DIRECT_S%WORK_COLS)
END FUNCTION BUTTERFLY_WORK_COLUMNS

SUBROUTINE APPLY_BUTTERFLY_INVERSE(PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PIN(:),POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KIN_BASE,KOUT_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

IF (.NOT.PLAN%DENSE_DISJOINT) &
  & CALL ZERO_COLUMNS(POUT,KLD,KOUT_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .FALSE.,.FALSE.,MERGE(ZERO,ONE,PLAN%DENSE_DISJOINT),&
  & ISTREAM,KBLAS_BASE-1,ALLOCATOR,&
  & .NOT.PLAN%DENSE_DISJOINT)
CALL RUN_PROJECTION(PLAN%LEVEL0,PLAN,PIN,POUT,KLD,0_JPIB,KOUT_BASE,&
  & KOUT_BASE+PLAN%BETA_COLS,&
  & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE,ALLOCATOR)
DO JL=1,PLAN%MAX_LEVELS
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,POUT,PIN,KLD,KOUT_BASE,KIN_BASE,&
      & KIN_BASE+PLAN%BETA_COLS,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+2*JL-1,ALLOCATOR)
  ELSE
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,PIN,POUT,KLD,KIN_BASE,KOUT_BASE,&
      & KOUT_BASE+PLAN%BETA_COLS,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+2*JL-1,ALLOCATOR)
  ENDIF
ENDDO
CALL COPY_COLUMNS(POUT,PIN,KLD,KOUT_BASE,KIN_BASE,0_JPIB,&
  & PLAN%EVEN_BETA_COLS,KASYNC)
CALL RUN_GROUP(PLAN%FINAL,PLAN,PIN,POUT,KLD,KIN_BASE,0_JPIB,&
  & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
END SUBROUTINE APPLY_BUTTERFLY_INVERSE

SUBROUTINE APPLY_BUTTERFLY_DIRECT(PLAN,PIN,POUT,KLD,KWORK_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

IF (.NOT.PLAN%DENSE_DISJOINT) &
  & CALL ZERO_COLUMNS(POUT,KLD,KWORK_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .TRUE.,.FALSE.,MERGE(ZERO,ONE,PLAN%DENSE_DISJOINT),&
  & ISTREAM,KBLAS_BASE+39,ALLOCATOR,&
  & .NOT.PLAN%DENSE_DISJOINT)
CALL RUN_GROUP(PLAN%FINAL,PLAN,PIN,POUT,KLD,0_JPIB,KWORK_BASE,&
  & .TRUE.,.TRUE.,ZERO,ISTREAM,KBLAS_BASE+40,ALLOCATOR)
CALL COPY_COLUMNS_INPLACE(POUT,KLD,KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,&
  & PLAN%EVEN_BETA_COLS,&
  & PLAN%BETA_COLS-PLAN%EVEN_BETA_COLS,KASYNC)
DO JL=PLAN%MAX_LEVELS,1,-1
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_ODD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,KWORK_BASE+2*PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+40+2*JL-1,ALLOCATOR)
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_EVEN,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,KWORK_BASE+2*PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+40+2*JL,ALLOCATOR)
  ELSE
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_ODD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE+2*PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE+40+2*JL-1,ALLOCATOR)
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%REV_EVEN,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE,KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE+2*PLAN%BETA_COLS,&
      & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+40+2*JL,ALLOCATOR)
  ENDIF
ENDDO
CALL RUN_PROJECTION(PLAN%LEVEL0,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
  & KWORK_BASE+2*PLAN%BETA_COLS,&
  & .TRUE.,.FALSE.,ONE,ISTREAM,KBLAS_BASE+70,ALLOCATOR,.TRUE.)
END SUBROUTINE APPLY_BUTTERFLY_DIRECT

SUBROUTINE APPLY_BUTTERFLY_DIRECT_FORWARD(PLAN,PIN,POUT,KLD,KWORK_BASE,&
  & KASYNC,KBLAS_BASE,ALLOCATOR)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
#ifdef ACCGPU
USE OPENACC_LIB, ONLY: ACC_GET_HIP_STREAM
#endif
USE ISO_C_BINDING, ONLY: C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC,KBLAS_BASE
INTEGER(KIND=JPIB),INTENT(IN) :: KWORK_BASE
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM) :: JL
INTEGER(C_INTPTR_T) :: ISTREAM

IF (.NOT.PLAN%ENABLED) RETURN
#ifdef ACCGPU
ISTREAM=INT(ACC_GET_HIP_STREAM(INT(KASYNC,C_INT)),C_INTPTR_T)
#else
ISTREAM=0_C_INTPTR_T
#endif

IF (.NOT.PLAN%DENSE_DISJOINT) &
  & CALL ZERO_COLUMNS(POUT,KLD,KWORK_BASE,KASYNC)
CALL RUN_GROUP(PLAN%DENSE,PLAN,PIN,POUT,KLD,0_JPIB,0_JPIB,&
  & .FALSE.,.FALSE.,MERGE(ZERO,ONE,PLAN%DENSE_DISJOINT),&
  & ISTREAM,KBLAS_BASE-1,ALLOCATOR,&
  & .NOT.PLAN%DENSE_DISJOINT)
CALL RUN_FUSED_LEAF(PLAN,PIN,POUT,KLD,ISTREAM)
CALL RUN_PROJECTION(PLAN%LEVEL0,PLAN,PIN,POUT,KLD,0_JPIB,KWORK_BASE,&
  & KWORK_BASE+2*PLAN%BETA_COLS,&
  & .FALSE.,.FALSE.,ZERO,ISTREAM,KBLAS_BASE,ALLOCATOR)
DO JL=1,PLAN%MAX_LEVELS
  IF (MOD(JL,2) == 1) THEN
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,POUT,POUT,KLD,KWORK_BASE,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE+2*PLAN%BETA_COLS,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,&
      & KBLAS_BASE+2*JL-1,ALLOCATOR)
  ELSE
    CALL RUN_PROJECTION(PLAN%LEVEL(JL)%FWD,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,KWORK_BASE+2*PLAN%BETA_COLS,&
      & .FALSE.,.FALSE.,ZERO,ISTREAM,&
      & KBLAS_BASE+2*JL-1,ALLOCATOR)
  ENDIF
ENDDO
CALL COPY_COLUMNS_INPLACE(POUT,KLD,KWORK_BASE,&
  & KWORK_BASE+PLAN%BETA_COLS,0_JPIB,PLAN%EVEN_BETA_COLS,KASYNC)
IF (PLAN%FUSE_FINAL) THEN
  CALL GATHER_FINAL_COLUMNS(POUT,KLD,KWORK_BASE+PLAN%BETA_COLS,KWORK_BASE,&
    & PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST,&
    & PLAN%FINAL_GATHER_COUNT,KASYNC)
  IF (PLAN%RECOMPRESS_FINAL) THEN
    CALL RUN_GROUP(PLAN%FINAL_PROJECT,PLAN,POUT,POUT,KLD,KWORK_BASE,&
      & KWORK_BASE+PLAN%BETA_COLS,.FALSE.,.FALSE.,ZERO,ISTREAM,&
      & KBLAS_BASE+29,ALLOCATOR)
    CALL RUN_GROUP(PLAN%FINAL_FUSED,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
      & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
    CALL RUN_GROUP(PLAN%FINAL_BASIS,PLAN,POUT,POUT,KLD,&
      & KWORK_BASE+PLAN%BETA_COLS,0_JPIB,.FALSE.,.TRUE.,ONE,ISTREAM,&
      & KBLAS_BASE+31,ALLOCATOR,.TRUE.)
  ELSE
    CALL RUN_GROUP(PLAN%FINAL_FUSED,PLAN,POUT,POUT,KLD,KWORK_BASE,0_JPIB,&
      & .FALSE.,.TRUE.,ONE,ISTREAM,KBLAS_BASE+30,ALLOCATOR,.TRUE.)
  ENDIF
ELSE
  CALL RUN_GROUP(PLAN%FINAL,PLAN,POUT,POUT,KLD,&
    & KWORK_BASE+PLAN%BETA_COLS,0_JPIB,.FALSE.,.TRUE.,ONE,ISTREAM,&
    & KBLAS_BASE+30,ALLOCATOR,.TRUE.)
ENDIF
END SUBROUTINE APPLY_BUTTERFLY_DIRECT_FORWARD

SUBROUTINE GATHER_FINAL_COLUMNS(PBUF,KLD,KSRC_BASE,KDST_BASE,&
  & KSRC,KDST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KCOUNT
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC(:),KDST(:)
INTEGER(KIND=JPIB) :: J,ICOL,IFIELD,JEND

IF (KCOUNT <= 0) RETURN
JEND=INT(KLD,JPIB)*KCOUNT
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF,KSRC,KDST) &
!$ACC& ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JEND,KLD,KSRC_BASE,KDST_BASE) &
!$OMP& MAP(PRESENT:PBUF,KSRC,KDST)
#endif
DO J=1,JEND
  ICOL=(J-1)/KLD+1
  IFIELD=MOD(J-1,INT(KLD,JPIB))+1
  PBUF((KDST_BASE+KDST(ICOL))*KLD+IFIELD)=&
    & PBUF((KSRC_BASE+KSRC(ICOL))*KLD+IFIELD)
ENDDO
END SUBROUTINE GATHER_FINAL_COLUMNS

SUBROUTINE ZERO_COLUMNS(PBUF,KLD,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KCOUNT
INTEGER(KIND=JPIB) :: J,JEND

JEND=INT(KLD,JPIB)*KCOUNT
IF (JEND <= 0) RETURN
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JEND) MAP(PRESENT:PBUF)
#endif
DO J=1,JEND
  PBUF(J)=ZERO
ENDDO
END SUBROUTINE ZERO_COLUMNS

SUBROUTINE COPY_COLUMNS(PSRC,PDST,KLD,KSRC_BASE,KDST_BASE,KFIRST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PSRC(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PDST(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KFIRST,KCOUNT
INTEGER(KIND=JPIB) :: J,JSTART,JEND
IF (KCOUNT <= 0) RETURN
JSTART=KFIRST*KLD+1
JEND=(KFIRST+KCOUNT)*KLD
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PSRC,PDST) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JSTART,JEND) MAP(PRESENT:PSRC,PDST)
#endif
DO J=JSTART,JEND
  PDST(KDST_BASE*KLD+J)=PSRC(KSRC_BASE*KLD+J)
ENDDO
END SUBROUTINE COPY_COLUMNS

SUBROUTINE COPY_COLUMNS_INPLACE(PBUF,KLD,KSRC_BASE,KDST_BASE,KFIRST,KCOUNT,KASYNC)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KASYNC
INTEGER(KIND=JPIB),INTENT(IN) :: KSRC_BASE,KDST_BASE,KFIRST,KCOUNT
INTEGER(KIND=JPIB) :: J,JSTART,JEND
IF (KCOUNT <= 0) RETURN
JSTART=KFIRST*KLD+1
JEND=(KFIRST+KCOUNT)*KLD
#ifdef ACCGPU
!$ACC PARALLEL LOOP PRESENT(PBUF) ASYNC(KASYNC)
#endif
#ifdef OMPGPU
!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO DEFAULT(NONE) FIRSTPRIVATE(JSTART,JEND) MAP(PRESENT:PBUF)
#endif
DO J=JSTART,JEND
  PBUF(KDST_BASE*KLD+J)=PBUF(KSRC_BASE*KLD+J)
ENDDO
END SUBROUTINE COPY_COLUMNS_INPLACE

SUBROUTINE RUN_FUSED_LEAF(PLAN,PIN,POUT,KLD,KSTREAM)
USE ISO_C_BINDING, ONLY: C_LOC,C_INT,C_INTPTR_T
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD
INTEGER(C_INTPTR_T),INTENT(IN) :: KSTREAM

IF (PLAN%FUSED_LEAF%COUNT <= 0) RETURN
#if defined(CUDAGPU) && !defined(TRANS_SINGLE)
ASSOCIATE(PFACTORS=>PLAN%FACTORS,PPIVOTS=>PLAN%PIVOTS,&
  & GR=>PLAN%FUSED_LEAF%ROWS,GK=>PLAN%FUSED_LEAF%RANKS,&
  & GC=>PLAN%FUSED_LEAF%COLUMNS,GI=>PLAN%FUSED_LEAF%INPUT_COL,&
  & GO=>PLAN%FUSED_LEAF%OUTPUT_COL,GF=>PLAN%FUSED_LEAF%FINAL_FACTOR_OFFSET,&
  & GP=>PLAN%FUSED_LEAF%PROJECTION_FACTOR_OFFSET,&
  & GV=>PLAN%FUSED_LEAF%PIVOT_OFFSET)
#ifdef ACCGPU
!$ACC HOST_DATA USE_DEVICE(PIN,PFACTORS,POUT,GR,GK,GC,GI,GO,GF,GP,GV,PPIVOTS)
#endif
#ifdef OMPGPU
!$OMP TARGET DATA USE_DEVICE_ADDR(PIN,PFACTORS,POUT,GR,GK,GC,GI,GO,GF,GP,GV,PPIVOTS)
#endif
CALL BUTTERFLY_FUSED_LEAF_DIRECT_C(C_LOC(PIN),C_LOC(PFACTORS),C_LOC(POUT),&
  & INT(KLD,C_INT),GR,GK,GC,GI,GO,GF,GP,GV,PPIVOTS,&
  & INT(PLAN%FUSED_LEAF%COUNT,C_INT),INT(PLAN%FUSED_LEAF%MAX_RANK,C_INT),KSTREAM)
#ifdef OMPGPU
!$OMP END TARGET DATA
#endif
#ifdef ACCGPU
!$ACC END HOST_DATA
#endif
END ASSOCIATE
#endif
END SUBROUTINE RUN_FUSED_LEAF

SUBROUTINE RUN_PROJECTION(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,KADD_SCRATCH,LREVERSE,&
  & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
USE HICBLAS_MOD, ONLY: HIP_DGEMM_GROUPED_ASYNC
USE TPM_GEN, ONLY: NCUR_RESOL
USE ISO_C_BINDING, ONLY: C_LOC,C_INT,C_INT64_T,C_INTPTR_T
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PA(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PC(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KBLAS
INTEGER(KIND=JPIB),INTENT(IN) :: KADD_A,KADD_C,KADD_SCRATCH
LOGICAL,INTENT(IN) :: LREVERSE,LFACTOR_TRANSPOSED
REAL(KIND=JPRBT),INTENT(IN) :: PBETA
INTEGER(C_INTPTR_T),INTENT(IN) :: KSTREAM
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
LOGICAL,INTENT(IN),OPTIONAL :: LORDERED
INTEGER(KIND=JPIM) :: IN(GROUP%COUNT),IK(GROUP%COUNT),ILDB(GROUP%COUNT),IMAX_N,IMAX_K
INTEGER(KIND=JPIB) :: IOFFA(GROUP%COUNT),IOFFB(GROUP%COUNT),IOFFC(GROUP%COUNT)

IF (GROUP%COUNT <= 0) RETURN
IMAX_N=MAXVAL(GROUP%N)
IMAX_K=MAXVAL(GROUP%K)
IF (.NOT.PLAN%COMPACT_ID .OR. LFACTOR_TRANSPOSED) THEN
  IF (PRESENT(LORDERED)) THEN
    CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
      & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
  ELSE
    CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
      & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR)
  ENDIF
  RETURN
ENDIF

#ifdef CUDAGPU
ASSOCIATE(PFACTORS=>PLAN%FACTORS,PPIVOTS=>PLAN%PIVOTS,&
  & GN=>GROUP%N,GK=>GROUP%K,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
  & GF=>GROUP%FACTOR_OFFSET,GP=>GROUP%PIVOT_OFFSET,GW=>GROUP%SCRATCH_OFFSET,&
  & GTG=>GROUP%TILE_GROUP,GTS=>GROUP%TILE_START)
ILDB=GROUP%N
IOFFB=GROUP%FACTOR_OFFSET
IF (LREVERSE) THEN
  IN=GROUP%K-GROUP%N
  IK=GROUP%N
  IOFFA=(GROUP%DST_COL+KADD_A)*KLD
  IOFFC=(KADD_SCRATCH+GROUP%SCRATCH_OFFSET)*KLD
ELSE
  IN=GROUP%N
  IK=GROUP%K-GROUP%N
  IOFFA=(KADD_SCRATCH+GROUP%SCRATCH_OFFSET)*KLD
  IOFFC=(GROUP%DST_COL+KADD_C)*KLD
ENDIF
#ifdef ACCGPU
!$ACC HOST_DATA USE_DEVICE(PA,PC,PFACTORS,PPIVOTS,GN,GK,GS,GD,GF,GP,GW,GTG,GTS)
#endif
#ifdef OMPGPU
!$OMP TARGET DATA USE_DEVICE_ADDR(PA,PC,PFACTORS,PPIVOTS,GN,GK,GS,GD,GF,GP,GW,GTG,GTS)
#endif
IF (LREVERSE .AND. PLAN%FUSE_REVERSE) THEN
  CALL BUTTERFLY_COMPACT_REVERSE_C(C_LOC(PA),C_LOC(PFACTORS),C_LOC(PC),&
    & INT(KLD,C_INT),GN,GK,GS,GD,GP,GF,PPIVOTS,INT(KADD_A,C_INT64_T),&
    & INT(KADD_C,C_INT64_T),INT(GROUP%COUNT,C_INT),INT(IMAX_K,C_INT),&
    & PBETA,KSTREAM)
ELSEIF (.NOT.LREVERSE .AND. PLAN%NATIVE_GROUPED) THEN
  CALL BUTTERFLY_COMPACT_PROJECTION_C(C_LOC(PA),C_LOC(PFACTORS),C_LOC(PC),&
    & INT(KLD,C_INT),GN,GK,GS,GD,GP,GF,PPIVOTS,INT(KADD_A,C_INT64_T),&
    & INT(KADD_C,C_INT64_T),INT(GROUP%COUNT,C_INT),INT(IMAX_N,C_INT),PBETA,KSTREAM)
ELSE
  IF (.NOT.LREVERSE) &
    & CALL BUTTERFLY_PROJECTION_C(C_LOC(PA),C_LOC(PC),INT(KLD,C_INT),GN,GK,GS,GD,&
    & GP,GW,GTG,GTS,PPIVOTS,INT(KADD_A,C_INT64_T),INT(KADD_C,C_INT64_T),&
    & INT(KADD_SCRATCH,C_INT64_T),INT(GROUP%TILE_COUNT,C_INT),0_C_INT,PBETA,KSTREAM)
  IF (GROUP%SCRATCH_COLS > 0 .AND. LREVERSE) THEN
    CALL HIP_DGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N','N',KLD,IN,IK,ONE,&
      & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),ILDB,IOFFB,ZERO,C_LOC(PC),KLD,&
      & IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
  ELSEIF (GROUP%SCRATCH_COLS > 0) THEN
    CALL HIP_DGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N','T',KLD,IN,IK,ONE,&
      & C_LOC(PC),KLD,IOFFA,C_LOC(PFACTORS),ILDB,IOFFB,ONE,C_LOC(PC),KLD,&
      & IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
  ENDIF
  IF (LREVERSE) &
    & CALL BUTTERFLY_PROJECTION_C(C_LOC(PA),C_LOC(PC),INT(KLD,C_INT),GN,GK,GS,GD,&
    & GP,GW,GTG,GTS,PPIVOTS,INT(KADD_A,C_INT64_T),INT(KADD_C,C_INT64_T),&
    & INT(KADD_SCRATCH,C_INT64_T),INT(GROUP%TILE_COUNT,C_INT),1_C_INT,PBETA,KSTREAM)
ENDIF
#ifdef OMPGPU
!$OMP END TARGET DATA
#endif
#ifdef ACCGPU
!$ACC END HOST_DATA
#endif
END ASSOCIATE
#else
IF (PRESENT(LORDERED)) THEN
  CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
    & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
ELSE
  CALL RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
    & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR)
ENDIF
#endif
END SUBROUTINE RUN_PROJECTION

SUBROUTINE RUN_GROUP(GROUP,PLAN,PA,PC,KLD,KADD_A,KADD_C,LREVERSE,&
  & LFACTOR_TRANSPOSED,PBETA,KSTREAM,KBLAS,ALLOCATOR,LORDERED)
USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR
USE HICBLAS_MOD, ONLY: HIP_DGEMM_GROUPED_ASYNC,HIP_SGEMM_GROUPED_ASYNC,&
  & HIP_DGEMM_GROUPED_ORDERED_ASYNC
USE TPM_GEN, ONLY: NCUR_RESOL
USE ISO_C_BINDING, ONLY: C_LOC,C_INT,C_INT64_T,C_INTPTR_T
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PA(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PC(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KBLAS
INTEGER(KIND=JPIB),INTENT(IN) :: KADD_A,KADD_C
LOGICAL,INTENT(IN) :: LREVERSE,LFACTOR_TRANSPOSED
REAL(KIND=JPRBT),INTENT(IN) :: PBETA
INTEGER(C_INTPTR_T),INTENT(IN) :: KSTREAM
TYPE(BUFFERED_ALLOCATOR),INTENT(IN) :: ALLOCATOR
LOGICAL,INTENT(IN),OPTIONAL :: LORDERED
INTEGER(KIND=JPIM) :: IN(GROUP%COUNT),IK(GROUP%COUNT)
INTEGER(KIND=JPIB) :: IOFFA(GROUP%COUNT),IOFFC(GROUP%COUNT)
CHARACTER(LEN=1) :: CTB
LOGICAL :: LLORDERED

IF (GROUP%COUNT <= 0) RETURN
LLORDERED=.FALSE.
IF (PRESENT(LORDERED)) LLORDERED=LORDERED
#ifdef CUDAGPU
IF (PLAN%NATIVE_GROUPED .AND. .NOT.LREVERSE .AND. &
  & (.NOT.LLORDERED .OR. PBETA == ONE)) THEN
  ASSOCIATE(PFACTORS=>PLAN%FACTORS,GN=>GROUP%N,GK=>GROUP%K,&
    & GLDB=>GROUP%LDB,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
    & GF=>GROUP%FACTOR_OFFSET)
#ifdef ACCGPU
  !$ACC HOST_DATA USE_DEVICE(PA,PFACTORS,PC,GN,GK,GLDB,GS,GD,GF)
#endif
#ifdef OMPGPU
  !$OMP TARGET DATA USE_DEVICE_ADDR(PA,PFACTORS,PC,GN,GK,GLDB,GS,GD,GF)
#endif
  CALL BUTTERFLY_GROUPED_GEMM_C(C_LOC(PA),C_LOC(PFACTORS),C_LOC(PC),&
    & INT(KLD,C_INT),GN,GK,GLDB,GS,GD,GF,INT(KADD_A,C_INT64_T),&
    & INT(KADD_C,C_INT64_T),INT(GROUP%COUNT,C_INT),&
    & INT(MAXVAL(GROUP%N),C_INT),MERGE(1_C_INT,0_C_INT,LFACTOR_TRANSPOSED),&
    & MERGE(1_C_INT,0_C_INT,LLORDERED),PBETA,KSTREAM)
#ifdef OMPGPU
  !$OMP END TARGET DATA
#endif
#ifdef ACCGPU
  !$ACC END HOST_DATA
#endif
  END ASSOCIATE
  RETURN
ENDIF
#endif
IF (LREVERSE) THEN
  IN=GROUP%K
  IK=GROUP%N
  IOFFA=(GROUP%DST_COL+KADD_A)*KLD
  IOFFC=(GROUP%SRC_COL+KADD_C)*KLD
  IF (LFACTOR_TRANSPOSED) THEN
    CTB='N'
  ELSE
    CTB='T'
  ENDIF
ELSE
  IN=GROUP%N
  IK=GROUP%K
  IOFFA=(GROUP%SRC_COL+KADD_A)*KLD
  IOFFC=(GROUP%DST_COL+KADD_C)*KLD
  IF (LFACTOR_TRANSPOSED) THEN
    CTB='T'
  ELSE
    CTB='N'
  ENDIF
ENDIF

ASSOCIATE(PFACTORS=>PLAN%FACTORS)
#ifdef OMPGPU
!$OMP TARGET DATA USE_DEVICE_ADDR(PA,PFACTORS,PC)
#endif
#ifdef ACCGPU
!$ACC HOST_DATA USE_DEVICE(PA,PFACTORS,PC)
#endif
#ifdef TRANS_SINGLE
CALL HIP_SGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
  & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
  & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
#else
IF (LLORDERED) THEN
  CALL HIP_DGEMM_GROUPED_ORDERED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
    & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
    & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
ELSE
  CALL HIP_DGEMM_GROUPED_ASYNC(NCUR_RESOL,KBLAS,'N',CTB,KLD,IN,IK,ONE,&
    & C_LOC(PA),KLD,IOFFA,C_LOC(PFACTORS),GROUP%LDB,GROUP%FACTOR_OFFSET,PBETA,&
    & C_LOC(PC),KLD,IOFFC,GROUP%COUNT,KSTREAM,C_LOC(ALLOCATOR%PTR))
ENDIF
#endif
#ifdef ACCGPU
!$ACC END HOST_DATA
#endif
#ifdef OMPGPU
!$OMP END TARGET DATA
#endif
END ASSOCIATE
END SUBROUTINE RUN_GROUP

SUBROUTINE FREE_GPU_BUTTERFLY_PLANS
USE TPM_FLT, ONLY: S
USE TPM_DISTR, ONLY: D
INTEGER(KIND=JPIM) :: JMLOC

CALL FREE_ONE_PLAN(S%PLAN_A)
CALL FREE_ONE_PLAN(S%PLAN_S)
CALL FREE_ONE_PLAN(S%PLAN_DIRECT_A)
CALL FREE_ONE_PLAN(S%PLAN_DIRECT_S)
IF (ALLOCATED(S%FA)) THEN
  DO JMLOC=1,D%NUMP
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_A)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_S)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_A)
    CALL FREE_HYBRID(S%FA(JMLOC)%YHYBRID_DIRECT_S)
  ENDDO
ENDIF
END SUBROUTINE FREE_GPU_BUTTERFLY_PLANS

SUBROUTINE FREE_ONE_PLAN(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(INOUT) :: PLAN
INTEGER(KIND=JPIM) :: JL
IF (PLAN%NATIVE_GROUPED) CALL EXIT_NATIVE_GROUPS_DEVICE(PLAN)
IF (PLAN%COMPACT_ID) CALL EXIT_COMPACT_GROUPS_DEVICE(PLAN)
IF (PLAN%FUSE_LEAF) CALL EXIT_FUSED_LEAF_DEVICE(PLAN%FUSED_LEAF)
#ifdef ACCGPU
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$ACC EXIT DATA DELETE(PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
!$ACC EXIT DATA DELETE(PLAN%FACTORS) IF(ASSOCIATED(PLAN%FACTORS))
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$ACC EXIT DATA DELETE(PLAN%PIVOTS)
ENDIF
#endif
#ifdef OMPGPU
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) THEN
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%FINAL_GATHER_SRC,PLAN%FINAL_GATHER_DST)
ENDIF
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%FACTORS) IF(ASSOCIATED(PLAN%FACTORS))
IF (ALLOCATED(PLAN%PIVOTS)) THEN
!$OMP TARGET EXIT DATA MAP(DELETE:PLAN%PIVOTS)
ENDIF
#endif
CALL FREE_GROUP(PLAN%LEVEL0)
CALL FREE_GROUP(PLAN%FINAL)
CALL FREE_GROUP(PLAN%FINAL_FUSED)
CALL FREE_GROUP(PLAN%FINAL_PROJECT)
CALL FREE_GROUP(PLAN%FINAL_BASIS)
CALL FREE_GROUP(PLAN%DENSE)
CALL FREE_FUSED_LEAF(PLAN%FUSED_LEAF)
IF (ALLOCATED(PLAN%LEVEL)) THEN
  DO JL=1,SIZE(PLAN%LEVEL)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%FWD)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%REV_ODD)
    CALL FREE_GROUP(PLAN%LEVEL(JL)%REV_EVEN)
  ENDDO
  DEALLOCATE(PLAN%LEVEL)
ENDIF
IF (ASSOCIATED(PLAN%FACTORS)) DEALLOCATE(PLAN%FACTORS)
IF (ALLOCATED(PLAN%PIVOTS)) DEALLOCATE(PLAN%PIVOTS)
IF (ALLOCATED(PLAN%FINAL_GATHER_SRC)) DEALLOCATE(PLAN%FINAL_GATHER_SRC)
IF (ALLOCATED(PLAN%FINAL_GATHER_DST)) DEALLOCATE(PLAN%FINAL_GATHER_DST)
IF (ALLOCATED(PLAN%USE_HYBRID)) DEALLOCATE(PLAN%USE_HYBRID)
IF (ALLOCATED(PLAN%DIRECT_CROP_FIRST)) DEALLOCATE(PLAN%DIRECT_CROP_FIRST)
IF (ALLOCATED(PLAN%DIRECT_CROP_COUNT)) DEALLOCATE(PLAN%DIRECT_CROP_COUNT)
IF (ALLOCATED(PLAN%DIRECT_GROUP_MLOC)) DEALLOCATE(PLAN%DIRECT_GROUP_MLOC)
IF (ALLOCATED(PLAN%DIRECT_GROUP_FIRST_ROW)) &
  & DEALLOCATE(PLAN%DIRECT_GROUP_FIRST_ROW)
IF (ALLOCATED(PLAN%DIRECT_GROUP_FIRST_COL)) &
  & DEALLOCATE(PLAN%DIRECT_GROUP_FIRST_COL)
IF (ALLOCATED(PLAN%DIRECT_GROUP_N)) DEALLOCATE(PLAN%DIRECT_GROUP_N)
IF (ALLOCATED(PLAN%DIRECT_GROUP_K)) DEALLOCATE(PLAN%DIRECT_GROUP_K)
PLAN%ENABLED=.FALSE.
PLAN%COMPACT_ID=.FALSE.
PLAN%DENSE_DISJOINT=.FALSE.
PLAN%DIRECT_INLINE_CROP=.FALSE.
PLAN%DIRECT_NATIVE_BLOCKS=.FALSE.
PLAN%NATIVE_GROUPED=.FALSE.
PLAN%FUSE_REVERSE=.FALSE.
PLAN%FUSE_FINAL=.FALSE.
PLAN%RECOMPRESS_FINAL=.FALSE.
PLAN%FUSE_LEAF=.FALSE.
PLAN%MAX_LEVELS=0
PLAN%CANDIDATE_COUNT=0
PLAN%SELECTED_COUNT=0
PLAN%DIRECT_GROUP_COUNT=0
PLAN%DENSE_BLOCKS=0
PLAN%LOW_RANK_BLOCKS=0
PLAN%BUTTERFLY_BLOCKS=0
PLAN%BETA_COLS=0
PLAN%EVEN_BETA_COLS=0
PLAN%WORK_COLS=0
PLAN%COMPACT_SCRATCH_COLS=0
PLAN%DENSE_COST=0
PLAN%HYBRID_COST=0
PLAN%DENSE_EXEC_COST=0
PLAN%HYBRID_EXEC_COST=0
PLAN%FINAL_FACTOR_VALUES=0
PLAN%PROJECTION_FULL_VALUES=0
PLAN%PROJECTION_COMPACT_VALUES=0
PLAN%FINAL_GATHER_COUNT=0
PLAN%FINAL_ORIGINAL_COST=0
PLAN%FINAL_EXEC_COST=0
PLAN%FINAL_RECOMPRESSED_GROUPS=0
PLAN%FINAL_DIRECT_GROUPS=0
END SUBROUTINE FREE_ONE_PLAN

SUBROUTINE EXIT_NATIVE_GROUPS_DEVICE(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
INTEGER(KIND=JPIM) :: JL

CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%DENSE)
CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%LEVEL0)
CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%FINAL)
CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%FINAL_FUSED)
CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%FINAL_PROJECT)
CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%FINAL_BASIS)
DO JL=1,PLAN%MAX_LEVELS
  CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%LEVEL(JL)%FWD)
  CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_ODD)
  CALL EXIT_NATIVE_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
END SUBROUTINE EXIT_NATIVE_GROUPS_DEVICE

SUBROUTINE EXIT_NATIVE_GROUP_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ASSOCIATE(GN=>GROUP%N,GK=>GROUP%K,GLDB=>GROUP%LDB,GS=>GROUP%SRC_COL,&
  & GD=>GROUP%DST_COL,GF=>GROUP%FACTOR_OFFSET)
#ifdef ACCGPU
!$ACC EXIT DATA DELETE(GN,GK,GLDB,GS,GD,GF)
#endif
#ifdef OMPGPU
!$OMP TARGET EXIT DATA MAP(DELETE:GN,GK,GLDB,GS,GD,GF)
#endif
END ASSOCIATE
END SUBROUTINE EXIT_NATIVE_GROUP_DEVICE

SUBROUTINE EXIT_FUSED_LEAF_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_FUSED_LEAF),INTENT(IN) :: GROUP
IF (GROUP%COUNT <= 0) RETURN
ASSOCIATE(GR=>GROUP%ROWS,GK=>GROUP%RANKS,GC=>GROUP%COLUMNS,&
  & GI=>GROUP%INPUT_COL,GO=>GROUP%OUTPUT_COL,GF=>GROUP%FINAL_FACTOR_OFFSET,&
  & GP=>GROUP%PROJECTION_FACTOR_OFFSET,GV=>GROUP%PIVOT_OFFSET)
#ifdef ACCGPU
!$ACC EXIT DATA DELETE(GR,GK,GC,GI,GO,GF,GP,GV)
#endif
#ifdef OMPGPU
!$OMP TARGET EXIT DATA MAP(DELETE:GR,GK,GC,GI,GO,GF,GP,GV)
#endif
END ASSOCIATE
END SUBROUTINE EXIT_FUSED_LEAF_DEVICE

SUBROUTINE EXIT_COMPACT_GROUPS_DEVICE(PLAN)
TYPE(BUTTERFLY_GPU_PLAN),INTENT(IN) :: PLAN
INTEGER(KIND=JPIM) :: JL

CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL0)
DO JL=1,PLAN%MAX_LEVELS
  CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL(JL)%FWD)
  CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_ODD)
  CALL EXIT_COMPACT_GROUP_DEVICE(PLAN%LEVEL(JL)%REV_EVEN)
ENDDO
END SUBROUTINE EXIT_COMPACT_GROUPS_DEVICE

SUBROUTINE EXIT_COMPACT_GROUP_DEVICE(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(IN) :: GROUP
IF (.NOT.ALLOCATED(GROUP%TILE_GROUP)) RETURN
ASSOCIATE(GN=>GROUP%N,GK=>GROUP%K,GS=>GROUP%SRC_COL,GD=>GROUP%DST_COL,&
  & GF=>GROUP%FACTOR_OFFSET,GP=>GROUP%PIVOT_OFFSET,GW=>GROUP%SCRATCH_OFFSET,&
  & GTG=>GROUP%TILE_GROUP,GTS=>GROUP%TILE_START)
#ifdef ACCGPU
!$ACC EXIT DATA DELETE(GN,GK,GS,GD,GF,GP,GW,GTG,GTS)
#endif
#ifdef OMPGPU
!$OMP TARGET EXIT DATA MAP(DELETE:GN,GK,GS,GD,GF,GP,GW,GTG,GTS)
#endif
END ASSOCIATE
END SUBROUTINE EXIT_COMPACT_GROUP_DEVICE

SUBROUTINE FREE_GROUP(GROUP)
TYPE(BUTTERFLY_GPU_GROUPS),INTENT(INOUT) :: GROUP
IF (ALLOCATED(GROUP%N)) DEALLOCATE(GROUP%N)
IF (ALLOCATED(GROUP%K)) DEALLOCATE(GROUP%K)
IF (ALLOCATED(GROUP%LDB)) DEALLOCATE(GROUP%LDB)
IF (ALLOCATED(GROUP%SRC_COL)) DEALLOCATE(GROUP%SRC_COL)
IF (ALLOCATED(GROUP%DST_COL)) DEALLOCATE(GROUP%DST_COL)
IF (ALLOCATED(GROUP%FACTOR_OFFSET)) DEALLOCATE(GROUP%FACTOR_OFFSET)
IF (ALLOCATED(GROUP%PIVOT_OFFSET)) DEALLOCATE(GROUP%PIVOT_OFFSET)
IF (ALLOCATED(GROUP%SCRATCH_OFFSET)) DEALLOCATE(GROUP%SCRATCH_OFFSET)
IF (ALLOCATED(GROUP%TILE_GROUP)) DEALLOCATE(GROUP%TILE_GROUP)
IF (ALLOCATED(GROUP%TILE_START)) DEALLOCATE(GROUP%TILE_START)
GROUP%COUNT=0
GROUP%TILE_COUNT=0
GROUP%SCRATCH_COLS=0
END SUBROUTINE FREE_GROUP

SUBROUTINE FREE_FUSED_LEAF(GROUP)
TYPE(BUTTERFLY_GPU_FUSED_LEAF),INTENT(INOUT) :: GROUP
IF (ALLOCATED(GROUP%ROWS)) DEALLOCATE(GROUP%ROWS)
IF (ALLOCATED(GROUP%RANKS)) DEALLOCATE(GROUP%RANKS)
IF (ALLOCATED(GROUP%COLUMNS)) DEALLOCATE(GROUP%COLUMNS)
IF (ALLOCATED(GROUP%INPUT_COL)) DEALLOCATE(GROUP%INPUT_COL)
IF (ALLOCATED(GROUP%OUTPUT_COL)) DEALLOCATE(GROUP%OUTPUT_COL)
IF (ALLOCATED(GROUP%FINAL_FACTOR_OFFSET)) DEALLOCATE(GROUP%FINAL_FACTOR_OFFSET)
IF (ALLOCATED(GROUP%PROJECTION_FACTOR_OFFSET)) &
  & DEALLOCATE(GROUP%PROJECTION_FACTOR_OFFSET)
IF (ALLOCATED(GROUP%PIVOT_OFFSET)) DEALLOCATE(GROUP%PIVOT_OFFSET)
GROUP%COUNT=0
GROUP%MAX_RANK=0
END SUBROUTINE FREE_FUSED_LEAF

END MODULE BUTTERFLY_GPU_DP_MOD
