#if defined CUDAGPU
#define ACC_GET_HIP_STREAM ACC_GET_CUDA_STREAM
#define OPENACC_LIB OPENACC
#endif

MODULE LEGENDRE_RECURRENCE_GPU_MOD

USE PARKIND_ECTRANS, ONLY: JPIM,JPIB,JPRBT,JPRD

IMPLICIT NONE

PRIVATE
PUBLIC :: BUILD_LEGENDRE_RECURRENCE_DATA
PUBLIC :: LEGENDRE_RECURRENCE_INVERSE_REQUESTED
PUBLIC :: APPLY_LEGENDRE_RECURRENCE_INVERSE

CONTAINS

LOGICAL FUNCTION LEGENDRE_RECURRENCE_INVERSE_REQUESTED()
CHARACTER(LEN=16) :: ZVALUE
INTEGER :: ILENGTH,ISTATUS

CALL GET_ENVIRONMENT_VARIABLE('ECTRANS_GPU_LEGENDRE_RECURRENCE_INVERSE',&
  & ZVALUE,LENGTH=ILENGTH,STATUS=ISTATUS)
LEGENDRE_RECURRENCE_INVERSE_REQUESTED=ISTATUS == 0 .AND. ILENGTH > 0 .AND. &
  & ZVALUE(1:1) == '1'
END FUNCTION LEGENDRE_RECURRENCE_INVERSE_REQUESTED

SUBROUTINE BUILD_LEGENDRE_RECURRENCE_DATA()
USE TPM_DIM, ONLY: R
USE TPM_DISTR, ONLY: D
USE TPM_FIELDS, ONLY: F
USE TPM_FIELDS_GPU, ONLY: FG
USE TPM_GEOMETRY, ONLY: G
USE TPM_GEN, ONLY: NOUT

INTEGER(KIND=JPIM) :: IMLOC,IM,IA,IS,ILA,ILS,IDGLU,ISL
INTEGER(KIND=JPIB) :: ICOEFF_SIZE,ILAT_SIZE

IF (.NOT.LEGENDRE_RECURRENCE_INVERSE_REQUESTED()) RETURN

ICOEFF_SIZE=D%OFFSETS_GEMM2(D%NUMP+1)
ILAT_SIZE=D%OFFSETS_GEMM1(D%NUMP+1)
ALLOCATE(FG%ZREC_A1(ICOEFF_SIZE),FG%ZREC_A2(ICOEFF_SIZE),&
  & FG%ZREC_A3(ICOEFF_SIZE),FG%ZREC_S1(ICOEFF_SIZE),&
  & FG%ZREC_S2(ICOEFF_SIZE),FG%ZREC_S3(ICOEFF_SIZE))
ALLOCATE(FG%ZREC_MU2(ILAT_SIZE),FG%IREC_A_SEED(ILAT_SIZE),&
  & FG%IREC_S_SEED(ILAT_SIZE))
FG%ZREC_A1=0.0_JPRBT
FG%ZREC_A2=0.0_JPRBT
FG%ZREC_A3=0.0_JPRBT
FG%ZREC_S1=0.0_JPRBT
FG%ZREC_S2=0.0_JPRBT
FG%ZREC_S3=0.0_JPRBT
FG%ZREC_MU2=0.0_JPRBT
FG%IREC_A_SEED=0
FG%IREC_S_SEED=0

DO IMLOC=1,D%NUMP
  IM=D%MYMS(IMLOC)
  IF (IM == 0) CYCLE
  IA=1+MOD(R%NSMAX-IM+2,2)
  IS=1+MOD(R%NSMAX-IM+1,2)
  ILA=(R%NSMAX-IM+2)/2
  ILS=(R%NSMAX-IM+3)/2
  IDGLU=G%NDGLU(IM)
  ISL=MAX(R%NDGNH-IDGLU+1,1)
  CALL BUILD_PATH(IMLOC,IM,R%NSMAX+2-IA,ILA,IDGLU,FG%ZAA,&
    & FG%ZREC_A1,FG%ZREC_A2,FG%ZREC_A3,FG%IREC_A_SEED)
  CALL BUILD_PATH(IMLOC,IM,R%NSMAX+2-IS,ILS,IDGLU,FG%ZAS,&
    & FG%ZREC_S1,FG%ZREC_S2,FG%ZREC_S3,FG%IREC_S_SEED)
  DO IS=1,IDGLU
    FG%ZREC_MU2(D%OFFSETS_GEMM1(IMLOC)+IS)=&
      & REAL(F%RMU(ISL+IS-1)**2,JPRBT)
  ENDDO
ENDDO

WRITE(NOUT,'(A,I0,A,I0)') 'GPU Legendre recurrence coefficients=',ICOEFF_SIZE,&
  & ' latitude entries=',ILAT_SIZE

CONTAINS

SUBROUTINE BUILD_PATH(KMLOC,KM,KFIRST_DEGREE,KCOLS,KROWS,PMAT,PC1,PC2,PC3,KSEED)
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC,KM,KFIRST_DEGREE,KCOLS,KROWS
REAL(KIND=JPRBT),INTENT(IN) :: PMAT(:)
REAL(KIND=JPRBT),INTENT(INOUT) :: PC1(:),PC2(:),PC3(:)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSEED(:)
INTEGER(KIND=JPIM) :: IC,IN,JGL,ISEED,ISTRIDE
INTEGER(KIND=JPIB) :: ICOEFF_BASE,IMAT_BASE,ILAT_BASE
REAL(KIND=JPRD) :: ZDENOM
REAL(KIND=JPRBT) :: ZEPS

IF (KCOLS < 1) RETURN
ICOEFF_BASE=D%OFFSETS_GEMM2(KMLOC)
IMAT_BASE=D%OFFSETS_GEMM_MATRIX(KMLOC)
ILAT_BASE=D%OFFSETS_GEMM1(KMLOC)
ISTRIDE=D%LEGENDRE_MATRIX_STRIDES(KMLOC)
DO IC=1,KCOLS-2
  IN=KFIRST_DEGREE-2*(IC-1)
  ZDENOM=DCL(IN-2,KM)
  PC1(ICOEFF_BASE+IC)=REAL(1.0_JPRD/ZDENOM,JPRBT)
  PC2(ICOEFF_BASE+IC)=REAL(-DDL(IN-2,KM)/ZDENOM,JPRBT)
  PC3(ICOEFF_BASE+IC)=REAL(-DCL(IN-4,KM)/ZDENOM,JPRBT)
ENDDO

ZEPS=EPSILON(1.0_JPRBT)
DO JGL=1,KROWS
  ISEED=KCOLS
  DO WHILE (ISEED >= 2)
    IF (PMAT(IMAT_BASE+(ISEED-1)*ISTRIDE+JGL) /= ZEPS .AND. &
      & PMAT(IMAT_BASE+(ISEED-2)*ISTRIDE+JGL) /= ZEPS) EXIT
    ISEED=ISEED-1
  ENDDO
  IF (ISEED < 2) ISEED=0
  KSEED(ILAT_BASE+JGL)=ISEED
ENDDO
END SUBROUTINE BUILD_PATH

REAL(KIND=JPRD) FUNCTION DCL(KN,KM)
INTEGER(KIND=JPIM),INTENT(IN) :: KN,KM
REAL(KIND=JPRD) :: ZN,ZM

ZN=REAL(KN,JPRD)
ZM=REAL(KM,JPRD)
DCL=SQRT(((ZN-ZM+1.0_JPRD)*(ZN-ZM+2.0_JPRD)*&
  & (ZN+ZM+1.0_JPRD)*(ZN+ZM+2.0_JPRD))/&
  & ((2.0_JPRD*ZN+1.0_JPRD)*(2.0_JPRD*ZN+3.0_JPRD)**2*&
  & (2.0_JPRD*ZN+5.0_JPRD)))
END FUNCTION DCL

REAL(KIND=JPRD) FUNCTION DDL(KN,KM)
INTEGER(KIND=JPIM),INTENT(IN) :: KN,KM
REAL(KIND=JPRD) :: ZN,ZM

ZN=REAL(KN,JPRD)
ZM=REAL(KM,JPRD)
DDL=(2.0_JPRD*ZN*(ZN+1.0_JPRD)-2.0_JPRD*ZM*ZM-1.0_JPRD)/&
  & ((2.0_JPRD*ZN-1.0_JPRD)*(2.0_JPRD*ZN+3.0_JPRD))
END FUNCTION DDL

END SUBROUTINE BUILD_LEGENDRE_RECURRENCE_DATA

SUBROUTINE APPLY_LEGENDRE_RECURRENCE_INVERSE(PMAT,PIN,POUT,KLD,KFIELDS,&
  & LSYM,KASYNC)
USE TPM_DIM, ONLY: R
USE TPM_DISTR, ONLY: D
USE TPM_GEOMETRY, ONLY: G
USE TPM_FIELDS_GPU, ONLY: FG

REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PMAT(:),PIN(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: POUT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLD,KFIELDS,KASYNC
LOGICAL,INTENT(IN) :: LSYM

IF (LSYM) THEN
  CALL APPLY_PATH(PMAT,PIN,POUT,KLD,KFIELDS,KASYNC,.TRUE.,&
    & FG%ZREC_S1,FG%ZREC_S2,FG%ZREC_S3,FG%IREC_S_SEED)
ELSE
  CALL APPLY_PATH(PMAT,PIN,POUT,KLD,KFIELDS,KASYNC,.FALSE.,&
    & FG%ZREC_A1,FG%ZREC_A2,FG%ZREC_A3,FG%IREC_A_SEED)
ENDIF

CONTAINS

SUBROUTINE APPLY_PATH(PM,PI,PO,KSTRIDE,KF,KQUEUE,LSP,PC1,PC2,PC3,PSEED)
REAL(KIND=JPRBT),POINTER,INTENT(IN) :: PM(:),PI(:)
REAL(KIND=JPRBT),POINTER,INTENT(INOUT) :: PO(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KSTRIDE,KF,KQUEUE
LOGICAL,INTENT(IN) :: LSP
REAL(KIND=JPRBT),INTENT(IN) :: PC1(:),PC2(:),PC3(:)
INTEGER(KIND=JPIM),INTENT(IN) :: PSEED(:)
INTEGER(KIND=JPIM) :: JMLOC,JM,JGL,JF,JC,ICOLS,ISEED,ISTRIDE
INTEGER(KIND=JPIB) :: IIN_BASE,IOUT_BASE,IMAT_BASE,ICOEFF_BASE,ILAT_POS
REAL(KIND=JPRBT) :: ZSUM,ZP0,ZP1,ZP2,ZMU2

!$ACC PARALLEL LOOP COLLAPSE(3) PRESENT(PM,PI,PO,PC1,PC2,PC3,PSEED) &
!$ACC& PRESENT(D,D%MYMS,D%OFFSETS_GEMM1,D%OFFSETS_GEMM2,D%OFFSETS_GEMM_MATRIX) &
!$ACC& PRESENT(D%LEGENDRE_MATRIX_STRIDES,G,G%NDGLU,R,FG,FG%ZREC_MU2) &
!$ACC& ASYNC(KQUEUE)
DO JMLOC=1,D%NUMP
  DO JGL=1,R%NDGNH
    DO JF=1,KF
      JM=D%MYMS(JMLOC)
      IF (JM == 0 .OR. JGL > G%NDGLU(JM)) CYCLE
      IF (LSP) THEN
        ICOLS=(R%NSMAX-JM+3)/2
      ELSE
        ICOLS=(R%NSMAX-JM+2)/2
      ENDIF
      IIN_BASE=D%OFFSETS_GEMM2(JMLOC)*KSTRIDE
      IOUT_BASE=(D%OFFSETS_GEMM1(JMLOC)+JGL-1)*KSTRIDE
      IMAT_BASE=D%OFFSETS_GEMM_MATRIX(JMLOC)
      ICOEFF_BASE=D%OFFSETS_GEMM2(JMLOC)
      ILAT_POS=D%OFFSETS_GEMM1(JMLOC)+JGL
      ISTRIDE=D%LEGENDRE_MATRIX_STRIDES(JMLOC)
      ISEED=PSEED(ILAT_POS)
      ZMU2=FG%ZREC_MU2(ILAT_POS)
      ZSUM=0.0_JPRBT
      IF (ISEED < 2) THEN
        DO JC=ICOLS,1,-1
          ZSUM=ZSUM+PI(IIN_BASE+(JC-1)*KSTRIDE+JF)*&
            & PM(IMAT_BASE+(JC-1)*ISTRIDE+JGL)
        ENDDO
      ELSE
        DO JC=ICOLS,ISEED+1,-1
          ZSUM=ZSUM+PI(IIN_BASE+(JC-1)*KSTRIDE+JF)*&
            & PM(IMAT_BASE+(JC-1)*ISTRIDE+JGL)
        ENDDO
        ZP0=PM(IMAT_BASE+(ISEED-1)*ISTRIDE+JGL)
        ZSUM=ZSUM+PI(IIN_BASE+(ISEED-1)*KSTRIDE+JF)*ZP0
        ZP1=PM(IMAT_BASE+(ISEED-2)*ISTRIDE+JGL)
        ZSUM=ZSUM+PI(IIN_BASE+(ISEED-2)*KSTRIDE+JF)*ZP1
        DO JC=ISEED-2,1,-1
          ZP2=(PC1(ICOEFF_BASE+JC)*ZMU2+PC2(ICOEFF_BASE+JC))*ZP1+&
            & PC3(ICOEFF_BASE+JC)*ZP0
          ZSUM=ZSUM+PI(IIN_BASE+(JC-1)*KSTRIDE+JF)*ZP2
          ZP0=ZP1
          ZP1=ZP2
        ENDDO
      ENDIF
      PO(IOUT_BASE+JF)=ZSUM
    ENDDO
  ENDDO
ENDDO
END SUBROUTINE APPLY_PATH

END SUBROUTINE APPLY_LEGENDRE_RECURRENCE_INVERSE

END MODULE LEGENDRE_RECURRENCE_GPU_MOD
