#define ALIGN(I, A) (((I)+(A)-1)/(A)*(A))
! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! (C) Copyright 2022- NVIDIA.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE LTINV_MOD
  USE BUFFERED_ALLOCATOR_MOD, ONLY: ALLOCATION_RESERVATION_HANDLE

  IMPLICIT NONE

  PRIVATE
  PUBLIC :: LTINV, LTINV_HANDLE, PREPARE_LTINV

  TYPE LTINV_HANDLE
    TYPE(ALLOCATION_RESERVATION_HANDLE) :: HPIA_AND_IN
    TYPE(ALLOCATION_RESERVATION_HANDLE) :: HOUTS_AND_OUTA
  END TYPE

CONTAINS
  FUNCTION PREPARE_LTINV(ALLOCATOR,KF_UV,KF_SCALARS,LVORGP,LDIVGP,LSCDERS) RESULT(HLTINV)
    USE PARKIND_ECTRANS,        ONLY: JPIM, JPRBT, JPRD, JPIB
    USE TPM_DISTR,              ONLY: D
    USE TPM_DIM,                ONLY: R
    USE ISO_C_BINDING,          ONLY: C_SIZEOF
    USE LEINV_MOD,              ONLY: LEINV_STRIDES
    USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR, RESERVE

    IMPLICIT NONE

    TYPE(BUFFERED_ALLOCATOR), INTENT(INOUT) :: ALLOCATOR
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_UV,KF_SCALARS
    LOGICAL, INTENT(IN) :: LVORGP,LDIVGP,LSCDERS

    TYPE(LTINV_HANDLE) :: HLTINV

    INTEGER(KIND=JPIB) :: IALLOC_SZ
    INTEGER(KIND=JPIM)  :: IOUT_STRIDES0
    INTEGER(KIND=JPIB)  :: IOUT_SIZE
    INTEGER(KIND=JPIM)  :: IOUT0_STRIDES0, IOUT0_SIZE
    INTEGER(KIND=JPIM)  :: IIN_STRIDES0
    INTEGER(KIND=JPIB)  :: IIN_SIZE
    INTEGER(KIND=JPIM)  :: IIN0_STRIDES0, IIN0_SIZE

    REAL(KIND=JPRBT) :: ZPRBT_DUMMY
    REAL(KIND=JPRD) :: ZPRD_DUMMY

    INTEGER(KIND=JPIM) :: IF_READIN, IF_LEG

    ! # fields that are initially read. We always read vorticity
    ! and divergence! Also keep in mind that we actually have 2X
    ! this number of levels because real+complex
    IF_READIN = 0
    IF_READIN = IF_READIN + KF_UV ! Vorticity or divergence
    IF_READIN = IF_READIN + KF_UV ! Vorticity or divergence
    IF_READIN = IF_READIN + KF_UV ! U
    IF_READIN = IF_READIN + KF_UV ! V
    IF_READIN = IF_READIN + KF_SCALARS ! Scalars
    IF (LSCDERS) &
      IF_READIN = IF_READIN + KF_SCALARS ! Scalars NS Derivatives

    ! In Legendre space, we then ignore vorticity/divergence, if
    ! they don't need to be transformed.
    IF_LEG = IF_READIN
    IF(.NOT. LVORGP) IF_LEG = IF_LEG - KF_UV ! No vorticity needed
    IF(.NOT. LDIVGP) IF_LEG = IF_LEG - KF_UV ! No divergence needed

    CALL LEINV_STRIDES(IF_LEG,IOUT_STRIDES0,IOUT_SIZE,IIN_STRIDES0,IIN_SIZE,&
                       IOUT0_STRIDES0,IOUT0_SIZE,IIN0_STRIDES0,IIN0_SIZE)

    IALLOC_SZ = 0
    ! ZINPA
    IALLOC_SZ = IALLOC_SZ + ALIGN(IIN_SIZE*C_SIZEOF(ZPRBT_DUMMY),128)
    ! ZINPA0
    IALLOC_SZ = IALLOC_SZ + ALIGN(IIN0_SIZE*C_SIZEOF(ZPRD_DUMMY),128)
    ! ZINPS
    IALLOC_SZ = IALLOC_SZ + ALIGN(IIN_SIZE*C_SIZEOF(ZPRBT_DUMMY),128)
    ! ZINPS0
    IALLOC_SZ = IALLOC_SZ + ALIGN(IIN0_SIZE*C_SIZEOF(ZPRD_DUMMY),128)

    HLTINV%HPIA_AND_IN = RESERVE(ALLOCATOR, IALLOC_SZ, "HLTINV_HPIA_AND_IN")

    IALLOC_SZ = 0
    ! ZOUTA
    IALLOC_SZ = IALLOC_SZ + ALIGN(IOUT_SIZE*C_SIZEOF(ZPRBT_DUMMY),128)
    ! ZOUTS
    IALLOC_SZ = IALLOC_SZ + ALIGN(IOUT_SIZE*C_SIZEOF(ZPRBT_DUMMY),128)
    ! ZOUTA0
    IALLOC_SZ = IALLOC_SZ + ALIGN(IOUT0_SIZE*C_SIZEOF(ZPRD_DUMMY),128)
    ! ZOUTS0
    IALLOC_SZ = IALLOC_SZ + ALIGN(IOUT0_SIZE*C_SIZEOF(ZPRD_DUMMY),128)

    HLTINV%HOUTS_AND_OUTA = RESERVE(ALLOCATOR, IALLOC_SZ, "HLTINV_HOUTS_AND_OUTA")

  END FUNCTION PREPARE_LTINV

  SUBROUTINE LTINV(ALLOCATOR,HLTINV,KF_UV,KF_SCALARS,&
     & PSPVOR,PSPDIV,PSPSCALAR,PSPSC3A,PSPSC3B,PSPSC2, &
     & ZOUTS,ZOUTA,ZOUTS0,ZOUTA0)

    USE PARKIND_ECTRANS,        ONLY: JPIM, JPRB, JPRBT, JPRD, JPIB
    USE YOMHOOK,                ONLY: LHOOK, DR_HOOK, JPHOOK
    USE TPM_DIM,                ONLY: R
    USE TPM_TRANS,              ONLY: LDIVGP, LVORGP, NF_SC2, NF_SC3A, NF_SC3B, LSCDERS
    USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR, ASSIGN_PTR, GET_ALLOCATION
    USE TPM_DISTR,              ONLY: D
    USE LTINV_PACK_MOD,         ONLY: LTINV_PACK_SPEC, LTINV_PACK_UV, LTINV_PACK_NSDER
    USE LEINV_MOD,              ONLY: LEINV_STRIDES, LEINV_GEMM_ANTISYM, LEINV_GEMM_SYM
    USE ABORT_TRANS_MOD,        ONLY: ABORT_TRANS
    USE TPM_FIELDS_GPU,         ONLY: FG
    USE MPL_MODULE,             ONLY: MPL_BARRIER,MPL_ALL_MS_COMM
    USE TPM_GEN,                ONLY: LSYNC_TRANS
    USE TPM_STATS,              ONLY: GSTATS => GSTATS_NVTX
    USE ISO_C_BINDING,          ONLY: C_SIZEOF

    !**** *LTINV* - Inverse Legendre transform
    !
    !     Purpose.
    !     --------
    !        Tranform from Laplace space to Fourier space, compute U and V
    !        and north/south derivatives of state variables.

    !**   Interface.
    !     ----------
    !        *CALL* *LTINV(...)

    !        Explicit arguments :
    !        --------------------
    !          KM        - zonal wavenumber
    !          KMLOC     - local zonal wavenumber
    !          PSPVOR    - spectral vorticity
    !          PSPDIV    - spectral divergence
    !          PSPSCALAR - spectral scalar variables

    !        Implicit arguments :  The Laplace arrays of the model.
    !        --------------------  The values of the Legendre polynomials
    !                              The grid point arrays of the model
    !     Method.
    !     -------

    !     Externals.
    !     ----------

    !         PREPSNM - prepare REPSNM for wavenumber KM
    !         LTINV_PACK_* - prepare packed Legendre inputs
    !         LEINV_GEMM_* - inverse Legendre GEMM

    !     Reference.
    !     ----------
    !        ECMWF Research Department documentation of the IFS
    !        Temperton, 1991, MWR 119 p1303

    !     Author.
    !     -------
    !        Mats Hamrud  *ECMWF*

    !     Modifications.
    !     --------------
    !        Original : 00-02-01 From LTINV in IFS CY22R1
    !     ------------------------------------------------------------------

    IMPLICIT NONE


    INTEGER(KIND=JPIM), INTENT(IN) :: KF_UV
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCALARS

    REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PSPVOR(:,:)
    REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PSPDIV(:,:)
    REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PSPSCALAR(:,:)
    REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PSPSC2(:,:)
    REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PSPSC3A(:,:,:)
    REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PSPSC3B(:,:,:)
    REAL(KIND=JPRBT), POINTER, INTENT(OUT) :: ZOUTS(:), ZOUTA(:)
    REAL(KIND=JPRD), POINTER, INTENT(OUT) :: ZOUTS0(:), ZOUTA0(:)

    INTEGER(KIND=JPIM) :: IFIRST, J3

    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
    TYPE(BUFFERED_ALLOCATOR), INTENT(IN) :: ALLOCATOR
    TYPE(LTINV_HANDLE), INTENT(IN) :: HLTINV

    INTEGER(KIND=JPIM)  :: IOUT_STRIDES0
    INTEGER(KIND=JPIB)  :: IOUT_SIZE
    INTEGER(KIND=JPIM)  :: IOUT0_STRIDES0, IOUT0_SIZE
    INTEGER(KIND=JPIM)  :: IIN_STRIDES0
    INTEGER(KIND=JPIB)  :: IIN_SIZE
    INTEGER(KIND=JPIM)  :: IIN0_STRIDES0, IIN0_SIZE

    INTEGER(KIND=JPIM) :: IF_READIN, IF_LEG
    INTEGER(KIND=JPIM) :: ISCALAR_OFFSET, IDER_OFFSET, ISCALAR_COUNT
    INTEGER(KIND=JPIB) :: IALLOC_POS, IALLOC_SZ

    REAL(KIND=JPRBT), POINTER :: ZINPA(:), ZINPS(:)
    REAL(KIND=JPRD), POINTER :: ZINPA0(:), ZINPS0(:)

    ASSOCIATE(ZEPSNM=>FG%ZEPSNM)

    !     ------------------------------------------------------------------

    !*       1.       PERFORM LEGENDRE TRANFORM.
    !                 --------------------------

    IF (LHOOK) CALL DR_HOOK('LTINV_MOD',0,ZHOOK_HANDLE)

    ! Get all pointers
    IF_READIN = 0
    IF_READIN = IF_READIN + KF_UV ! Vorticity or divergence
    IF_READIN = IF_READIN + KF_UV ! Vorticity or divergence
    IF_READIN = IF_READIN + KF_UV ! U
    IF_READIN = IF_READIN + KF_UV ! V
    IF_READIN = IF_READIN + KF_SCALARS ! Scalars
    IF (LSCDERS) &
      IF_READIN = IF_READIN + KF_SCALARS ! Scalars NS Derivatives

    ! In Legendre space, we then ignore vorticity/divergence, if
    ! they don't need to be transformed.
    IF_LEG = IF_READIN
    IF(.NOT. LVORGP) IF_LEG = IF_LEG - KF_UV ! No vorticity needed
    IF(.NOT. LDIVGP) IF_LEG = IF_LEG - KF_UV ! No divergence needed

    CALL LEINV_STRIDES(IF_LEG,IOUT_STRIDES0,IOUT_SIZE,IIN_STRIDES0,IIN_SIZE,&
                       IOUT0_STRIDES0,IOUT0_SIZE,IIN0_STRIDES0,IIN0_SIZE)

    IALLOC_POS = 1

    ! ZINPA
    IALLOC_SZ = ALIGN(IIN_SIZE*C_SIZEOF(ZINPA(1)),128)
    CALL ASSIGN_PTR(ZINPA, GET_ALLOCATION(ALLOCATOR, HLTINV%HPIA_AND_IN),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    ! ZINPA0
    IALLOC_SZ = ALIGN(IIN0_SIZE*C_SIZEOF(ZINPA0(1)),128)
    CALL ASSIGN_PTR(ZINPA0, GET_ALLOCATION(ALLOCATOR, HLTINV%HPIA_AND_IN),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    ! ZINPS
    IALLOC_SZ = ALIGN(IIN_SIZE*C_SIZEOF(ZINPS(1)),128)
    CALL ASSIGN_PTR(ZINPS, GET_ALLOCATION(ALLOCATOR, HLTINV%HPIA_AND_IN),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    ! ZINPS0
    IALLOC_SZ = ALIGN(IIN0_SIZE*C_SIZEOF(ZINPS0(1)),128)
    CALL ASSIGN_PTR(ZINPS0, GET_ALLOCATION(ALLOCATOR, HLTINV%HPIA_AND_IN),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    IALLOC_POS = 1

    ! ZOUTA
    IALLOC_SZ = ALIGN(IOUT_SIZE*C_SIZEOF(ZOUTA(1)),128)
    CALL ASSIGN_PTR(ZOUTA, GET_ALLOCATION(ALLOCATOR, HLTINV%HOUTS_AND_OUTA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    ! ZOUTS
    IALLOC_SZ = ALIGN(IOUT_SIZE*C_SIZEOF(ZOUTS(1)),128)
    CALL ASSIGN_PTR(ZOUTS, GET_ALLOCATION(ALLOCATOR, HLTINV%HOUTS_AND_OUTA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    ! ZOUTA0
    IALLOC_SZ = ALIGN(IOUT0_SIZE*C_SIZEOF(ZOUTA0(1)),128)
    CALL ASSIGN_PTR(ZOUTA0, GET_ALLOCATION(ALLOCATOR, HLTINV%HOUTS_AND_OUTA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    ! ZOUTS0
    IALLOC_SZ = ALIGN(IOUT0_SIZE*C_SIZEOF(ZOUTS0(1)),128)
    CALL ASSIGN_PTR(ZOUTS0, GET_ALLOCATION(ALLOCATOR, HLTINV%HOUTS_AND_OUTA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS = IALLOC_POS + IALLOC_SZ

    !     ------------------------------------------------------------------


    !*       3.    SPECTRAL COMPUTATIONS FOR U,V AND DERIVATIVES.
    !              ----------------------------------------------

    IF (LSYNC_TRANS) THEN
      CALL GSTATS(440,0)
      CALL MPL_BARRIER(MPL_ALL_MS_COMM,CDSTRING='')
      CALL GSTATS(440,1)
    ENDIF
    CALL GSTATS(422,0)
    CALL GSTATS(474,0)
#ifdef OMPGPU
    !$OMP TARGET DATA MAP(TO:PSPVOR,PSPDIV) IF(KF_UV > 0)
    !$OMP TARGET DATA MAP(TO:PSPSCALAR) IF(PRESENT(PSPSCALAR) .AND. KF_SCALARS > 0)
    !$OMP TARGET DATA MAP(TO:PSPSC2) IF(NF_SC2 > 0)
    !$OMP TARGET DATA MAP(TO:PSPSC3A) IF(NF_SC3A > 0)
    !$OMP TARGET DATA MAP(TO:PSPSC3B) IF(NF_SC3B > 0)
#endif
#ifdef ACCGPU
    !$ACC DATA COPYIN(PSPVOR,PSPDIV) IF(KF_UV > 0)
    !$ACC DATA COPYIN(PSPSCALAR) IF(PRESENT(PSPSCALAR) .AND. KF_SCALARS > 0)
    !$ACC DATA COPYIN(PSPSC2) IF(NF_SC2 > 0)
    !$ACC DATA COPYIN(PSPSC3A) IF(NF_SC3A > 0)
    !$ACC DATA COPYIN(PSPSC3B) IF(NF_SC3B > 0)
#endif
    IF (LSYNC_TRANS) THEN
      CALL GSTATS(442,0)
      CALL MPL_BARRIER(MPL_ALL_MS_COMM,CDSTRING='')
      CALL GSTATS(442,1)
    ENDIF
    CALL GSTATS(474,1)
    CALL GSTATS(422,1)

    CALL GSTATS(470,0)
    IFIRST = 0
    IF (KF_UV > 0 .AND. LVORGP) THEN
      CALL LTINV_PACK_SPEC(ZINPA,ZINPA0,PSPVOR,KF_UV,IFIRST,.TRUE.,&
                         & IIN_STRIDES0,IIN0_STRIDES0)
      IFIRST = IFIRST + KF_UV
    ENDIF
    IF (KF_UV > 0 .AND. LDIVGP) THEN
      CALL LTINV_PACK_SPEC(ZINPA,ZINPA0,PSPDIV,KF_UV,IFIRST,.TRUE.,&
                         & IIN_STRIDES0,IIN0_STRIDES0)
      IFIRST = IFIRST + KF_UV
    ENDIF
    IF (KF_UV > 0) THEN
      CALL LTINV_PACK_UV(ZINPA,ZINPA0,PSPVOR,PSPDIV,KF_UV,IFIRST,IFIRST+KF_UV,&
                       & .TRUE.,ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
      IFIRST = IFIRST + 2*KF_UV
    ENDIF
    IF (KF_SCALARS > 0) THEN
      ISCALAR_OFFSET = IFIRST
      IDER_OFFSET = ISCALAR_OFFSET + KF_SCALARS
      ISCALAR_COUNT = 0
      IF(PRESENT(PSPSCALAR)) THEN
        CALL LTINV_PACK_SPEC(ZINPA,ZINPA0,PSPSCALAR,KF_SCALARS,ISCALAR_OFFSET,.TRUE.,&
                           & IIN_STRIDES0,IIN0_STRIDES0)
        IF (LSCDERS) THEN
          CALL LTINV_PACK_NSDER(ZINPA,ZINPA0,PSPSCALAR,KF_SCALARS,IDER_OFFSET,.TRUE.,&
                              & ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
        ENDIF
        ISCALAR_COUNT = KF_SCALARS
      ELSE
        IF(PRESENT(PSPSC2) .AND. NF_SC2 > 0) THEN
          CALL LTINV_PACK_SPEC(ZINPA,ZINPA0,PSPSC2(:,:),NF_SC2,ISCALAR_OFFSET+ISCALAR_COUNT,&
                             & .TRUE.,IIN_STRIDES0,IIN0_STRIDES0)
          IF (LSCDERS) THEN
            CALL LTINV_PACK_NSDER(ZINPA,ZINPA0,PSPSC2(:,:),NF_SC2,IDER_OFFSET+ISCALAR_COUNT,&
                                & .TRUE.,ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
          ENDIF
          ISCALAR_COUNT = ISCALAR_COUNT + NF_SC2
        ENDIF
        IF(PRESENT(PSPSC3A) .AND. NF_SC3A > 0) THEN
          DO J3=1,UBOUND(PSPSC3A,3)
            CALL LTINV_PACK_SPEC(ZINPA,ZINPA0,PSPSC3A(:,:,J3),NF_SC3A,&
                               & ISCALAR_OFFSET+ISCALAR_COUNT,.TRUE.,&
                               & IIN_STRIDES0,IIN0_STRIDES0)
            IF (LSCDERS) THEN
              CALL LTINV_PACK_NSDER(ZINPA,ZINPA0,PSPSC3A(:,:,J3),NF_SC3A,&
                                  & IDER_OFFSET+ISCALAR_COUNT,.TRUE.,&
                                  & ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
            ENDIF
            ISCALAR_COUNT = ISCALAR_COUNT + NF_SC3A
          ENDDO
        ENDIF
        IF(PRESENT(PSPSC3B) .AND. NF_SC3B > 0) THEN
          DO J3=1,UBOUND(PSPSC3B,3)
            CALL LTINV_PACK_SPEC(ZINPA,ZINPA0,PSPSC3B(:,:,J3),NF_SC3B,&
                               & ISCALAR_OFFSET+ISCALAR_COUNT,.TRUE.,&
                               & IIN_STRIDES0,IIN0_STRIDES0)
            IF (LSCDERS) THEN
              CALL LTINV_PACK_NSDER(ZINPA,ZINPA0,PSPSC3B(:,:,J3),NF_SC3B,&
                                  & IDER_OFFSET+ISCALAR_COUNT,.TRUE.,&
                                  & ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
            ENDIF
            ISCALAR_COUNT = ISCALAR_COUNT + NF_SC3B
          ENDDO
        ENDIF
      ENDIF
      IF(ISCALAR_COUNT /= KF_SCALARS) THEN
        WRITE(0,*) 'LTINV:KF_SCALARS,ISCALAR_COUNT',KF_SCALARS,ISCALAR_COUNT
        CALL ABORT_TRANS('LTINV_MOD:ISCALAR_COUNT /= KF_SCALARS')
      ENDIF
      IFIRST = ISCALAR_OFFSET + KF_SCALARS
      IF (LSCDERS) IFIRST = IFIRST + KF_SCALARS
    ENDIF
    IF(IFIRST /= IF_LEG) THEN
      WRITE(0,*) 'LTINV:IF_LEG,IFIRST',IF_LEG,IFIRST
      CALL ABORT_TRANS('LTINV_MOD:IFIRST /= IF_LEG')
    ENDIF
    ! Padding slots are outside the grouped GEMM K extent, so no separate
    ! clear kernel is needed here.
    IF (LSYNC_TRANS) THEN
#ifdef ACCGPU
      !$ACC WAIT(1)
#endif
      CALL GSTATS(470,1)
      CALL GSTATS(440,0)
      CALL MPL_BARRIER(MPL_ALL_MS_COMM,CDSTRING='')
      CALL GSTATS(440,1)
    ELSE
      CALL GSTATS(470,1)
    ENDIF

    CALL GSTATS(472,0)
    IFIRST = 0
    IF (KF_UV > 0 .AND. LVORGP) THEN
      CALL LTINV_PACK_SPEC(ZINPS,ZINPS0,PSPVOR,KF_UV,IFIRST,.FALSE.,&
                         & IIN_STRIDES0,IIN0_STRIDES0)
      IFIRST = IFIRST + KF_UV
    ENDIF
    IF (KF_UV > 0 .AND. LDIVGP) THEN
      CALL LTINV_PACK_SPEC(ZINPS,ZINPS0,PSPDIV,KF_UV,IFIRST,.FALSE.,&
                         & IIN_STRIDES0,IIN0_STRIDES0)
      IFIRST = IFIRST + KF_UV
    ENDIF
    IF (KF_UV > 0) THEN
      CALL LTINV_PACK_UV(ZINPS,ZINPS0,PSPVOR,PSPDIV,KF_UV,IFIRST,IFIRST+KF_UV,&
                       & .FALSE.,ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
      IFIRST = IFIRST + 2*KF_UV
    ENDIF
    IF (KF_SCALARS > 0) THEN
      ISCALAR_OFFSET = IFIRST
      IDER_OFFSET = ISCALAR_OFFSET + KF_SCALARS
      ISCALAR_COUNT = 0
      IF(PRESENT(PSPSCALAR)) THEN
        CALL LTINV_PACK_SPEC(ZINPS,ZINPS0,PSPSCALAR,KF_SCALARS,ISCALAR_OFFSET,.FALSE.,&
                           & IIN_STRIDES0,IIN0_STRIDES0)
        IF (LSCDERS) THEN
          CALL LTINV_PACK_NSDER(ZINPS,ZINPS0,PSPSCALAR,KF_SCALARS,IDER_OFFSET,.FALSE.,&
                              & ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
        ENDIF
        ISCALAR_COUNT = KF_SCALARS
      ELSE
        IF(PRESENT(PSPSC2) .AND. NF_SC2 > 0) THEN
          CALL LTINV_PACK_SPEC(ZINPS,ZINPS0,PSPSC2(:,:),NF_SC2,ISCALAR_OFFSET+ISCALAR_COUNT,&
                             & .FALSE.,IIN_STRIDES0,IIN0_STRIDES0)
          IF (LSCDERS) THEN
            CALL LTINV_PACK_NSDER(ZINPS,ZINPS0,PSPSC2(:,:),NF_SC2,IDER_OFFSET+ISCALAR_COUNT,&
                                & .FALSE.,ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
          ENDIF
          ISCALAR_COUNT = ISCALAR_COUNT + NF_SC2
        ENDIF
        IF(PRESENT(PSPSC3A) .AND. NF_SC3A > 0) THEN
          DO J3=1,UBOUND(PSPSC3A,3)
            CALL LTINV_PACK_SPEC(ZINPS,ZINPS0,PSPSC3A(:,:,J3),NF_SC3A,&
                               & ISCALAR_OFFSET+ISCALAR_COUNT,.FALSE.,&
                               & IIN_STRIDES0,IIN0_STRIDES0)
            IF (LSCDERS) THEN
              CALL LTINV_PACK_NSDER(ZINPS,ZINPS0,PSPSC3A(:,:,J3),NF_SC3A,&
                                  & IDER_OFFSET+ISCALAR_COUNT,.FALSE.,&
                                  & ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
            ENDIF
            ISCALAR_COUNT = ISCALAR_COUNT + NF_SC3A
          ENDDO
        ENDIF
        IF(PRESENT(PSPSC3B) .AND. NF_SC3B > 0) THEN
          DO J3=1,UBOUND(PSPSC3B,3)
            CALL LTINV_PACK_SPEC(ZINPS,ZINPS0,PSPSC3B(:,:,J3),NF_SC3B,&
                               & ISCALAR_OFFSET+ISCALAR_COUNT,.FALSE.,&
                               & IIN_STRIDES0,IIN0_STRIDES0)
            IF (LSCDERS) THEN
              CALL LTINV_PACK_NSDER(ZINPS,ZINPS0,PSPSC3B(:,:,J3),NF_SC3B,&
                                  & IDER_OFFSET+ISCALAR_COUNT,.FALSE.,&
                                  & ZEPSNM,IIN_STRIDES0,IIN0_STRIDES0)
            ENDIF
            ISCALAR_COUNT = ISCALAR_COUNT + NF_SC3B
          ENDDO
        ENDIF
      ENDIF
      IF(ISCALAR_COUNT /= KF_SCALARS) THEN
        WRITE(0,*) 'LTINV:KF_SCALARS,ISCALAR_COUNT',KF_SCALARS,ISCALAR_COUNT
        CALL ABORT_TRANS('LTINV_MOD:ISCALAR_COUNT /= KF_SCALARS')
      ENDIF
      IFIRST = ISCALAR_OFFSET + KF_SCALARS
      IF (LSCDERS) IFIRST = IFIRST + KF_SCALARS
    ENDIF
    IF(IFIRST /= IF_LEG) THEN
      WRITE(0,*) 'LTINV:IF_LEG,IFIRST',IF_LEG,IFIRST
      CALL ABORT_TRANS('LTINV_MOD:IFIRST /= IF_LEG')
    ENDIF
    ! Padding slots are outside the grouped GEMM K extent, so no separate
    ! clear kernel is needed here.
    IF (LSYNC_TRANS) THEN
#ifdef ACCGPU
      !$ACC WAIT(1)
#endif
      CALL GSTATS(472,1)
      CALL GSTATS(440,0)
      CALL MPL_BARRIER(MPL_ALL_MS_COMM,CDSTRING='')
      CALL GSTATS(440,1)
    ELSE
      CALL GSTATS(472,1)
    ENDIF
    CALL GSTATS(475,0)
#ifdef OMPGPU
    !$OMP END TARGET DATA
    !$OMP END TARGET DATA
    !$OMP END TARGET DATA
    !$OMP END TARGET DATA
    !$OMP END TARGET DATA
#endif
#ifdef ACCGPU
    !$ACC END DATA
    !$ACC END DATA
    !$ACC END DATA
    !$ACC END DATA
    !$ACC END DATA
#endif
    CALL GSTATS(475,1)

    CALL LEINV_GEMM_ANTISYM(ALLOCATOR,ZINPA,ZINPA0,ZOUTA,ZOUTA0,IF_LEG)
    CALL LEINV_GEMM_SYM(ALLOCATOR,ZINPS,ZINPS0,ZOUTS,ZOUTS0,IF_LEG)

    IF (LHOOK) CALL DR_HOOK('LTINV_MOD',1,ZHOOK_HANDLE)
    END ASSOCIATE
    !     ------------------------------------------------------------------
  END SUBROUTINE LTINV
END MODULE LTINV_MOD
